(() => {
  'use strict';

  const terms = [
    ['Meaningful Human Control over Autonomous Systems: A Philosophical Account', '자율시스템에 대한 의미 있는 인간 통제: 철학적 설명'],
    ['Attributing Agency to Automated Systems: Reflections on Human–Robot Collaborations and Responsibility-Loci', '자동화시스템에 행위자성 귀속하기: 인간-로봇 협업과 책임의 위치에 관한 성찰'],
    ['The Responsibility Gap: Ascribing Responsibility for the Actions of Learning Automata', '책임공백: 학습 자동기계의 행위에 대한 책임 귀속'],
    ['Rights of Non-humans? Electronic Agents and Animals as New Actors in Politics and Law', '비인간의 권리? 정치와 법의 새로운 행위자로서의 전자적 에이전트와 동물'],
    ['Of, for, and by the People: The Legal Lacuna of Synthetic Persons', '사람에 의한·사람을 위한·사람의: 합성적 인격체의 법적 공백'],
    ['Computer Systems: Moral Entities but Not Moral Agents', '컴퓨터시스템: 도덕적 평가대상이지만 도덕적 행위자는 아님'],
    ['Artificial Intelligence and the Limits of Legal Personality', '인공지능과 법인격의 한계'],
    ['The Fundamental Right as a Right of Defence and a State Duty to Protect', '방어권 및 국가의 보호의무로서의 기본권'],
    ['Proportionality: Constitutional Rights and their Limitations', '비례성: 헌법적 권리와 그 제한'],
    ['The Other Question: Can and Should Robots Have Rights?', '또 다른 질문: 로봇은 권리를 가질 수 있으며 가져야 하는가?'],
    ['A Legal Theory for Autonomous Artificial Agents', '자율형 인공 에이전트를 위한 법이론'],
    ['The Laws of Robots: Crimes, Contracts, and Torts', '로봇의 법: 범죄, 계약, 불법행위'],
    ['The Historic Background of Corporate Legal Personality', '법인격의 역사적 배경'],
    ['Law’s Meaning of Life: Philosophy, Religion, Darwin and the Legal Person', '법이 의미하는 생명: 철학, 종교, 다윈과 법적 인격'],
    ['Legal Personhood for Artificial Intelligences', '인공지능을 위한 법인격'],
    ['Fundamental Rights as Constitutional Principles', '헌법원리로서의 기본권'],
    ['Constitutional and Political Theory: Selected Writings', '헌법 및 정치이론: 선집'],
    ['Return to the Traditional Understanding of Fundamental Rights?', '기본권에 대한 전통적 이해로의 회귀?'],
    ['Fairness and Utility in Tort Theory', '불법행위 이론에서의 공정성과 효용'],
    ['Distributed Morality in an Information Society', '정보사회에서의 분산된 도덕성'],
    ['On the Morality of Artificial Agents', '인공적 행위자의 도덕성에 관하여'],
    ['Fundamental Legal Conceptions as Applied in Judicial Reasoning', '사법적 추론에 적용되는 기본적 법개념'],
    ['An Introduction to the Principles of Morals and Legislation', '도덕과 입법의 원리 서설'],
    ['Groundwork of the Metaphysics of Morals', '도덕형이상학 정초'],
    ['The Province of Jurisprudence Determined', '법리학의 영역'],
    ['System des heutigen Römischen Rechts', '오늘날의 로마법 체계'],
    ['Lehrbuch des Pandektenrechts', '판덱텐법 교과서'],
    ['Das deutsche Genossenschaftsrecht', '독일 단체법'],
    ['Statutory Lawlessness and Supra-Statutory Law', '법률적 불법과 초법률적 법'],
    ['A Theory of Constitutional Rights', '기본권 이론'],
    ['A Theory of Legal Argumentation', '법적 논증 이론'],
    ['Purposive Interpretation in Law', '법에서의 목적론적 해석'],
    ['A Theory of Legal Personhood', '법인격 이론'],
    ['Responsibility in Law and Morality', '법과 도덕에서의 책임'],
    ['Legal Reasoning and Legal Theory', '법적 추론과 법이론'],
    ['Rhetoric and the Rule of Law', '수사학과 법치주의'],
    ['The Metaphysics of Morals', '도덕형이상학'],
    ['Two Treatises of Government', '통치론 두 편'],
    ['Der Kampf ums Recht', '권리를 위한 투쟁'],
    ['Der Zweck im Recht', '법에 있어서의 목적'],
    ['Allgemeine Staatslehre', '일반국가학'],
    ['Pure Theory of Law', '순수법학'],
    ['General Theory of Law and State', '법과 국가의 일반이론'],
    ['The Concept of Law', '법의 개념'],
    ['Punishment and Responsibility', '형벌과 책임'],
    ['The Morality of Law', '법의 도덕성'],
    ['A Theory of Justice', '정의론'],
    ['Political Liberalism', '정치적 자유주의'],
    ['Justice as Fairness', '공정으로서의 정의'],
    ['Anarchy, State, and Utopia', '무정부, 국가, 유토피아'],
    ['Taking Rights Seriously', '권리를 진지하게 받아들이기'],
    ['Law’s Empire', '법의 제국'],
    ['The Authority of Law', '법의 권위'],
    ['The Morality of Freedom', '자유의 도덕성'],
    ['Natural Law and Natural Rights', '자연법과 자연권'],
    ['Between Facts and Norms', '사실성과 타당성'],
    ['The Idea of Private Law', '사법의 이념'],
    ['The Costs of Accidents', '사고비용'],
    ['Playing by the Rules', '규칙에 따라 행동하기'],
    ['Grundzüge des Verfassungsrechts der Bundesrepublik Deutschland', '독일연방공화국 헌법의 기본개요'],
    ['Die offene Gesellschaft der Verfassungsinterpreten', '열린 헌법해석자 사회'],
    ['Der Grundrechtssatz von der Menschenwürde', '인간존엄의 기본권 조항'],
    ['Responsibility and Fault', '책임과 과실'],
    ['Causation in the Law', '법에서의 인과관계'],
    ['Risks and Wrongs', '위험과 잘못'],
    ['Private Wrongs', '사적 잘못'],
    ['Robot Rights', '로봇 권리'],
    ['Nicomachean Ethics, Book V', '니코마코스 윤리학 제5권'],
    ['Nicomachean Ethics', '니코마코스 윤리학'],
    ['Politics', '정치학'],
    ['Summa Theologiae, Treatise on Law', '신학대전, 법론'],
    ['Leviathan', '리바이어던'],
    ['On Liberty', '자유론'],
    ['Legal Philosophy', '법철학'],
    ['meaningful human control', '의미 있는 인간 통제'],
    ['responsibility abundance', '책임의 다중·과잉 상태'],
    ['moral responsibility gap', '도덕적 책임공백'],
    ['civil liability gap', '민사책임 공백'],
    ['responsibility taxonomy', '책임 개념의 유형론'],
    ['responsibility gap', '책임공백'],
    ['artificial moral agency', '인공적 도덕 행위자성'],
    ['moral agency', '도덕적 행위자성'],
    ['technical agency', '기술적 행위자성'],
    ['legal agency', '법적 행위자성'],
    ['AI agency', 'AI 행위자성'],
    ['agency attribution', '행위자성 귀속'],
    ['attribution of contracts', '계약효과의 귀속'],
    ['legal personhood', '법인격'],
    ['AI legal personhood', 'AI 법인격'],
    ['AI personhood', 'AI 법인격'],
    ['synthetic personhood', '합성적 법인격'],
    ['synthetic persons', '합성적 법적 인격체'],
    ['functional personhood', '기능적 법인격'],
    ['bundle theory of legal personhood', '법인격의 묶음 이론'],
    ['legal personality', '법인격'],
    ['AI legal personality', 'AI 법인격'],
    ['juridical personality', '법적 인격'],
    ['corporate personality', '법인격'],
    ['legal person / legal thing distinction', '법적 사람/법적 사물 구별'],
    ['legal person', '법적 인격체'],
    ['legal subject', '법적 주체'],
    ['person-thing distinction', '사람-사물 구별'],
    ['personhood boundary', '법인격의 경계'],
    ['law’s persons', '법적 사람'],
    ['law\'s persons', '법적 사람'],
    ['constitutional personhood', '헌법적 인격성'],
    ['personified', '인격화된'],
    ['personification', '인격화'],
    ['personify', '인격화하다'],
    ['personhood', '인격성'],
    ['person', '사람·인격체'],
    ['humanity', '인간성'],
    ['moral responsibility', '도덕적 책임'],
    ['legal responsibility', '법적 책임'],
    ['responsibility practices', '책임 관행'],
    ['responsibility as relation', '관계로서의 책임'],
    ['role-responsibility', '역할책임'],
    ['role responsibility', '역할책임'],
    ['causal-responsibility', '인과책임'],
    ['causal responsibility', '인과책임'],
    ['liability-responsibility', '법적 책임'],
    ['liability responsibility', '법적 책임'],
    ['capacity-responsibility', '능력책임'],
    ['capacity responsibility', '능력책임'],
    ['prospective / retrospective responsibility', '사전적/사후적 책임'],
    ['prospective responsibility', '사전적 책임'],
    ['retrospective responsibility', '사후적 책임'],
    ['responsibility objection', '책임 반론'],
    ['judgment objection', '판단 반론'],
    ['responsibility', '책임'],
    ['moral agents', '도덕적 행위자'],
    ['moral agent', '도덕적 행위자'],
    ['moral entities', '도덕적 평가대상'],
    ['moral entity', '도덕적 평가대상'],
    ['moral action', '도덕적 행위'],
    ['moral status', '도덕적 지위'],
    ['bundle theory', '묶음 이론'],
    ['clustered/singularist personhood', '군집형/단일형 법인격'],
    ['cluster', '묶음'],
    ['passive/active incidents', '수동적/능동적 법적 지위 요소'],
    ['passive / active incidents', '수동적/능동적 법적 지위 요소'],
    ['fiction theory', '의제설'],
    ['real entity theory', '실재설'],
    ['practical concordance', '실제적 조화'],
    ['praktische Konkordanz', '실제적 조화'],
    ['ad hoc balancing', '사안별 형량'],
    ['status positivus libertatis', '자유의 적극적 지위'],
    ['status passivus', '수동적 지위'],
    ['status negativus', '소극적 지위'],
    ['status positivus', '적극적 지위'],
    ['status activus', '능동적 지위'],
    ['passive status', '수동적 지위'],
    ['negative status', '소극적 지위'],
    ['positive status', '적극적 지위'],
    ['active status', '능동적 지위'],
    ['corrective justice', '교정적 정의'],
    ['distributive justice', '분배적 정의'],
    ['justice as fairness', '공정으로서의 정의'],
    ['relational justice', '관계적 정의'],
    ['correlativity', '상관성'],
    ['correlatives', '상관관계'],
    ['opposites', '반대관계'],
    ['outcome responsibility', '결과책임'],
    ['fault responsibility', '과실책임'],
    ['causation / responsibility distinction', '인과관계/책임 구별'],
    ['strict liability', '무과실책임'],
    ['reciprocity of risk', '위험의 상호성'],
    ['nonreciprocal risks', '비상호적 위험'],
    ['nonreciprocal risk', '비상호적 위험'],
    ['wrongful loss', '부당한 손실'],
    ['private wrong', '사적 잘못'],
    ['private right', '사적 권리'],
    ['independence', '독립성'],
    ['wrong', '법적 잘못'],
    ['private law', '사법'],
    ['tort responsibility', '불법행위책임'],
    ['tort theory', '불법행위법 이론'],
    ['tort law', '불법행위법'],
    ['tort', '불법행위'],
    ['cheapest cost avoider', '최소비용 회피자'],
    ['cost of accidents', '사고비용'],
    ['risk distribution', '위험배분'],
    ['rights as trumps', '권리는 으뜸패'],
    ['rules and principles', '규칙과 원칙'],
    ['rules/principles', '규칙/원칙'],
    ['law as integrity', '통합성으로서의 법'],
    ['constructive interpretation', '구성적 해석'],
    ['integrity', '통합성'],
    ['rule of recognition', '승인의 규칙'],
    ['primary rules and secondary rules', '1차 규칙과 2차 규칙'],
    ['primary and secondary rules', '1차 규칙과 2차 규칙'],
    ['primary/secondary rules', '1차 규칙과 2차 규칙'],
    ['system of rights', '권리체계'],
    ['discourse principle', '담론원리'],
    ['democracy principle', '민주주의 원리'],
    ['democracy', '민주주의'],
    ['political liberalism', '정치적 자유주의'],
    ['optimization requirements', '최적화 명령'],
    ['principles as optimization requirements', '최적화 명령으로서의 원칙'],
    ['legal reasoning', '법적 논증'],
    ['deductive justification', '연역적 정당화'],
    ['second-order justification', '2차적 정당화'],
    ['coherence', '정합성'],
    ['consistency', '일관성'],
    ['consequentialist arguments', '결과주의적 논증'],
    ['consequences', '결과'],
    ['rule-based decision', '규칙기반 결정'],
    ['under- and over-inclusiveness', '과소·과잉포섭'],
    ['under/over-inclusiveness', '과소·과잉포섭'],
    ['under-inclusiveness', '과소포섭'],
    ['over-inclusiveness', '과잉포섭'],
    ['generalization', '일반화'],
    ['entrenchment of rules', '규칙의 고착성'],
    ['rule entrenchment', '규칙의 고착성'],
    ['reason-responsiveness', '이유반응성'],
    ['guidance control', '지도적 통제'],
    ['responsibility-loci', '책임의 위치'],
    ['human–robot collaborations', '인간-로봇 협업'],
    ['human–robot collaboration', '인간-로봇 협업'],
    ['human-robot collaborations', '인간-로봇 협업'],
    ['human-robot collaboration', '인간-로봇 협업'],
    ['human-in-the-loop', '인간개입형 구조'],
    ['tracking condition', '추적 조건'],
    ['tracing condition', '귀속추적 조건'],
    ['tracking', '추적 조건'],
    ['tracing', '귀속추적 조건'],
    ['level of abstraction', '추상화 수준'],
    ['levels of abstraction', '추상화 수준'],
    ['Interest Theory', '이익설'],
    ['interest theory of rights', '권리 이익설'],
    ['Will Theory', '의사설'],
    ['entitlement theory', '권원이론'],
    ['side constraints', '측면제약'],
    ['original position', '원초적 입장'],
    ['veil of ignorance', '무지의 베일'],
    ['difference principle', '차등원칙'],
    ['basic liberties', '기본적 자유'],
    ['two principles', '두 정의원칙'],
    ['minimal state', '최소국가'],
    ['service conception of authority', '권위의 서비스 구상'],
    ['normal justification thesis', '통상적 정당화 명제'],
    ['exclusionary reasons', '배제적 이유'],
    ['exclusionary reason', '배제적 이유'],
    ['basic goods', '기본적 선'],
    ['practical reasonableness', '실천적 합리성'],
    ['common good', '공동선'],
    ['legal discourse', '법적 담론'],
    ['special case', '특수사례'],
    ['private autonomy', '사적 자율'],
    ['public autonomy', '공적 자율'],
    ['proper purpose', '정당한 목적'],
    ['rational connection', '합리적 관련성'],
    ['less restrictive means', '덜 제한적인 수단'],
    ['proportionality stricto sensu', '협의의 비례성'],
    ['stricto sensu', '협의의'],
    ['proportionality', '비례성'],
    ['purposive interpretation', '목적론적 해석'],
    ['balancing', '형량'],
    ['Law of Balancing', '형량법칙'],
    ['Drittwirkung', '제3자효'],
    ['defensive rights', '방어권'],
    ['objective principles', '객관적 원칙'],
    ['horizontal effect', '제3자효'],
    ['state duty to protect', '국가의 보호의무'],
    ['state protection', '국가의 보호'],
    ['fundamental rights', '기본권'],
    ['Schutzpflicht', '국가의 기본권 보호의무'],
    ['Objektformel', '객체공식'],
    ['dingliche und persönliche Ansprüche', '물권적·인적 청구권'],
    ['Anspruch', '청구권'],
    ['claim-right', '청구권'],
    ['no-right', '무권리'],
    ['privilege', '자유'],
    ['immunity', '면제'],
    ['disability', '무권능'],
    ['incidents', '법적 지위 요소'],
    ['incident', '법적 지위 요소'],
    ['AI trustee thought experiment', 'AI 수탁자 사고실험'],
    ['trustee', '수탁자'],
    ['autonomous artificial agents', '자율형 인공 에이전트'],
    ['autonomous artificial agent', '자율형 인공 에이전트'],
    ['artificial agents', '인공적 행위자'],
    ['electronic agents', '전자적 에이전트'],
    ['electronic agent', '전자적 에이전트'],
    ['non-human actors', '비인간 행위자'],
    ['non-human actor', '비인간 행위자'],
    ['distributed morality', '분산된 도덕성'],
    ['distributed responsibility', '분산된 책임'],
    ['learning automata', '학습 자동기계'],
    ['control condition', '통제 조건'],
    ['legal lacuna', '법적 공백'],
    ['accountability gap critique', '책무성 공백 비판'],
    ['accountability gap', '책무성 공백'],
    ['human accountability', '인간의 책무성'],
    ['accountability architecture', '책무성 구조'],
    ['accountability', '책무성'],
    ['instrumental justification', '도구적 정당화'],
    ['rights and duties', '권리와 의무'],
    ['legal capacity', '법적 능력'],
    ['artificial intelligence', '인공지능'],
    ['Agentic AI', '에이전틱 AI'],
    ['law of robots', '로봇법'],
    ['tool / agent distinction', '도구/행위자 구별'],
    ['robot rights', '로봇 권리'],
    ['relational ethics', '관계적 윤리'],
    ['relational turn', '관계적 전환'],
    ['otherness', '타자성'],
    ['human intentionality', '인간 의도성'],
    ['sociotechnical systems', '사회기술적 시스템'],
    ['sociotechnical system', '사회기술적 시스템'],
    ['attribution', '귀속'],
    ['imputation', '귀속'],
    ['agency', '행위자성'],
    ['hard case', '난해사건'],
    ['congruence', '합치'],
    ['eight desiderata', '여덟 가지 요건'],
    ['eight ways to fail to make law', '법을 만들지 못하는 여덟 가지 방식'],
    ['Hart-Fuller debate', '하트-풀러 논쟁'],
    ['epieikeia', '형평'],
    ['human rights', '인권'],
    ['authority', '권위'],
    ['rights', '권리'],
    ['claim', '청구권'],
    ['power', '권능'],
    ['duty', '의무'],
    ['liability', '책임'],
    ['freedom', '자유'],
    ['contracts', '계약'],
    ['torts', '불법행위'],
    ['source of law', '법원'],
    ['legality', '합법성'],
    ['rights·principles', '권리·원칙'],
    ['collective goals', '집단적 목표'],
    ['innate right', '생득적 권리'],
    ['Restatement', '재진술'],
  ];

  const escapeRegex = value => value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const ordered = terms.slice().sort((a, b) => b[0].length - a[0].length);

  function localize(value) {
    let text = String(value ?? '');
    const replacements = [];

    ordered.forEach(([foreign, korean]) => {
      const pattern = new RegExp(`(^|[^A-Za-z])(${escapeRegex(foreign)})(?![A-Za-z]|\\s*\\()`, 'gi');
      text = text.replace(pattern, (full, prefix, match) => {
        const index = replacements.length;
        replacements.push(`${match} (${korean})`);
        return `${prefix}\uE000${index}\uE001`;
      });
    });

    replacements.forEach((replacement, index) => {
      text = text.replace(`\uE000${index}\uE001`, replacement);
    });
    return text;
  }

  window.LEGAL_PHILOSOPHY_TERMINOLOGY = {
    terms: Object.freeze(Object.fromEntries(terms)),
    localize
  };
})();
