(() => {
  'use strict';

  const terms = [
    ['meaningful human control', '의미 있는 인간 통제'],
    ['responsibility abundance', '책임의 다중·과잉 상태'],
    ['moral responsibility gap', '도덕적 책임공백'],
    ['civil liability gap', '민사책임 공백'],
    ['responsibility gap', '책임공백'],
    ['artificial moral agency', '인공적 도덕 행위자성'],
    ['moral agency', '도덕적 행위자성'],
    ['technical agency', '기술적 행위자성'],
    ['legal agency', '법적 행위자성'],
    ['AI agency', 'AI 행위자성'],
    ['legal personhood', '법인격'],
    ['AI legal personhood', 'AI 법인격'],
    ['AI personhood', 'AI 법인격'],
    ['synthetic personhood', '합성적 법인격'],
    ['synthetic persons', '합성적 법적 인격체'],
    ['functional personhood', '기능적 법인격'],
    ['legal personality', '법인격'],
    ['AI legal personality', 'AI 법인격'],
    ['juridical personality', '법적 인격'],
    ['corporate personality', '법인격'],
    ['legal person', '법적 인격체'],
    ['legal subject', '법적 주체'],
    ['person-thing distinction', '사람-사물 구별'],
    ['law’s persons', '법적 사람'],
    ["law's persons", '법적 사람'],
    ['personhood', '인격성'],
    ['person', '사람·인격체'],
    ['humanity', '인간성'],
    ['moral responsibility', '도덕적 책임'],
    ['legal responsibility', '법적 책임'],
    ['responsibility practices', '책임 관행'],
    ['responsibility', '책임'],
    ['moral agents', '도덕적 행위자'],
    ['moral agent', '도덕적 행위자'],
    ['moral entities', '도덕적 평가대상'],
    ['moral entity', '도덕적 평가대상'],
    ['moral action', '도덕적 행위'],
    ['moral status', '도덕적 지위'],
    ['bundle theory', '묶음 이론'],
    ['fiction theory', '의제설'],
    ['real entity theory', '실재설'],
    ['practical concordance', '실제적 조화'],
    ['praktische Konkordanz', '실제적 조화'],
    ['status positivus libertatis', '자유의 적극적 지위'],
    ['status passivus', '수동적 지위'],
    ['status negativus', '소극적 지위'],
    ['status positivus', '적극적 지위'],
    ['status activus', '능동적 지위'],
    ['passive status', '수동적 지위'],
    ['negative status', '소극적 지위'],
    ['positive status', '적극적 지위'],
    ['active status', '능동적 지위'],
    ['corrective justice', '교정적 정의'],
    ['distributive justice', '분배적 정의'],
    ['justice as fairness', '공정으로서의 정의'],
    ['relational justice', '관계적 정의'],
    ['correlativity', '상관성'],
    ['outcome responsibility', '결과책임'],
    ['role-responsibility', '역할책임'],
    ['role responsibility', '역할책임'],
    ['causal responsibility', '인과책임'],
    ['liability responsibility', '법적 책임'],
    ['capacity responsibility', '능력책임'],
    ['prospective responsibility', '사전적 책임'],
    ['retrospective responsibility', '사후적 책임'],
    ['strict liability', '무과실책임'],
    ['reciprocity of risk', '위험의 상호성'],
    ['nonreciprocal risks', '비상호적 위험'],
    ['nonreciprocal risk', '비상호적 위험'],
    ['wrongful loss', '위법한 손실'],
    ['private wrong', '사적 잘못'],
    ['wrong', '법적 잘못'],
    ['private law', '사법'],
    ['tort theory', '불법행위법 이론'],
    ['tort law', '불법행위법'],
    ['tort', '불법행위'],
    ['cheapest cost avoider', '최소비용 회피자'],
    ['cost of accidents', '사고비용'],
    ['risk distribution', '위험배분'],
    ['rights as trumps', '권리의 으뜸패성'],
    ['rules and principles', '규칙과 원칙'],
    ['law as integrity', '통합성으로서의 법'],
    ['constructive interpretation', '구성적 해석'],
    ['rule of recognition', '승인규칙'],
    ['primary/secondary rules', '1차·2차 규칙'],
    ['optimization requirements', '최적화 명령'],
    ['legal reasoning', '법적 논증'],
    ['coherence', '정합성'],
    ['consistency', '일관성'],
    ['consequentialist arguments', '결과주의적 논증'],
    ['rule-based decision', '규칙기반 결정'],
    ['under/over-inclusiveness', '과소·과잉포섭'],
    ['under-inclusiveness', '과소포섭'],
    ['over-inclusiveness', '과잉포섭'],
    ['generalization', '일반화'],
    ['reason-responsiveness', '이유반응성'],
    ['guidance control', '지도적 통제'],
    ['responsibility-loci', '책임의 위치'],
    ['human–robot collaborations', '인간-로봇 협업'],
    ['human-robot collaborations', '인간-로봇 협업'],
    ['human-robot collaboration', '인간-로봇 협업'],
    ['human-in-the-loop', '인간개입형 구조'],
    ['tracking condition', '추적 조건'],
    ['tracing condition', '귀속추적 조건'],
    ['tracking', '추적 조건'],
    ['tracing', '귀속추적 조건'],
    ['level of abstraction', '추상화 수준'],
    ['levels of abstraction', '추상화 수준'],
    ['Interest Theory', '이익설'],
    ['interest theory of rights', '권리 이익설'],
    ['Will Theory', '의사설'],
    ['entitlement theory', '권원이론'],
    ['side constraints', '측면제약'],
    ['original position', '원초적 입장'],
    ['veil of ignorance', '무지의 베일'],
    ['difference principle', '차등원칙'],
    ['basic liberties', '기본적 자유'],
    ['service conception of authority', '권위의 서비스 구상'],
    ['exclusionary reasons', '배제적 이유'],
    ['basic goods', '기본적 선'],
    ['practical reasonableness', '실천적 합리성'],
    ['common good', '공동선'],
    ['discourse principle', '담론원리'],
    ['democracy principle', '민주주의 원리'],
    ['private autonomy', '사적 자율'],
    ['public autonomy', '공적 자율'],
    ['proportionality stricto sensu', '협의의 비례성'],
    ['stricto sensu', '협의의'],
    ['proportionality', '비례성'],
    ['balancing', '형량'],
    ['Drittwirkung', '제3자효'],
    ['defensive rights', '방어권'],
    ['objective principles', '객관적 원칙'],
    ['horizontal effect', '제3자효'],
    ['state duty to protect', '국가의 보호의무'],
    ['state protection', '국가의 보호'],
    ['personification', '인격화'],
    ['personify', '인격화하다'],
    ['Schutzpflicht', '국가의 기본권 보호의무'],
    ['Objektformel', '객체공식'],
    ['dingliche und persönliche Ansprüche', '물권적·인적 청구권'],
    ['Anspruch', '청구권'],
    ['claim-right', '청구권'],
    ['no-right', '무권리'],
    ['privilege', '특권·자유'],
    ['immunity', '면책·면제'],
    ['disability', '무권능'],
    ['incidents', '법적 지위 요소'],
    ['incident', '법적 지위 요소'],
    ['autonomous artificial agents', '자율형 인공 에이전트'],
    ['artificial agents', '인공적 행위자'],
    ['electronic agents', '전자적 에이전트'],
    ['non-human actors', '비인간 행위자'],
    ['distributed morality', '분산된 도덕성'],
    ['distributed responsibility', '분산된 책임'],
    ['learning automata', '학습 자동기계'],
    ['legal lacuna', '법적 공백'],
    ['accountability gap', '책임 공백'],
    ['human accountability', '인간의 책무성'],
    ['accountability', '책무성'],
    ['instrumental justification', '도구적 정당화'],
    ['rights and duties', '권리와 의무'],
    ['legal capacity', '법적 능력'],
    ['artificial intelligence', '인공지능'],
    ['Agentic AI', '에이전틱 AI'],
    ['law of robots', '로봇법'],
    ['robot rights', '로봇 권리'],
    ['relational ethics', '관계적 윤리'],
    ['otherness', '타자성'],
    ['human intentionality', '인간 의도성'],
    ['sociotechnical systems', '사회기술적 시스템'],
    ['attribution', '귀속'],
    ['agency', '행위자성'],
    ['hard case', '난해사건'],
    ['claim', '청구권'],
    ['power', '권능'],
    ['duty', '의무'],
    ['liability', '책임'],
    ['freedom', '자유'],
    ['contracts', '계약'],
    ['torts', '불법행위']
  ];

  const escapeRegex = value => value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const ordered = terms.slice().sort((a, b) => b[0].length - a[0].length);

  function localize(value) {
    let text = String(value ?? '');
    const replacements = [];

    ordered.forEach(([foreign, korean]) => {
      const pattern = new RegExp(`(^|[^A-Za-z])(${escapeRegex(foreign)})(?![A-Za-z]|\\s*\\()`, 'gi');
      text = text.replace(pattern, (full, prefix, match) => {
        const index = replacements.length;
        replacements.push(`${match} (${korean})`);
        return `${prefix}\uE000${index}\uE001`;
      });
    });

    replacements.forEach((replacement, index) => {
      text = text.replace(`\uE000${index}\uE001`, replacement);
    });
    return text;
  }

  window.LEGAL_PHILOSOPHY_TERMINOLOGY = {
    terms: Object.freeze(Object.fromEntries(terms)),
    localize
  };
})();