window.AI_LITERATURE_RECORDS = [
  {
    id:"book-ai-principles-2021", type:"필수도서", priority:"A", stage:"기초", jurisdiction:"대한민국", language:"한국어",
    title:"인공지능 원론: 설명가능성을 중심으로", translatedTitle:"", author:"고학수·김용대·윤성로·김정훈·이선구·박도현·김시원", year:2021, publication:"박영사",
    citation:"고학수 외, 『인공지능 원론: 설명가능성을 중심으로』, 박영사, 2021.", legalAreas:["법철학·규제이론","헌법·공법","데이터·개인정보"], issues:["설명가능성","불투명성","AI 기술전제","신뢰성"],
    summary:"인공지능의 작동 구조와 설명가능성 문제를 기술·법·의료 등 여러 관점에서 연결한다. 법적 책임 논의를 시작하기 전에 ‘왜 결과를 설명하기 어려운가’를 기술적으로 이해하는 기초문헌이다.",
    mustRead:["설명가능성과 투명성의 차이","모델의 기술적 한계와 법적 설명의 요구가 동일하지 않다는 점","불투명성을 곧바로 무책임의 근거로 연결하지 않는 분석"],
    argumentUse:["AI 책임론의 기술적 전제 정리","설명의무·로그·감사 가능성을 설계할 때 기술적 한계 제시","블랙박스라는 수사 대신 구체적 불투명성 유형을 구분"],
    researchFit:"행위효과와 책임귀속을 분리한 뒤, 책임규범이 요구하는 설명·검증 가능성의 최소조건을 설정하는 부분에 접목한다.", counterpoint:"설명가능성은 책임귀속의 필요조건일 수 있으나 충분조건은 아니다. 규범적 책임근거는 별도로 제시해야 한다.", related:["article-trustworthy-ai-2022","article-kroll-accountable-2017","norm-nist-ai-rmf"], url:"https://www.yes24.com/product/goods/102821434", access:"도서·서지"
  },
  {
    id:"book-privacy-ai-2022", type:"전공서적", priority:"A", stage:"교리", jurisdiction:"대한민국", language:"한국어", title:"인공지능 시대의 개인정보 보호법", translatedTitle:"", author:"고학수·김병필·구본효·백대열·박도현·정종구·김은수", year:2022, publication:"박영사",
    citation:"고학수 외, 『인공지능 시대의 개인정보 보호법』, 박영사, 2022.", legalAreas:["데이터·개인정보","헌법·공법"], issues:["개인정보","가명정보","자동화된 의사결정","데이터 거버넌스"],
    summary:"데이터3법 이후 개인정보 보호법제를 인공지능 기술의 데이터 처리 구조와 함께 설명한다. AI의 학습·추론·자동화 의사결정에서 개인정보 규율이 어디에 개입하는지 파악하는 전공 기초다.", mustRead:["개인정보 개념과 처리 단계","가명정보·데이터 결합","자동화된 의사결정과 정보주체 보호"], argumentUse:["AI 시스템의 데이터 입력단계 의무를 책임사슬에 포함","학습데이터 결함과 개인정보 침해를 구별","개인정보 자기결정권과 설명·거부권 논증의 국내법 기반"], researchFit:"다중 AI 에이전트의 책임을 모델 작동 이후만이 아니라 데이터 수집·공급·전처리 단계까지 계층적으로 배분하는 근거로 활용한다.", counterpoint:"개인정보 보호의무와 민사상 손해배상책임은 요건과 목적이 다르므로 동일시하지 않는다.", related:["thesis-kang-hyekyung-2024","article-wachter-explanation-2017","article-kaminski-explanation-2019"], url:"https://www.yes24.com/product/goods/109728693", access:"도서·서지"
  },
  {
    id:"book-eu-ai-act-2024", type:"전공서적", priority:"A", stage:"비교법", jurisdiction:"대한민국·EU", language:"한국어", title:"EU 인공지능법", translatedTitle:"EU AI Act", author:"강혜경·함인선", year:2024, publication:"마로니에", citation:"강혜경·함인선, 『EU 인공지능법(EU AI Act)』, 마로니에, 2024.", legalAreas:["헌법·공법","데이터·개인정보","비교법·국제"], issues:["EU AI Act","위험기반 규제","GPAI","GDPR","규제샌드박스"], summary:"EU 인공지능법의 위험기반 규제구조, 범용 AI, 표준·적합성평가, 규제샌드박스와 GDPR의 관계를 체계적으로 해설한다.", mustRead:["위험등급과 규제강도의 연결","공급자·배포자 등 행위자별 의무","AI Act와 GDPR의 규범 중첩"], argumentUse:["계층적 책임주체를 규제상 행위자 구조와 비교","기능적 단위 규율의 등록·기록·감독 장치를 설계","한국 AI기본법과 EU 규율의 차이 확인"], researchFit:"개발자·공급자·배포자·운영자별 의무를 민사상 책임귀속 층위와 비교하여, 규제의무와 손해배상책임을 연결하되 구별하는 부분에 접목한다.", counterpoint:"EU의 위험기반 행정규제가 곧바로 한국 민사책임의 귀책근거가 되는 것은 아니다.", related:["thesis-kang-hyekyung-2024","norm-eu-ai-act","norm-korea-ai-basic"], url:"https://www.yes24.com/Product/Goods/136879157", access:"도서·서지"
  },
  {
    id:"book-ax-law-2026", type:"전공서적", priority:"B", stage:"쟁점", jurisdiction:"대한민국", language:"한국어", title:"인공지능 대전환(AX)과 법", translatedTitle:"", author:"이성엽", year:2026, publication:"박영사", citation:"이성엽, 『인공지능 대전환(AX)과 법』, 박영사, 2026.", legalAreas:["법철학·규제이론","헌법·공법","민사·책임법","데이터·개인정보","지식재산"], issues:["AI 전환","혁신과 기본권","국가규제","산업법"], summary:"AI 전환이 여러 법영역에 미치는 영향을 폭넓게 다루는 최신 국내 단행본이다. 세부 교리보다 현재 한국의 AI 법제 지형을 빠르게 파악하는 데 적합하다.", mustRead:["혁신촉진과 권리보호의 긴장","국가 개입의 정당화","분야별 AI 법제의 접점"], argumentUse:["박사논문 서론의 법정책 배경","분야별 규율의 파편화 문제 제시","AI 전환에 따른 법체계 재구성 필요성 설명"], researchFit:"기능적 단위 법적 지위를 단일 특수법의 문제가 아니라 민사·공법·데이터 규율이 만나는 구조문제로 위치시키는 서론에 활용한다.", counterpoint:"폭넓은 개론서는 개별 책임요건이나 직접 인용의 근거로는 원전·전문논문을 추가 확인해야 한다.", related:["norm-korea-ai-basic","book-chesterman-2021"], url:"https://www.pybook.co.kr/mall/book/field?category=06&goodsno=9403", access:"출판사"
  },
  {
    id:"book-ai-risk-2025", type:"필수도서", priority:"B", stage:"기초", jurisdiction:"대한민국", language:"한국어", title:"AI 위험과 인간의 대응", translatedTitle:"", author:"박도현", year:2025, publication:"커뮤니케이션북스", citation:"박도현, 『AI 위험과 인간의 대응』, 커뮤니케이션북스, 2025.", legalAreas:["법철학·규제이론","헌법·공법"], issues:["AI 위험","규제 거버넌스","해악","인간 통제"], summary:"AI 규제의 역사적 흐름과 위험 대응 방식을 핵심 키워드 중심으로 정리한다. 창발적 해악론을 박사학위논문보다 압축적으로 재확인하는 입문 경로로 사용할 수 있다.", mustRead:["기술유형에 따른 위험 차이","규제와 윤리 거버넌스의 역할","법인격 논의가 등장하는 조건"], argumentUse:["창발적 손해의 문제의식 정리","위험유형에 따라 규율수단을 달리해야 한다는 근거","경성규범과 연성규범의 조합 검토"], researchFit:"창발적 손해를 책임규칙 하나로 해결하기보다 위험관리·사후책임·조직통제를 결합해야 한다는 연구구조의 도입부에 접목한다.", counterpoint:"대중적 압축서이므로 핵심 명제의 학술적 직접근거는 원 박사논문과 후속 논문으로 보강한다.", related:["thesis-park-emergent-2021","article-park-bias-2022","article-trustworthy-ai-2022"], url:"https://play.google.com/store/books/details?id=xDc5EQAAQBAJ", access:"도서·서지"
  },
  {
    id:"thesis-park-emergent-2021", type:"국내 박사학위논문", priority:"A", stage:"쟁점", jurisdiction:"대한민국", language:"한국어", title:"인공지능과 해악: 창발적 해악론을 중심으로", translatedTitle:"Artificial Intelligence and Harm: Focusing on Emergent Harm", author:"박도현", year:2021, publication:"서울대학교 법학박사", citation:"박도현, 「인공지능과 해악: 창발적 해악론을 중심으로」, 서울대학교 법학박사학위논문, 2021.", legalAreas:["법철학·규제이론","민사·책임법"], issues:["창발적 해악","딥러닝","인과구조","법인격","거버넌스"], summary:"규칙기반 AI, 딥러닝 AI, 강·초인공지능을 구분하면서 특히 인간지능과 인공지능의 상호작용에서 발생하는 창발적 해악을 독립된 규범문제로 다룬다.", mustRead:["창발적 해악의 정의와 발생기제","딥러닝 위험을 인간의 단일 의지행위로 환원하기 어려운 이유","기술유형별 법적 대응의 차등화"], argumentUse:["창발적 손해의 개념틀 설정","다수 행위자·복잡계에서 인과와 귀책이 분산되는 문제 제시","기능적 법인격 논의를 경쟁적 제도대안으로 비교"], researchFit:"현재 박사연구의 ‘창발적 손해’ 장에서 출발점이 되는 국내 핵심 선행연구다. 이후 민법상 귀책·증명위험·계층적 책임귀속으로 논의를 전환한다.", counterpoint:"창발성을 이유로 기존 책임법을 곧바로 폐기하지 말고, 기존 교리의 미세조정이 가능한 영역과 새로운 제도가 필요한 영역을 분리해야 한다.", related:["article-balkin-2015","article-calo-2015","thesis-lee-tort-2021","article-bryson-persons-2017"], url:"https://www.kalp.kr/post/2021-9-25-%EB%B0%95%EB%8F%84%ED%98%84_%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5%EA%B3%BC-%ED%95%B4%EC%95%85", access:"학술발표·서지 확인"
  },
  {
    id:"thesis-lee-tort-2021", type:"국내 박사학위논문", priority:"A", stage:"교리", jurisdiction:"대한민국", language:"한국어", title:"인공지능과 불법행위책임에 관한 연구", translatedTitle:"", author:"이해원", year:2021, publication:"연세대학교 법학전문대학원 박사학위논문", citation:"이해원, 「인공지능과 불법행위책임에 관한 연구」, 연세대학교 법학전문대학원 박사학위논문, 2021.", legalAreas:["민사·책임법","법철학·규제이론"], issues:["불법행위","위험책임","제조물책임","법인격","보험","증명곤란"], summary:"AI 사고에서 누가 어떤 근거로 민사책임을 부담하는지를 체계적으로 검토하고, 고위험 AI에는 위험책임, 그 밖의 영역에는 제조물책임 보완 등 위험기반의 책임구조를 제안한다.", mustRead:["AI 법인격 부정 논거","고위험 AI와 일반 AI의 책임구조 차등","공급자·제조자·이용자 사이 책임배분과 피해자 입증곤란"], argumentUse:["기존 민법·제조물책임법으로 가능한 범위 확정","기능적 단위 법적 지위 주장에 대한 국내 반대논거 확보","보험·증명부담 완화가 법인격의 대체수단인지 검토"], researchFit:"기능적 단위 법적 지위를 주장하기 전에 ‘기존 책임법 보완으로 충분하다’는 가장 강한 대안을 검토하는 반론 장에 배치한다.", counterpoint:"법인격을 부정하더라도 복수 에이전트가 독립적으로 상호작용하는 구조에서 책임재산·소송상 지위·기록의 독립 단위가 필요한지는 별도 문제다.", related:["article-jeong-civil-2018","article-kim-error-2022","article-lee-soeun-seo-2026","article-bryson-persons-2017"], url:"https://www.dbpia.co.kr/journal/detail?nodeId=T15875745", access:"학위논문 서지"
  },
  {
    id:"thesis-kang-hyekyung-2024", type:"국내 박사학위논문", priority:"A", stage:"비교법", jurisdiction:"대한민국·EU", language:"한국어", title:"EU 인공지능법에 대한 연구: 인공지능 규율과 개인정보 보호의 관계를 중심으로", translatedTitle:"", author:"강혜경", year:2024, publication:"전남대학교 법학박사학위논문", citation:"강혜경, 「EU 인공지능법에 대한 연구: 인공지능 규율과 개인정보 보호의 관계를 중심으로」, 전남대학교 법학박사학위논문, 2024.", legalAreas:["헌법·공법","데이터·개인정보","비교법·국제"], issues:["EU AI Act","GDPR","규범중첩","차별","개인정보"], summary:"EU AI Act와 GDPR이 AI 규율에서 어떻게 겹치고 분업하는지 분석한다. 개인정보, 차별, 허위정보 등 권리침해 문제를 위험기반 규제와 연결한다.", mustRead:["AI Act와 GDPR의 적용관계","권리보호와 위험기반 규제의 결합","한국법에 대한 비교법적 시사점"], argumentUse:["규제법상 행위자의무와 사법상 책임의 구별","개인정보 위험이 책임사슬의 어느 단계에 위치하는지 분석","국내 AI기본법 해석의 비교법 근거"], researchFit:"기능적 단위를 설계할 때 개인정보·기본권 관련 의무가 단위 자체와 배후 운영자에게 어떻게 병존하는지 검토하는 비교법 장에 접목한다.", counterpoint:"EU 제도의 기관·시장·기본권 구조가 한국과 다르므로 규정의 직접 이식보다 기능 비교가 필요하다.", related:["book-eu-ai-act-2024","article-wachter-explanation-2017","article-kaminski-explanation-2019","norm-eu-ai-act"], url:"https://www.dbpia.co.kr/journal/detail?nodeId=T17076123", access:"학위논문 서지"
  },
  {
    id:"thesis-kang-civil-procedure-2024", type:"국내 박사학위논문", priority:"B", stage:"교리", jurisdiction:"대한민국", language:"한국어", title:"인공지능과 민사소송: 사법 접근성 향상을 위한 인공지능 활용 가능성에 관한 연구", translatedTitle:"AI and Civil Procedure: A Study on the Possibility of Using Artificial Intelligence to Improve Access to Justice", author:"강영주", year:2024, publication:"고려대학교 법학박사학위논문", citation:"강영주, 「인공지능과 민사소송: 사법 접근성 향상을 위한 인공지능 활용 가능성에 관한 연구」, 고려대학교 법학박사학위논문, 2024.", legalAreas:["민사·책임법","헌법·공법","법적 추론"], issues:["민사소송","사법접근성","ODR","리걸테크","재판예측","편향","법치주의"], summary:"AI를 민사분쟁 해결과 재판절차에 활용할 가능성을 사법 접근성, ODR, 법률챗봇, 재판예측, 판결문 데이터, 편향·불투명성 문제와 함께 검토한다.", mustRead:["사법 접근성과 효율성의 긴장","AI 법률서비스·ODR의 절차적 한계","판결문 데이터와 재판예측의 규범 문제"], argumentUse:["AI가 소송주체가 될 수 있는지와 별개로 소송도구로 사용될 때의 통제논리 확보","기능적 단위에 제한적 소송상 지위를 부여하는 경우 기존 민사소송 원칙과 충돌 검토","로그·증거접근 구조의 절차법적 의미"], researchFit:"기능적 단위의 제한적 피소송능력 또는 증거제출·로그보존 구조를 설계할 때 민사소송법적 검증 기준으로 활용한다.", counterpoint:"사법 접근성을 높이는 AI 활용 논의와 AI 자체의 소송상 지위 문제는 구별해야 한다.", related:["article-citron-2008","article-kroll-accountable-2017"], url:"https://dcollection.korea.ac.kr/srch/srchDetail/000000280489", access:"학위논문 원문·서지"
  },
  {
    id:"thesis-kim-automated-admin-2024", type:"국내 박사학위논문", priority:"A", stage:"교리", jurisdiction:"대한민국", language:"한국어", title:"인공지능을 활용한 자동적 처분에 관한 공법적 연구", translatedTitle:"Public Law Research on Automatic Administrative Agency Action Using Artificial Intelligence", author:"김휘식", year:2024, publication:"고려대학교 법학박사학위논문", citation:"김휘식, 「인공지능을 활용한 자동적 처분에 관한 공법적 연구」, 고려대학교 법학박사학위논문, 2024.", legalAreas:["헌법·공법","데이터·개인정보"], issues:["자동적 처분","행정절차","설명요구권","행정소송","국가배상","알고리즘"], summary:"행정기본법상 자동적 처분을 중심으로 허용범위, 사전통지·의견청취·이유제시, 설명요구권, 알고리즘 검증, 행정소송과 국가배상을 통합적으로 분석한다.", mustRead:["자동적 처분의 행정청 귀속 논리","알고리즘 공개와 설명의무의 구별","공무원 과실 입증부담과 국가배상법 제2조·제5조의 관계"], argumentUse:["AI 작동결과를 인간·기관에 규범적으로 귀속하는 공법 모델","설명·검증·권리구제 절차를 사전·사후 통제로 나누는 근거","공적 영역에서 AI 시스템을 독립주체로 보지 않는 강한 반대사례"], researchFit:"AI의 비규범적 작동을 법적 주체의 행위로 변환하는 ‘귀속규칙’의 비교모델로 사용하고, 민사영역의 기능적 단위론과 차이를 설명한다.", counterpoint:"행정청이라는 선행 공권력 주체가 존재하는 구조는 민간 다중에이전트 시스템과 동일하지 않다.", related:["article-citron-2008","article-wachter-explanation-2017","norm-korea-ai-basic"], url:"https://dcollection.korea.ac.kr/srch/srchDetail/000000280122", access:"학위논문 원문·서지"
  },
  {
    id:"article-jeong-civil-2018", type:"국내 학술논문", priority:"A", stage:"교리", jurisdiction:"대한민국", language:"한국어", title:"인공지능에 대한 민사책임 법리", translatedTitle:"", author:"정진명", year:2018, publication:"재산법연구 34(4), 137-168", citation:"정진명, 「인공지능에 대한 민사책임 법리」, 『재산법연구』 34(4), 2018, 137-168.", legalAreas:["민사·책임법"], issues:["민사책임","법률행위","통제","과실","자율성"], summary:"자율적 AI가 법률행위와 손해를 발생시키는 경우 전통적 통제·의사 중심의 민사책임 법리가 어떤 한계를 갖는지 검토한다.", mustRead:["AI 작동과 인간 의사 사이의 거리","책임귀속의 전통적 전제","현행 민사법리의 재구성 가능성"], argumentUse:["기존 민사책임 교리의 출발점","AI 자율성 때문에 책임 공백이 발생한다는 주장 검토","사용자·제조자 책임을 기능별로 분리"], researchFit:"계층적 책임귀속론에서 기존 민법이 각 층위에 제공하는 기본 요건을 확정하는 데 사용한다.", counterpoint:"AI의 자율성을 과장하여 인간 통제 가능성을 성급히 부정하지 않는다.", related:["thesis-lee-tort-2021","article-kim-error-2022"], url:"https://doi.org/10.35142/prolaw.34.4.201802.005", access:"DOI"
  },
  {
    id:"article-shin-personhood-2018", type:"국내 학술논문", priority:"A", stage:"쟁점", jurisdiction:"대한민국", language:"한국어", title:"인공지능(AI)의 법인격 – 전자인격(Electronic Person) 개념에 관한 소고", translatedTitle:"", author:"신현탁", year:2018, publication:"인권과 정의 478, 45-64", citation:"신현탁, 「인공지능(AI)의 법인격 – 전자인격(Electronic Person) 개념에 관한 소고」, 『인권과 정의』 478, 2018, 45-64.", legalAreas:["법철학·규제이론","민사·책임법","상법·회사법"], issues:["전자법인격","법인격","권리능력","책임재산"], summary:"AI에 전자인격을 인정할 수 있는지 법인격의 기능과 사회적 필요를 중심으로 검토하는 국내 초기 핵심 논문이다.", mustRead:["법인격을 자연적 실체가 아닌 법기술로 보는 관점","전자인격의 제한적 인정 가능성","권리·의무 범위를 기능에 맞춰 제한하는 문제"], argumentUse:["기능적 단위 법적 지위의 국내 선행논의 위치 확인","전면적 인간유사 인격과 제한적 기능인격을 구별","법인격의 도구적·제도적 기능 논증"], researchFit:"기능적 단위에 필요한 incidents만 부여한다는 논증의 선행연구로 사용하되, 전자인격 개념과 현재 제안의 차이를 명시한다.", counterpoint:"법인격 부여가 책임회피 장치가 될 수 있다는 해외 반대론을 반드시 함께 검토한다.", related:["article-bryson-persons-2017","book-abbott-2020","thesis-lee-tort-2021"], url:"https://doi.org/10.22999/hraj..478.201812.004", access:"DOI"
  },
  {
    id:"article-kim-error-2022", type:"국내 학술논문", priority:"A", stage:"교리", jurisdiction:"대한민국", language:"한국어", title:"인공지능 오류사고 민사책임에 대한 입법론적 검토", translatedTitle:"", author:"김진아", year:2022, publication:"재산법연구 39(2), 273-308", citation:"김진아, 「인공지능 오류사고 민사책임에 대한 입법론적 검토」, 『재산법연구』 39(2), 2022, 273-308.", legalAreas:["민사·책임법"], issues:["오류사고","제조물책임","소프트웨어","법인격","특별법"], summary:"AI 오류사고의 책임을 별도 AI 법인격, 특별책임법, 제조물책임법의 소프트웨어 포섭 등 여러 입법대안으로 비교한다.", mustRead:["소프트웨어의 제조물 해당성 논의","특별법과 일반법의 역할배분","법인격과 책임재산의 관계"], argumentUse:["기능적 단위 법적 지위가 왜 또는 왜 아닌지 대안 비교","제조물책임 확장안과 차별점 제시","입법수단 선택의 비용·편익 비교"], researchFit:"기능적 단위론을 제시하기 전 제조물책임법 개정과 특별법 모델이 해결할 수 있는 범위를 선행 검토하는 데 활용한다.", counterpoint:"법적 지위 부여가 피해자 보호를 실제로 강화하는지 책임재산·보험과 함께 검증해야 한다.", related:["thesis-lee-tort-2021","article-shin-personhood-2018"], url:"https://doi.org/10.35142/prolaw.39.2.202208.010", access:"DOI"
  },
  {
    id:"article-lee-soeun-seo-2026", type:"국내 학술논문", priority:"A", stage:"쟁점", jurisdiction:"대한민국", language:"한국어", title:"인공지능 관련 사고와 민사책임 - 불법행위책임을 중심으로 -", translatedTitle:"", author:"이소은·서종희", year:2026, publication:"소비자법연구 12(1), 97-129", citation:"이소은·서종희, 「인공지능 관련 사고와 민사책임 - 불법행위책임을 중심으로 -」, 『소비자법연구』 12(1), 2026, 97-129.", legalAreas:["민사·책임법","소비자·플랫폼"], issues:["불법행위","고위험 AI","과실책임","증명부담","보험","보상기금"], summary:"AI기본법 시행 이후의 환경을 전제로 고위험 AI와 일반 AI의 책임기준을 달리하고, 다수 관여자 책임배분·입증부담 완화·보험 및 보상기금까지 검토하는 최신 민사책임 논문이다.", mustRead:["고위험 AI의 엄격책임 가능성","일반 AI의 과실책임 유지 논리","피해자 증명부담과 보험·기금"], argumentUse:["2026년 국내 민사책임 논의의 최신 기준점","기능적 단위 책임재산·보험 설계와 비교","위험등급과 책임강도를 연동하는 논거"], researchFit:"기능적 단위의 보험·공탁·책임재산을 기존 인간 책임의 대체가 아니라 피해자 구제의 보충층으로 설계하는 부분에 접목한다.", counterpoint:"엄격책임의 적용대상과 위험개념을 AI기본법의 규제분류와 기계적으로 동일시하지 않는다.", related:["norm-korea-ai-basic","thesis-lee-tort-2021","article-scherer-2016"], url:"https://doi.org/10.22820/jcl.12.1.202602.97", access:"DOI"
  },
  {
    id:"article-training-data-liability-2025", type:"국내 학술논문", priority:"A", stage:"쟁점", jurisdiction:"대한민국·EU", language:"한국어", title:"인공지능 학습데이터의 법적 책임과 규제 패러다임 - EU 입법 동향과 민사책임론적 함의를 중심으로 -", translatedTitle:"", author:"이종덕", year:2025, publication:"재산법연구 42(3), 147-178", citation:"이종덕, 「인공지능 학습데이터의 법적 책임과 규제 패러다임」, 『재산법연구』 42(3), 2025, 147-178.", legalAreas:["민사·책임법","데이터·개인정보","비교법·국제"], issues:["학습데이터","편향","결함","인과관계","증명책임","공급자"], summary:"잘못되거나 편향된 학습데이터가 손해에 기여한 경우 데이터 공급자·개발자·이용자 사이의 법적 책임과 인과관계·증명문제를 EU 동향과 함께 분석한다.", mustRead:["데이터 결함과 모델 결함의 구별","공급망형 책임배분","인과관계와 피해자 증명곤란"], argumentUse:["다중에이전트 책임사슬을 데이터 공급망까지 확장","원인기여도와 통제가능성에 따른 계층 귀속","로그·출처추적 의무의 필요성"], researchFit:"설계·통합·배치·운용뿐 아니라 데이터 공급층을 별도 책임층으로 둘지 검토하는 데 직접 접목한다.", counterpoint:"데이터 편향이 결과 손해에 기여했다는 사실은 개별 사건에서 별도의 인과관계 증명이 필요하다.", related:["article-barocas-selbst-2016","book-privacy-ai-2022"], url:"https://doi.org/10.35142/prolaw.42.3.202511.006", access:"DOI"
  },
  {
    id:"article-choi-company-2020", type:"국내 학술논문", priority:"A", stage:"교리", jurisdiction:"대한민국", language:"한국어", title:"인공지능(Artificial Intelligence)과 회사법의 접점 - 인공지능의 활용에 수반되는 회사법적 논점 -", translatedTitle:"", author:"최문희", year:2020, publication:"상사법연구 39(1), 1-53", citation:"최문희, 「인공지능과 회사법의 접점」, 『상사법연구』 39(1), 2020, 1-53.", legalAreas:["상법·회사법"], issues:["이사회","이사의무","기업의 AI 활용","의사결정"], summary:"회사가 AI를 의사결정·업무에 활용할 때 이사회와 이사의 법적 의무, 회사법상 책임구조가 어떻게 변하는지 검토하는 국내 핵심 회사법 논문이다.", mustRead:["AI를 이용한 이사의 의사결정","감독·정보수집 의무","AI 사용이 회사기관 구조에 미치는 영향"], argumentUse:["법인 내부의 AI와 독립 기능단위 AI를 구별","배치·운용층의 이사 책임 근거","기업 내부통제와 기술통제의 연결"], researchFit:"다중에이전트 시스템을 기업이 배치한 경우 통합자·운영회사·이사의 책임층을 구분하는 회사법 파트에 접목한다.", counterpoint:"AI가 회사의 기관을 대체한다는 주장과 이사가 AI를 도구로 활용한다는 현행법 모델을 구별한다.", related:["article-namgung-director-2024","norm-nist-ai-rmf"], url:"https://doi.org/10.21188/CLR.39.1.1", access:"DOI"
  },
  {
    id:"article-namgung-director-2024", type:"국내 학술논문", priority:"A", stage:"교리", jurisdiction:"대한민국", language:"한국어", title:"인공지능(AI)과 회사법의 연결에 관한 소고 - 이사의 책임 부담 가능성을 중심으로 -", translatedTitle:"", author:"남궁주현", year:2024, publication:"성균관법학 36(4), 41-69", citation:"남궁주현, 「인공지능(AI)과 회사법의 연결에 관한 소고 - 이사의 책임 부담 가능성을 중심으로 -」, 『성균관법학』 36(4), 2024, 41-69.", legalAreas:["상법·회사법"], issues:["이사책임","경영판단","정보수집","AI 사용·불사용"], summary:"AI의 사용 또는 불사용이 이사의 주의의무와 책임 판단에 어떤 영향을 미칠 수 있는지 정보수집·경영판단의 관점에서 검토한다.", mustRead:["AI 사용 자체가 면책이 되지 않는 이유","합리적 정보수집과 AI 의존","AI를 사용하지 않은 경우의 책임 가능성"], argumentUse:["운용자의 감독의무 구체화","인간 최종결정자 원칙의 한계 검토","다중에이전트 배치기업의 내부통제 기준"], researchFit:"운용층 책임을 단순한 ‘human-in-the-loop’ 여부가 아니라 합리적 감독·정보수집·통제설계로 구체화하는 데 활용한다.", counterpoint:"이사의 회사법상 의무와 피해자에 대한 직접 불법행위책임은 구별한다.", related:["article-choi-company-2020","book-chesterman-2021"], url:"https://doi.org/10.17008/skklr.2024.36.4.002", access:"DOI"
  },
  {
    id:"article-trustworthy-ai-2022", type:"국내 학술논문", priority:"A", stage:"기초", jurisdiction:"대한민국", language:"한국어", title:"신뢰할 수 있는 인공지능의 이론적 고찰", translatedTitle:"A Theoretical Study on Trustworthy Artificial Intelligence", author:"박도현", year:2022, publication:"법철학연구 25(2), 321-364", citation:"박도현, 「신뢰할 수 있는 인공지능의 이론적 고찰」, 『법철학연구』 25(2), 2022, 321-364.", legalAreas:["법철학·규제이론","헌법·공법"], issues:["신뢰성","거버넌스","공정성","투명성","책임성"], summary:"신뢰할 수 있는 AI를 구성하는 여러 하위원칙을 하나의 이론적 틀에서 정리하고, 실무적 체크리스트를 넘어 거버넌스의 정당화 구조를 검토한다.", mustRead:["신뢰성의 구성요소와 상호관계","윤리원칙과 법규범의 관계","신뢰 개념의 규범적 한계"], argumentUse:["로그·감사·설명가능성·인간감독을 제도요소로 묶는 상위 근거","책임주체 논의와 시스템 신뢰성 논의를 구별","규범 설계의 중간원칙 마련"], researchFit:"기능적 단위 등록·로그·책임관리인·보험 등 incidents가 어떤 신뢰성 목표를 달성하는지 정당화하는 부분에 접목한다.", counterpoint:"신뢰성은 가치목표이지 그 자체로 손해배상책임의 법적 요건은 아니다.", related:["norm-nist-ai-rmf","book-ai-principles-2021"], url:"https://www.kci.go.kr/kciportal/landing/article.kci?arti_id=ART002877025", access:"KCI"
  },
  {
    id:"article-park-bias-2022", type:"국내 학술논문", priority:"B", stage:"쟁점", jurisdiction:"대한민국", language:"한국어", title:"인간 편향성과 인공지능의 교차", translatedTitle:"", author:"박도현", year:2022, publication:"서울대학교 법학 63(1), 139-175", citation:"박도현, 「인간 편향성과 인공지능의 교차」, 『서울대학교 법학』 63(1), 2022, 139-175.", legalAreas:["법철학·규제이론","헌법·공법"], issues:["편향","차별","창발적 해악","규제거버넌스"], summary:"AI가 인간 편향을 단순 반영한다는 설명을 넘어서 편향의 확대·변형과 규제 필요성을 해악의 총량과 거버넌스 관점에서 재검토한다.", mustRead:["인간 편향과 AI 편향의 인과관계","확대재생산의 규범적 의미","새 규제의 정당화 조건"], argumentUse:["창발적 손해의 구체 사례","AI 위험을 인간 원인 하나로 환원하는 논리 비판","차별 위험과 책임귀속을 분리"], researchFit:"다중 에이전트 상호작용이 기존 인간 편향을 증폭·변형하는 경우를 창발적 손해의 사례유형으로 확장하는 데 활용한다.", counterpoint:"규제 필요성은 편향 존재만으로 자동 도출되지 않는다는 저자의 경고를 함께 반영한다.", related:["thesis-park-emergent-2021","article-barocas-selbst-2016"], url:"https://www.kci.go.kr/kciportal/landing/article.kci?arti_id=ART002829250", access:"KCI"
  },
  {
    id:"article-fairness-2023", type:"국내 학술논문", priority:"B", stage:"쟁점", jurisdiction:"대한민국", language:"한국어", title:"인공지능 공정성의 이론과 실제", translatedTitle:"", author:"박도현", year:2023, publication:"법철학연구 26(2), 5-52", citation:"박도현, 「인공지능 공정성의 이론과 실제」, 『법철학연구』 26(2), 2023, 5-52.", legalAreas:["법철학·규제이론","헌법·공법"], issues:["공정성","기술적 공정성","차별","불가능성 정리"], summary:"AI 공정성의 철학적·법적 의미와 기술적 공정성 지표, 상충 가능성을 연결하여 단일한 ‘공정한 알고리즘’이라는 표현의 한계를 보여준다.", mustRead:["공정성 개념의 다원성","기술적 지표 사이의 충돌","법적 평등과 수학적 공정성의 차이"], argumentUse:["규범목표를 기술지표로 환원하지 않는 근거","차별형 손해에서 설계자 의무의 구체화","공정성 실패를 책임판단에 연결할 때의 주의점"], researchFit:"에이전트별 목표함수·데이터·의사결정 기준이 충돌하는 경우 규범적 공정성 판단을 상위 귀속기준으로 두는 데 참고한다.", counterpoint:"특정 공정성 지표 실패만으로 위법·과실을 자동 인정하지 않는다.", related:["article-barocas-selbst-2016","article-park-bias-2022"], url:"https://www.kci.go.kr/kciportal/main.kci", access:"KCI 검색"
  },
  {
    id:"article-human-intervention-2026", type:"국내 학술논문", priority:"B", stage:"쟁점", jurisdiction:"대한민국·EU", language:"한국어", title:"인공지능의 자동화된 의사결정에 대한 인간의 개입", translatedTitle:"", author:"정애령", year:2026, publication:"유럽헌법연구 50, 161-187", citation:"정애령, 「인공지능의 자동화된 의사결정에 대한 인간의 개입」, 『유럽헌법연구』 50, 2026, 161-187.", legalAreas:["헌법·공법","데이터·개인정보"], issues:["인간개입","자동화 의사결정","인간존엄","자기결정권","설명"], summary:"자동화된 의사결정에서 인간의 개입이 인간존엄과 자기결정권 보호를 위한 절차적·규범적 장치가 되는 방식을 검토한다.", mustRead:["인간개입의 실질성","형식적 승인과 실제 통제의 차이","기본권 보호기능"], argumentUse:["human-in-the-loop 원칙의 헌법적 근거","운영자 감독의무의 내용","완전자동화와 부분자동화의 규범 차이"], researchFit:"계층적 책임귀속에서 인간개입 여부를 단순 면책조건이 아니라 통제가능성·개입실효성의 하나의 판단요소로 배치하는 데 활용한다.", counterpoint:"인간이 최종 버튼을 누른다는 사실만으로 실질적 통제나 과실을 입증한 것은 아니다.", related:["article-citron-2008","thesis-kim-automated-admin-2024"], url:"https://www.kci.go.kr/kciportal/main.kci", access:"KCI 검색"
  },
  {
    id:"article-copyright-genai-2025", type:"국내 학술논문", priority:"B", stage:"쟁점", jurisdiction:"대한민국", language:"한국어", title:"생성형 AI와 저작권 문제 - 저작권 침해와 저작물성의 사례와 분석", translatedTitle:"", author:"김경숙", year:2025, publication:"계간 저작권 38(2), 5-54", citation:"김경숙, 「생성형 AI와 저작권 문제 - 저작권 침해와 저작물성의 사례와 분석」, 『계간 저작권』 38(2), 2025, 5-54.", legalAreas:["지식재산"], issues:["생성형 AI","저작권 침해","저작물성","학습데이터"], summary:"생성형 AI의 학습과 산출물을 둘러싼 저작권 침해 및 저작물성 쟁점을 사례 중심으로 정리한다.", mustRead:["학습단계와 산출단계의 침해구조 구별","인간 창작적 기여","생성물의 저작물성"], argumentUse:["AI 행위효과의 재산권 귀속 사례","학습·생성 단계별 책임주체 구별","기능단위가 산출물 권리귀속의 매개가 될 수 있는지 검토"], researchFit:"책임뿐 아니라 AI가 만들어내는 법적 효과의 귀속을 설명하는 지식재산 사례로 사용한다.", counterpoint:"저작권상 저작자 지위와 민법상 권리주체성은 동일 개념이 아니다.", related:["article-patent-ai-2025","book-abbott-2020"], url:"https://doi.org/10.30582/kdps.2025.38.2.5", access:"DOI"
  },
  {
    id:"article-copyright-constitutional-2025", type:"국내 학술논문", priority:"B", stage:"쟁점", jurisdiction:"대한민국", language:"한국어", title:"인공지능과 저작권 제한의 헌법적 논의 — 학습데이터와 창작적 기여 및 변형물의 관계를 중심으로 —", translatedTitle:"", author:"권순재", year:2025, publication:"법학논총 42(3), 25-48", citation:"권순재, 「인공지능과 저작권 제한의 헌법적 논의」, 『법학논총』 42(3), 2025, 25-48.", legalAreas:["지식재산","헌법·공법"], issues:["학습데이터","저작권 제한","창작적 기여","변형물","재산권"], summary:"AI 학습데이터 이용을 저작권 제한과 헌법상 재산권·창작 인센티브의 관계에서 검토하고, 인간의 추가적 창작기여와 변형물의 보호범위를 논의한다.", mustRead:["TDM·학습 예외의 한계","저작권과 AI 혁신의 균형","인간 추가 기여의 의미"], argumentUse:["AI 규제가 기본권 충돌을 조정해야 한다는 사례","학습데이터의 무제한 이용론에 대한 반론","행위효과 귀속에서 인간 기여의 규범적 평가"], researchFit:"기능적 단위에 권리귀속 기능을 부여할 때 제3자의 기존 재산권을 침해하지 않는 제한원리를 구성하는 데 활용한다.", counterpoint:"저작권 제한의 위헌성 판단과 AI 법적 지위 문제는 별개의 논증단계를 거쳐야 한다.", related:["article-copyright-genai-2025","article-patent-ai-2025"], url:"https://doi.org/10.18018/HYLR.2025.42.3.025", access:"DOI"
  },
  {
    id:"article-patent-ai-2025", type:"국내 학술논문", priority:"B", stage:"쟁점", jurisdiction:"대한민국", language:"한국어", title:"인공지능 발명에 대한 특허법적 고찰: 발명자 지위와 발명 성립성을 중심으로", translatedTitle:"", author:"전병주", year:2025, publication:"The Journal of Law & IP 15(1), 87-122", citation:"전병주, 「인공지능 발명에 대한 특허법적 고찰: 발명자 지위와 발명 성립성을 중심으로」, 『The Journal of Law & IP』 15(1), 2025, 87-122.", legalAreas:["지식재산"], issues:["DABUS","발명자","AI 보조발명","자연인 발명자"], summary:"DABUS 논쟁을 포함해 AI 보조발명과 AI 생성발명을 구별하고 특허법상 발명자 지위와 인간 창작적 기여의 기준을 검토한다.", mustRead:["발명자 자연인 원칙","AI 보조와 AI 생성의 구별","인간 기여의 법적 평가"], argumentUse:["AI의 법적 행위효과와 법적 주체성의 분리 사례","법영역별로 필요한 법적 지위가 다를 수 있다는 기능주의 근거","권리귀속 규칙의 설계 가능성"], researchFit:"‘AI가 사실상 기여했다’는 기술적 사실과 ‘법이 누구를 발명자로 인정한다’는 규범적 귀속을 구별하는 사례로 활용한다.", counterpoint:"특허법의 발명자 개념은 책임주체나 민사상 법인격을 직접 결정하지 않는다.", related:["article-copyright-genai-2025","book-abbott-2020"], url:"https://doi.org/10.23190/lawnip.2025.15.1.003", access:"DOI"
  },
  {
    id:"article-hallucination-rights-2026", type:"국내 학술논문", priority:"B", stage:"쟁점", jurisdiction:"대한민국", language:"한국어", title:"생성형 인공지능 할루시네이션 현상의 법적 책임 구조와 기본권 보호를 위한 규범설계", translatedTitle:"", author:"이형석", year:2026, publication:"14(1), 49-88", citation:"이형석, 「생성형 인공지능 할루시네이션 현상의 법적 책임 구조와 기본권 보호를 위한 규범설계」, 2026, 14(1), 49-88.", legalAreas:["헌법·공법","민사·책임법","소비자·플랫폼"], issues:["할루시네이션","명예","정보자기결정권","표현의 자유","인간 최종책임"], summary:"생성형 AI의 할루시네이션을 단순 오류가 아니라 구조적 위험으로 보고, 기본권 침해와 사후 책임, 인간 최종책임을 연결한 규범설계를 검토한다.", mustRead:["할루시네이션의 구조적 위험성","명예·정보자기결정권·표현의 자유 충돌","사후 책임과 인간개입"], argumentUse:["생성형 AI의 비결정적 손해 사례","구조적 위험과 개별 과실의 분리","인간 최종책임 원칙의 실제 한계 검토"], researchFit:"복수 에이전트의 출력이 연쇄적으로 증폭되는 경우 단일 모델 할루시네이션보다 인과추적이 어려워지는 논증의 비교 사례로 사용한다.", counterpoint:"‘인간 최종책임’ 문구만으로 구체적 귀책주체와 주의의무 내용이 결정되지 않는다.", related:["norm-nist-genai","article-balkin-2015"], url:"https://www.kci.go.kr/kciportal/main.kci", access:"KCI 검색"
  },
  {
    id:"article-ai-search-liability-2025", type:"국내 학술논문", priority:"B", stage:"쟁점", jurisdiction:"대한민국", language:"한국어", title:"인공지능 검색 사업자의 법적 책임, 그리고 과제", translatedTitle:"", author:"김윤명", year:2025, publication:"법과 기업 연구 15(3), 33-66", citation:"김윤명, 「인공지능 검색 사업자의 법적 책임, 그리고 과제」, 『법과 기업 연구』 15(3), 2025, 33-66.", legalAreas:["소비자·플랫폼","지식재산","민사·책임법"], issues:["AI 검색","플랫폼 책임","저작권","답변생성","사업자책임"], summary:"검색결과를 단순 링크가 아니라 합성된 답변으로 제공하는 AI 검색 사업자의 지위와 책임 문제를 검토한다.", mustRead:["검색서비스와 생성형 답변의 차이","정보매개자 책임","저작권·오정보 책임의 결합"], argumentUse:["플랫폼이 에이전트 결과를 통합·제시할 때 통합자 책임 사례","배포자·서비스제공자의 통제가능성","사용자에게 최종 결과를 제공하는 층위의 의무"], researchFit:"다중에이전트 결과를 하나의 서비스가 취합해 외부에 제시하는 경우 ‘통합자’와 ‘배포자’ 층을 독립적으로 설정하는 데 활용한다.", counterpoint:"플랫폼 책임을 개별 모델 개발자의 책임과 합치지 않는다.", related:["norm-nist-genai","article-hallucination-rights-2026"], url:"https://doi.org/10.35505/sjlb.2025.12.15.3.33", access:"DOI"
  },
  {
    id:"article-ai-washing-2025", type:"국내 학술논문", priority:"B", stage:"쟁점", jurisdiction:"대한민국", language:"한국어", title:"AI워싱의 민사법적 책임과 대응방안 - 인공지능기본법 정의규정을 중심으로 -", translatedTitle:"", author:"김태형", year:2025, publication:"민사법의 이론과 실무 28(3), 125-182", citation:"김태형, 「AI워싱의 민사법적 책임과 대응방안 - 인공지능기본법 정의규정을 중심으로 -」, 『민사법의 이론과 실무』 28(3), 2025, 125-182.", legalAreas:["민사·책임법","소비자·플랫폼"], issues:["AI워싱","계약","설명의무","사기","표시광고","제품결함"], summary:"실제 AI 기능을 과장하거나 허위 표시하는 AI워싱을 계약취소·설명의무·사기·불법행위·표시광고·제품결함의 관점에서 검토한다.", mustRead:["AI기본법 정의와 민사법 효과","설명의무·기망의 성립","광고표시와 제품책임의 연결"], argumentUse:["AI 시스템의 법정 정의가 민사분쟁에서 갖는 간접효과","배포자·판매자의 설명책임","기술성능에 대한 표시와 실제 기능의 불일치"], researchFit:"에이전트 시스템의 등록·표시 내용과 실제 기능이 다를 경우 책임관리인·운영자의 정보제공 의무를 설계하는 데 활용한다.", counterpoint:"AI기본법상 정의 해당 여부만으로 민사상 사기나 과실이 자동 성립하지 않는다.", related:["norm-korea-ai-basic","article-ai-search-liability-2025"], url:"https://www.kci.go.kr/kciportal/main.kci", access:"KCI 검색"
  },
  {
    id:"book-abbott-2020", type:"해외 단행본", priority:"A", stage:"쟁점", jurisdiction:"미국·비교법", language:"영어", title:"The Reasonable Robot: Artificial Intelligence and the Law", translatedTitle:"합리적인 로봇: 인공지능과 법", author:"Ryan Abbott", year:2020, publication:"Cambridge University Press", citation:"Ryan Abbott, The Reasonable Robot: Artificial Intelligence and the Law, Cambridge University Press (2020).", legalAreas:["법철학·규제이론","민사·책임법","지식재산","비교법·국제"], issues:["AI 법적 중립성","합리적 로봇","불법행위","지식재산","형사책임"], summary:"사람과 AI가 동일한 기능을 수행할 때 법이 기술 때문에 불합리하게 차별하지 않아야 한다는 AI legal neutrality를 중심으로 여러 법영역을 재검토한다.", mustRead:["AI legal neutrality","reasonable robot standard","불법행위·지식재산에서 인간 기준을 AI에 적용할 때의 문제"], argumentUse:["기능적 접근의 해외 이론근거","주체의 본질보다 수행기능을 기준으로 법적 효과를 배분하는 논증","인간과 AI의 규율 비대칭 검토"], researchFit:"기능적 단위 법적 지위를 ‘인간과 같은 인격’이 아니라 특정 기능에 필요한 법적 incidents의 배분으로 설명하는 데 활용한다.", counterpoint:"기술중립성은 동일취급 원칙일 뿐 AI 법인격을 필연적으로 요구하지 않는다.", related:["article-bryson-persons-2017","book-chesterman-2021"], url:"https://www.cambridge.org/core/books/reasonable-robot/introduction-artificial-intelligence-and-the-law/DB801A3932CB86F1E08A6A10ACC91A8A", access:"출판사"
  },
  {
    id:"book-chesterman-2021", type:"해외 단행본", priority:"A", stage:"비교법", jurisdiction:"비교법", language:"영어", title:"We, the Robots? Regulating Artificial Intelligence and the Limits of the Law", translatedTitle:"우리, 로봇들? 인공지능 규제와 법의 한계", author:"Simon Chesterman", year:2021, publication:"Cambridge University Press", citation:"Simon Chesterman, We, the Robots? Regulating Artificial Intelligence and the Limits of the Law, Cambridge University Press (2021).", legalAreas:["법철학·규제이론","헌법·공법","민사·책임법","비교법·국제"], issues:["자율성","불투명성","책임","규제한계","AI 거버넌스"], summary:"자율성·불투명성·책임의 문제를 중심으로 기존 법의 한계와 새로운 규칙·기관·감독 구조가 필요한 조건을 체계적으로 분석한다.", mustRead:["법이 AI를 규율할 때의 세 가지 구조적 난점","기존법의 적응과 신설규범의 경계","책임과 규제기관의 역할"], argumentUse:["새 법적 단위를 만드는 제도정당화 기준","기존법으로 충분한 경우와 제도혁신이 필요한 경우의 구별","규제와 사법책임의 기능분업"], researchFit:"기능적 단위론이 과잉입법이 되지 않도록 ‘기존법 한계가 실제로 존재하는 영역’만 선별하는 검증틀로 사용한다.", counterpoint:"새 제도의 필요성을 주장할 때 단순한 기술 새로움이 아니라 구체적 법적 실패를 증명해야 한다.", related:["book-abbott-2020","article-scherer-2016"], url:"https://www.cambridge.org/core/books/we-the-robots/we-the-robots/976E650FDAF83FDF4F950AC105CBE612", access:"출판사"
  },
  {
    id:"article-calo-2015", type:"해외 학술논문", priority:"A", stage:"기초", jurisdiction:"미국", language:"영어", title:"Robotics and the Lessons of Cyberlaw", translatedTitle:"로봇공학과 사이버법의 교훈", author:"Ryan Calo", year:2015, publication:"103 California Law Review 513", citation:"Ryan Calo, Robotics and the Lessons of Cyberlaw, 103 California Law Review 513 (2015).", legalAreas:["법철학·규제이론","민사·책임법","비교법·국제"], issues:["로봇법","예측불가능성","물리적 손해","자율성","규제"], summary:"로봇·AI가 데이터 처리뿐 아니라 현실세계의 물리적 행동과 손해를 발생시키고 예측불가능성을 키운다는 점에서 기존 사이버법과 다른 법적 문제를 만든다고 분석한다.", mustRead:["디지털 위험과 물리적 위험의 결합","예측불가능성과 통제","사람과 도구의 경계가 흐려지는 문제"], argumentUse:["AI가 단순 정보서비스를 넘어 행위주체처럼 작동하는 사실적 전제","Physical AI·에이전트 손해의 법적 특수성","새로운 책임배분 논의의 출발점"], researchFit:"Agentic AI가 외부 시스템과 상호작용하면서 행위효과를 발생시키는 구조를 법적 문제로 정의하는 서론에 접목한다.", counterpoint:"로봇의 물리적 구현과 순수 소프트웨어 에이전트의 위험은 구별할 필요가 있다.", related:["article-balkin-2015","article-scherer-2016"], url:"https://digitalcommons.law.uw.edu/faculty-articles/23/", access:"원문"
  },
  {
    id:"article-balkin-2015", type:"해외 학술논문", priority:"A", stage:"쟁점", jurisdiction:"미국", language:"영어", title:"The Path of Robotics Law", translatedTitle:"로봇법의 길", author:"Jack M. Balkin", year:2015, publication:"California Law Review Online", citation:"Jack M. Balkin, The Path of Robotics Law, California Law Review Online (2015).", legalAreas:["법철학·규제이론","민사·책임법"], issues:["창발성","many hands","인과책임","인간-기계 상호작용"], summary:"로봇·AI의 행동이 인간과 기술의 상호작용에서 창발하고 여러 손(many hands)을 거치면서 예측과 인과적 책임 추적이 어려워진다는 점을 강조한다.", mustRead:["emergent behavior","many hands problem","사용자와 설계자의 책임이 분산되는 구조"], argumentUse:["창발적 손해의 해외 비교근거","다수 주체 책임분산의 개념화","계층적 책임귀속의 필요성 제시"], researchFit:"국내 창발적 해악론을 미국 로봇법 논의와 연결해 ‘창발성+다수주체’가 별개의 문제가 아니라 하나의 책임구조 문제임을 논증한다.", counterpoint:"창발성은 인과관계의 부존재가 아니라 인과구조의 복잡성을 뜻할 수 있으므로 증명책임 설계와 연결해야 한다.", related:["thesis-park-emergent-2021","article-calo-2015"], url:"https://www.californialawreview.org/online/the-path-of-robotics-law", access:"원문"
  },
  {
    id:"article-citron-2008", type:"해외 학술논문", priority:"A", stage:"교리", jurisdiction:"미국", language:"영어", title:"Technological Due Process", translatedTitle:"기술적 적법절차", author:"Danielle Keats Citron", year:2008, publication:"85 Washington University Law Review 1249", citation:"Danielle Keats Citron, Technological Due Process, 85 Washington University Law Review 1249 (2008).", legalAreas:["헌법·공법"], issues:["적법절차","자동화 의사결정","통지","청문","이유제시","책임성"], summary:"공공 자동화 의사결정이 규칙제정과 개별 판단을 결합하면서 전통적 적법절차 보호를 약화시킬 수 있음을 지적하고 기술적 적법절차라는 통제틀을 제시한다.", mustRead:["자동화가 절차적 권리를 약화시키는 구조","통지·의견제출·이유제시","코드와 행정규칙의 관계"], argumentUse:["자동화 의사결정에서 절차보장의 고전적 근거","설명·이의제기·감사로그 설계","공법상 인간개입의 정당화"], researchFit:"기능적 단위가 공적 의사결정에 참여할 경우 별도의 책임주체 논의와 관계없이 절차적 통제가 필수라는 제한원리로 사용한다.", counterpoint:"2008년 논문이므로 생성형 AI·에이전트 구조는 최신 규범과 후속문헌으로 보완한다.", related:["thesis-kim-automated-admin-2024","article-kroll-accountable-2017"], url:"https://journals.library.wustl.edu/lawreview/article/id/6697/", access:"원문"
  },
  {
    id:"article-kroll-accountable-2017", type:"해외 학술논문", priority:"A", stage:"제도설계", jurisdiction:"미국", language:"영어", title:"Accountable Algorithms", translatedTitle:"책임성 있는 알고리즘", author:"Joshua A. Kroll et al.", year:2017, publication:"165 University of Pennsylvania Law Review 633", citation:"Joshua A. Kroll et al., Accountable Algorithms, 165 University of Pennsylvania Law Review 633 (2017).", legalAreas:["헌법·공법","데이터·개인정보","법적 추론"], issues:["알고리즘 책임성","검증","감사","절차적 공정성"], summary:"알고리즘 시스템이 법적·절차적 요구를 충족하는지 기술적으로 검증할 수 있는 여러 도구와 제도적 책임성 구조를 제안한다.", mustRead:["설명과 검증의 차이","감사가능한 시스템 설계","절차적 공정성을 기술적으로 뒷받침하는 방법"], argumentUse:["로그·검증·감사 의무의 기술법적 근거","설명 불가능성을 이유로 책임을 포기할 필요가 없다는 논증","증거보존·검증가능성의 제도설계"], researchFit:"다중에이전트 시스템에 행위로그·메시지 추적·버전관리·감사기록을 법적 incidents로 부과하는 근거에 접목한다.", counterpoint:"기술적 검증가능성이 곧 법적 책임 귀속의 정당성을 보장하는 것은 아니다.", related:["book-ai-principles-2021","norm-nist-ai-rmf"], url:"https://pennlawreview.com/2017/02/23/accountable-algorithms/", access:"원문"
  },
  {
    id:"article-barocas-selbst-2016", type:"해외 학술논문", priority:"A", stage:"쟁점", jurisdiction:"미국", language:"영어", title:"Big Data's Disparate Impact", translatedTitle:"빅데이터의 차별적 영향", author:"Solon Barocas & Andrew D. Selbst", year:2016, publication:"104 California Law Review 671", citation:"Solon Barocas & Andrew D. Selbst, Big Data's Disparate Impact, 104 California Law Review 671 (2016).", legalAreas:["헌법·공법","데이터·개인정보"], issues:["알고리즘 차별","편향","데이터","간접차별"], summary:"데이터 기반 의사결정이 명시적 차별의도가 없어도 사회적 편향을 재생산해 차별적 영향을 만들 수 있음을 고용차별법과 데이터 분석 구조를 통해 보여준다.", mustRead:["데이터 편향의 발생경로","차별의도와 차별효과의 구별","프록시 변수와 모델 설계"], argumentUse:["학습데이터 위험의 기본 해외문헌","결과 편향을 단일 개발자 과실로 환원하기 어려운 근거","데이터 공급·설계·운용의 계층 책임"], researchFit:"창발적 손해 가운데 차별·편향형 손해를 데이터층과 모델층의 상호작용으로 분석하는 데 활용한다.", counterpoint:"미국 차별법의 doctrinal context를 한국 기본권·평등법 논의에 그대로 이식하지 않는다.", related:["article-training-data-liability-2025","article-park-bias-2022"], url:"https://doi.org/10.2139/ssrn.2477899", access:"SSRN·DOI"
  },
  {
    id:"article-scherer-2016", type:"해외 학술논문", priority:"A", stage:"제도설계", jurisdiction:"미국", language:"영어", title:"Regulating Artificial Intelligence Systems: Risks, Challenges, Competencies, and Strategies", translatedTitle:"인공지능 시스템 규제: 위험, 도전, 역량과 전략", author:"Matthew U. Scherer", year:2016, publication:"29 Harvard Journal of Law & Technology", citation:"Matthew U. Scherer, Regulating Artificial Intelligence Systems: Risks, Challenges, Competencies, and Strategies, 29 Harvard Journal of Law & Technology (2016).", legalAreas:["법철학·규제이론","민사·책임법","헌법·공법"], issues:["AI 규제","위험","기관역량","불법행위","차등책임"], summary:"AI 규제가 직면하는 예측·통제·전문성 문제를 분석하고, 규제기관의 역량과 책임법을 결합한 전략을 검토한다.", mustRead:["AI 위험의 규제상 난점","기관 전문성 문제","불법행위책임을 규제도구로 사용하는 방식"], argumentUse:["사전규제와 사후책임의 기능분업","위험수준에 따른 책임강도 차등","전문기관·감사체계 설계"], researchFit:"기능적 단위의 등록·보험·감독을 모든 AI에 적용하지 않고 위험·자율성·외부효과 수준에 따라 차등화하는 근거로 사용한다.", counterpoint:"포괄적 규제모델은 최신 AI Act·한국 AI기본법의 실제 제도와 대조해야 한다.", related:["norm-eu-ai-act","norm-korea-ai-basic","book-chesterman-2021"], url:"https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2609777", access:"SSRN 원문"
  },
  {
    id:"article-bryson-persons-2017", type:"해외 학술논문", priority:"A", stage:"쟁점", jurisdiction:"비교법", language:"영어", title:"Of, for, and by the People: the Legal Lacuna of Synthetic Persons", translatedTitle:"사람에 의한, 사람을 위한 인공적 법인격과 법적 공백", author:"Joanna J. Bryson, Mihailis E. Diamantis & Thomas D. Grant", year:2017, publication:"Artificial Intelligence and Law 25, 273-291", citation:"Joanna J. Bryson, Mihailis E. Diamantis & Thomas D. Grant, Of, for, and by the People: the Legal Lacuna of Synthetic Persons, 25 Artificial Intelligence and Law 273 (2017).", legalAreas:["법철학·규제이론","민사·책임법","상법·회사법"], issues:["AI 법인격","synthetic persons","책임회피","법적 허구"], summary:"AI에 법인격을 부여하는 것이 도덕적으로 필요하지 않고, 기존 법인의 법적 허구와 결합해 책임회피와 규범적 혼란을 만들 수 있다고 강하게 비판한다.", mustRead:["AI 법인격 부정의 규범적 근거","법적 허구의 오남용 가능성","책임을 인간·조직으로 되돌리는 논리"], argumentUse:["기능적 단위론의 핵심 반대문헌","법인격 남용·책임회피 방지장치 필요성","전면적 인격부여와 제한적 법적 incidents의 구별"], researchFit:"기능적 단위에 독립 인격을 부여하는 것이 아니라 책임재산·등록·소송지위 등 특정 기능만 부여하고 배후 인간책임을 차단하지 않는 이유를 논증하는 반론축이다.", counterpoint:"반대론을 회피하지 말고 법인격 부인·배후책임·최소자본/보험·책임관리인으로 남용위험을 어떻게 통제할지 제시해야 한다.", related:["article-shin-personhood-2018","book-abbott-2020","thesis-lee-tort-2021"], url:"https://doi.org/10.1007/s10506-017-9214-9", access:"DOI·오픈액세스"
  },
  {
    id:"article-wachter-explanation-2017", type:"해외 학술논문", priority:"A", stage:"쟁점", jurisdiction:"EU", language:"영어", title:"Why a Right to Explanation of Automated Decision-Making Does Not Exist in the General Data Protection Regulation", translatedTitle:"GDPR에 자동화 의사결정 설명권이 존재하지 않는다는 논증", author:"Sandra Wachter, Brent Mittelstadt & Luciano Floridi", year:2017, publication:"International Data Privacy Law 7(2), 76-99", citation:"Sandra Wachter, Brent Mittelstadt & Luciano Floridi, Why a Right to Explanation of Automated Decision-Making Does Not Exist in the General Data Protection Regulation, 7(2) International Data Privacy Law 76 (2017).", legalAreas:["데이터·개인정보","헌법·공법","비교법·국제"], issues:["설명권","GDPR","자동화 의사결정","투명성"], summary:"GDPR에서 흔히 주장되는 강한 의미의 개별 설명권이 문언상 존재하지 않는다고 분석하며, 정보제공 의무와 사후 설명을 구별한다.", mustRead:["right to explanation 논쟁의 문언적 근거","system functionality 정보와 개별 결정 설명의 차이","GDPR 조문 해석"], argumentUse:["설명의무를 과장하지 않기 위한 반대문헌","설명·정보공개·감사의 기능분화","외국법 인용 시 정확한 범위 설정"], researchFit:"기능적 단위에 설명의무를 부과할 때 ‘설명’의 범위를 법적 효과, 로그, 모델정보, 개별결정 이유로 세분화하는 데 활용한다.", counterpoint:"후속 Kaminski의 넓은 알고리즘 책임성 해석을 반드시 대조한다.", related:["article-kaminski-explanation-2019","thesis-kang-hyekyung-2024"], url:"https://doi.org/10.1093/idpl/ipx005", access:"DOI"
  },
  {
    id:"article-kaminski-explanation-2019", type:"해외 학술논문", priority:"A", stage:"쟁점", jurisdiction:"EU·미국", language:"영어", title:"The Right to Explanation, Explained", translatedTitle:"설명권에 대한 설명", author:"Margot E. Kaminski", year:2019, publication:"34 Berkeley Technology Law Journal 189", citation:"Margot E. Kaminski, The Right to Explanation, Explained, 34 Berkeley Technology Law Journal 189 (2019).", legalAreas:["데이터·개인정보","헌법·공법","비교법·국제"], issues:["설명권","알고리즘 책임성","GDPR","절차적 권리"], summary:"GDPR의 여러 권리와 의무를 종합하면 단일한 ‘설명권’ 문구보다 넓은 알고리즘 책임성 구조가 형성된다고 해석한다.", mustRead:["Wachter 논문에 대한 반론","설명권을 권리묶음으로 보는 관점","절차적·구조적 책임성"], argumentUse:["상반된 해외학설 대립축 구성","설명권을 단일 권리보다 incidents 묶음으로 설계","정보·이의제기·인간검토의 결합"], researchFit:"기능적 단위의 법적 지위도 하나의 추상적 인격개념보다 권리·의무·절차 incidents의 묶음으로 설계할 수 있다는 방법론적 유추에 활용한다.", counterpoint:"GDPR 해석 논쟁을 한국법상 독립 권리의 존재로 곧바로 전환하지 않는다.", related:["article-wachter-explanation-2017","article-citron-2008"], url:"https://doi.org/10.15779/Z38TD9N83H", access:"DOI"
  },
  {
    id:"norm-korea-ai-basic", type:"규범자료", priority:"A", stage:"제도설계", jurisdiction:"대한민국", language:"한국어", title:"인공지능 발전과 신뢰 기반 조성 등에 관한 기본법", translatedTitle:"AI Basic Act of Korea", author:"대한민국", year:2026, publication:"국가법령정보센터", citation:"「인공지능 발전과 신뢰 기반 조성 등에 관한 기본법」, 현행법령.", legalAreas:["헌법·공법","민사·책임법","데이터·개인정보","산업·융합법"], issues:["AI기본법","고영향 AI","투명성","사업자의무","신뢰기반"], summary:"한국 AI 규율의 기본 틀을 제공하는 1차 규범자료다. 연구문헌의 주장과 별도로 현행 정의·적용대상·사업자의무·고영향 AI 규율은 반드시 이 원문에서 확인한다.", mustRead:["AI 및 관련 주체의 법정 정의","고영향 AI와 투명성 관련 의무","시행령·고시로 위임된 세부사항"], argumentUse:["국내 현행법 기준선","문헌의 개념과 법정개념 불일치 확인","책임법 제안이 현행 규제의무와 중복되는지 검토"], researchFit:"계층적 책임귀속에서 규제상 의무주체와 민사상 귀책주체가 일치하는지 비교하고, 기능적 단위 등록제의 제도적 접점을 확인한다.", counterpoint:"행정규제상 의무 위반과 민사상 손해배상책임 성립은 별도의 법적 요건이다.", related:["article-lee-soeun-seo-2026","book-eu-ai-act-2024"], url:"https://www.law.go.kr/LSW/lsInfoP.do?lsId=014820", access:"공식 법령"
  },
  {
    id:"norm-eu-ai-act", type:"규범자료", priority:"A", stage:"비교법", jurisdiction:"EU", language:"영어", title:"Regulation (EU) 2024/1689 — Artificial Intelligence Act", translatedTitle:"EU 인공지능법", author:"European Union", year:2024, publication:"EUR-Lex", citation:"Regulation (EU) 2024/1689 (Artificial Intelligence Act).", legalAreas:["헌법·공법","데이터·개인정보","비교법·국제","산업·융합법"], issues:["위험기반 규제","고위험 AI","GPAI","공급자","배포자","기록의무"], summary:"EU의 위험기반 AI 규율을 정한 1차 법규범이다. 공급자·배포자 등 행위자별 의무, 고위험 AI, 범용 AI, 기록·투명성·감독 구조를 원문으로 확인하는 기준자료다.", mustRead:["정의와 적용범위","고위험 AI 의무","공급망 행위자의 역할","기록·감독·적합성평가"], argumentUse:["책임사슬의 역할분류 비교","사전 위험관리와 사후책임의 기능구별","로그·문서화·등록 의무의 비교법 근거"], researchFit:"다중에이전트 시스템의 설계·통합·배치·운용 역할을 EU의 provider/deployer 등 역할과 비교해 계층 분류의 객관성을 검증한다.", counterpoint:"AI Act는 주로 규제법이며 민사책임의 완결적 체계가 아니다.", related:["book-eu-ai-act-2024","thesis-kang-hyekyung-2024","article-scherer-2016"], url:"https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32024R1689", access:"공식 법령"
  },
  {
    id:"norm-nist-ai-rmf", type:"규범자료", priority:"A", stage:"제도설계", jurisdiction:"미국·국제", language:"영어", title:"Artificial Intelligence Risk Management Framework (AI RMF 1.0)", translatedTitle:"인공지능 위험관리 프레임워크 1.0", author:"NIST", year:2023, publication:"National Institute of Standards and Technology", citation:"NIST, Artificial Intelligence Risk Management Framework (AI RMF 1.0), 2023.", legalAreas:["법철학·규제이론","상법·회사법","산업·융합법"], issues:["위험관리","거버넌스","측정","감사","책임성"], summary:"조직이 AI 위험을 Govern, Map, Measure, Manage의 체계로 관리하도록 제시하는 대표적 비강제 프레임워크다. 법적 책임 자체보다 조직적 통제의 구체화를 위해 사용한다.", mustRead:["Govern·Map·Measure·Manage 구조","조직 역할과 책임","위험 측정·모니터링·문서화"], argumentUse:["주의의무·내부통제의 구체적 내용","로그·감사·위험관리 의무 설계","회사법상 이사·운영자의 합리적 감독 기준 보조"], researchFit:"계층적 책임귀속의 각 층위에 어떤 사전통제 의무를 부여할지 체크리스트가 아니라 규범화 가능한 관리요소로 추출한다.", counterpoint:"자율적 프레임워크이므로 법적 의무의 직접 근거로 인용하지 않고 주의의무 내용의 참고표준으로 사용한다.", related:["article-kroll-accountable-2017","article-namgung-director-2024","article-trustworthy-ai-2022"], url:"https://www.nist.gov/publications/artificial-intelligence-risk-management-framework-ai-rmf-10", access:"공식 원문"
  },
  {
    id:"norm-nist-genai", type:"규범자료", priority:"B", stage:"제도설계", jurisdiction:"미국·국제", language:"영어", title:"Artificial Intelligence Risk Management Framework: Generative Artificial Intelligence Profile", translatedTitle:"NIST 생성형 AI 위험관리 프로파일", author:"NIST", year:2024, publication:"National Institute of Standards and Technology", citation:"NIST, Artificial Intelligence Risk Management Framework: Generative Artificial Intelligence Profile, 2024.", legalAreas:["법철학·규제이론","소비자·플랫폼","산업·융합법"], issues:["생성형 AI","할루시네이션","정보무결성","위험관리","콘텐츠"], summary:"생성형 AI 특유의 위험을 AI RMF에 연결해 구체화한 프로파일이다. 할루시네이션, 정보무결성, 오용 등 생성형 모델의 위험관리 항목을 정리한다.", mustRead:["생성형 AI 특유 위험 분류","측정·모니터링 방법","사람·조직의 관리조치"], argumentUse:["생성형 AI 손해유형의 사실적 분류","예견가능성과 사전주의의무 구체화","모델 제공자·통합자·배포자의 통제조치 비교"], researchFit:"다중 에이전트에 생성형 모델이 포함된 경우 일반 AI 위험과 생성형 특유 위험을 분리해 귀책 기준을 세분화하는 데 활용한다.", counterpoint:"법적 구속력이 없는 기술·거버넌스 표준임을 명시한다.", related:["article-hallucination-rights-2026","norm-nist-ai-rmf"], url:"https://www.nist.gov/itl/ai-risk-management-framework/ai-rmf-generative-ai-profile", access:"공식 원문"
  },
  {
    id:"norm-oecd-ai-principles", type:"규범자료", priority:"B", stage:"기초", jurisdiction:"국제", language:"영어", title:"OECD AI Principles", translatedTitle:"OECD 인공지능 원칙", author:"OECD", year:2024, publication:"OECD.AI — 2019 채택, 2024 개정", citation:"OECD, OECD AI Principles, adopted 2019, updated 2024.", legalAreas:["법철학·규제이론","헌법·공법","비교법·국제"], issues:["인간중심 AI","투명성","책임성","안전","국제원칙"], summary:"인간중심 가치, 투명성, 안전·보안, 책임성 등 국제적으로 반복되는 AI 거버넌스 원칙의 공통분모를 제공한다.", mustRead:["인간중심 가치","투명성·설명가능성","책임성","안전·보안"], argumentUse:["국제적 규범원칙의 최소 공통분모","국내 제도설계의 목적조항·원칙 수준 근거","법적 incidents의 정책목표 설명"], researchFit:"기능적 단위 제도를 도입할 경우 어떤 가치목표를 충족해야 하는지 상위원칙으로 사용하고, 구체 요건은 법률문헌에서 도출한다.", counterpoint:"원칙 수준 문서는 구체적 책임요건이나 권리의 직접 근거가 아니다.", related:["article-trustworthy-ai-2022","norm-nist-ai-rmf"], url:"https://oecd.ai/en/ai-principles", access:"공식 원문"
  },
  {
    id:"article-ai-constitutional-automation-2024", type:"해외 학술논문", priority:"B", stage:"비교법", jurisdiction:"대한민국·비교법", language:"영어", title:"Automated decision-making in South Korea", translatedTitle:"한국의 자동화된 의사결정", author:"Do Hyun Park et al.", year:2024, publication:"International comparative literature", citation:"Do Hyun Park et al., Automated decision-making in South Korea (2024).", legalAreas:["헌법·공법","데이터·개인정보","비교법·국제"], issues:["자동화 의사결정","한국법","개인정보","설명","비교법"], summary:"한국의 자동화 의사결정 관련 법제와 제도적 특징을 영문 비교법 문맥에서 파악하는 보완자료다.", mustRead:["한국 개인정보법상 자동화 의사결정 규율","국내 제도의 국제비교상 위치","설명·거부·인간개입의 구조"], argumentUse:["한국법을 해외문헌에 소개된 형태로 역검증","비교법 장에서 국내 제도의 특수성 설명","국내법 개정 논의의 국제적 맥락"], researchFit:"한국 규율을 EU·미국과 비교할 때 국내 학술문헌의 자기기술만으로 생길 수 있는 편향을 줄이는 보완문헌으로 활용한다.", counterpoint:"영문 비교문헌의 요약이 현행 한국법 원문을 대체하지 않는다.", related:["norm-korea-ai-basic","thesis-kim-automated-admin-2024"], url:"https://scholar.google.com/scholar?q=%22Automated+decision-making+in+South+Korea%22", access:"학술검색"
  },
  {
    id:"article-ai-fairness-law-2023-en", type:"해외 학술논문", priority:"B", stage:"쟁점", jurisdiction:"비교법", language:"영어", title:"Artificial Intelligence, Fairness, and Legal Governance", translatedTitle:"인공지능 공정성과 법적 거버넌스 관련 해외문헌 탐색축", author:"Selected comparative literature", year:2023, publication:"Comparative research axis", citation:"해외 공정성·차별 관련 비교문헌군 — Barocas & Selbst 등 원문에서 확장.", legalAreas:["헌법·공법","법철학·규제이론","비교법·국제"], issues:["공정성","차별","거버넌스","기술지표"], summary:"공정성·차별 논증을 국내 논문 하나에 의존하지 않고 해외의 차별법·기술공정성 문헌으로 확장하기 위한 연구노드다.", mustRead:["법적 공정성과 수학적 공정성의 불일치","차별효과의 증명","지표 선택의 규범성"], argumentUse:["비교문헌 확장용 검색 노드","공정성 장의 후속 해외문헌 확보","국내 논증의 국제적 검증"], researchFit:"향후 해외 학술논문을 추가 수집할 때 공정성·편향 카테고리의 확장 기준점으로 사용한다.", counterpoint:"이 항목은 단일 문헌의 직접 인용용이 아니라 후속 문헌탐색 노드다.", related:["article-barocas-selbst-2016","article-fairness-2023"], url:"https://scholar.google.com/scholar?q=artificial+intelligence+fairness+law+algorithmic+discrimination", access:"학술검색"
  },
  {
    id:"norm-council-europe-ai", type:"규범자료", priority:"B", stage:"비교법", jurisdiction:"유럽·국제", language:"영어", title:"Framework Convention on Artificial Intelligence and Human Rights, Democracy and the Rule of Law", translatedTitle:"인공지능·인권·민주주의·법치주의 기본협약", author:"Council of Europe", year:2024, publication:"Council of Europe", citation:"Council of Europe Framework Convention on Artificial Intelligence and Human Rights, Democracy and the Rule of Law (2024).", legalAreas:["헌법·공법","비교법·국제"], issues:["인권","민주주의","법치주의","AI 거버넌스"], summary:"AI 생애주기 활동이 인권·민주주의·법치주의와 양립하도록 하는 국제적 기본 틀을 제공한다.", mustRead:["인권영향과 위험평가","공공기관과 민간주체의 책무","법치주의와 구제절차"], argumentUse:["기본권 보호를 제도설계의 외부 한계로 설정","AI 거버넌스의 국제규범 맥락","공법·민사 책임제도의 정당화 배경"], researchFit:"기능적 단위 법적 지위가 피해자 권리구제를 약화시키지 않아야 한다는 외부 제한원리로 활용한다.", counterpoint:"국내 적용 가능성·체약상태는 실제 논문 작성 시 최신 공식 자료를 별도 확인한다.", related:["norm-oecd-ai-principles","norm-eu-ai-act"], url:"https://www.coe.int/en/web/artificial-intelligence/the-framework-convention-on-artificial-intelligence", access:"공식 원문"
  }
];

window.AI_LITERATURE_ROUTES = [
  {id:"route-emergent",title:"책임귀속·창발적 손해",area:"민사·책임법",description:"창발성의 개념에서 출발해 기존 민사책임, 다수주체·인과분산, 최신 책임론과 위험관리까지 연결합니다.",path:"인공지능 원론 → 박도현 박사논문 → 이해원 박사논문 → Balkin·Calo → 최신 국내 민사책임 → NIST",recordIds:["book-ai-principles-2021","thesis-park-emergent-2021","thesis-lee-tort-2021","article-balkin-2015","article-calo-2015","article-lee-soeun-seo-2026","norm-nist-ai-rmf"]},
  {id:"route-personhood",title:"법인격·기능적 책임주체",area:"법철학·규제이론",description:"전자인격 찬성·기능론과 법인격 부정론을 먼저 충돌시킨 뒤, 기능적 incidents가 필요한 범위를 좁혀갑니다.",path:"신현탁 → Bryson·Diamantis·Grant → Abbott → Chesterman → 이해원 → 책임재산·소송지위 설계",recordIds:["article-shin-personhood-2018","article-bryson-persons-2017","book-abbott-2020","book-chesterman-2021","thesis-lee-tort-2021","article-kim-error-2022"]},
  {id:"route-public",title:"헌법·자동화 의사결정·공법",area:"헌법·공법",description:"적법절차와 설명·검증에서 시작해 국내 자동적 처분, AI기본법과 EU 위험기반 규율로 이어집니다.",path:"Citron → Kroll → Wachter ↔ Kaminski → 김휘식 박사논문 → 한국 AI기본법 → EU AI Act",recordIds:["article-citron-2008","article-kroll-accountable-2017","article-wachter-explanation-2017","article-kaminski-explanation-2019","thesis-kim-automated-admin-2024","norm-korea-ai-basic","norm-eu-ai-act"]},
  {id:"route-tort",title:"민법·불법행위·제품책임",area:"민사·책임법",description:"전통적 민사책임 교리에서 시작해 오류사고, 위험책임, 데이터 결함, 보험·증명부담까지 단계적으로 읽습니다.",path:"정진명 → 김진아 → 이해원 → Scherer → 학습데이터 책임 → 이소은·서종희",recordIds:["article-jeong-civil-2018","article-kim-error-2022","thesis-lee-tort-2021","article-scherer-2016","article-training-data-liability-2025","article-lee-soeun-seo-2026"]},
  {id:"route-company",title:"상법·회사법·기업 내부통제",area:"상법·회사법",description:"회사의 AI 활용과 이사책임을 중심으로 위험관리와 감독의무를 구체화합니다.",path:"최문희 → 남궁주현 → Chesterman → NIST AI RMF → 한국 AI기본법",recordIds:["article-choi-company-2020","article-namgung-director-2024","book-chesterman-2021","norm-nist-ai-rmf","norm-korea-ai-basic"]},
  {id:"route-data",title:"개인정보·데이터·설명권",area:"데이터·개인정보",description:"국내 개인정보법 기초와 EU 규범중첩, 설명권 논쟁, 학습데이터 책임을 하나의 데이터 책임사슬로 연결합니다.",path:"인공지능 시대의 개인정보 보호법 → 강혜경 박사논문 → Wachter ↔ Kaminski → EU AI Act → 학습데이터 책임",recordIds:["book-privacy-ai-2022","thesis-kang-hyekyung-2024","article-wachter-explanation-2017","article-kaminski-explanation-2019","norm-eu-ai-act","article-training-data-liability-2025"]},
  {id:"route-ip",title:"저작권·특허·AI 산출물",area:"지식재산",description:"AI 학습과 산출물, 인간 창작적 기여, 발명자 지위를 통해 ‘사실상 기여’와 ‘법적 귀속’을 구별합니다.",path:"김경숙 → 권순재 → 전병주 → Abbott → AI 행위효과와 권리귀속의 분리",recordIds:["article-copyright-genai-2025","article-copyright-constitutional-2025","article-patent-ai-2025","book-abbott-2020"]},
  {id:"route-genai",title:"생성형 AI·플랫폼·할루시네이션",area:"소비자·플랫폼",description:"생성형 AI 특유의 오류·정보위험을 기본권, 민사책임, 위험관리 관점에서 읽습니다.",path:"할루시네이션 기본권 → AI 검색 책임 → NIST GenAI Profile → AI기본법 → 로그·책임 설계",recordIds:["article-hallucination-rights-2026","article-ai-search-liability-2025","norm-nist-genai","norm-korea-ai-basic","article-kroll-accountable-2017"]}
];
