(()=>{
'use strict';
const app=document.getElementById('courseApp');
const toast=document.getElementById('toast');
const curriculum=window.NEXUS_CURRICULUM;
const textbook=window.NEXUS_CORE_TEXTBOOK||{};
const params=new URLSearchParams(location.search);
const id=params.get('id');
const course=curriculum?.all?.find(c=>c.id===id);
const esc=window.NEXUS_UNIVERSITY_UTILS.escapeHtml;
const domainLabels={core:'University Core',humanities:'인문학',social:'사회과학',law:'법학·공공정책',natural:'자연과학',engineering:'공학',computing:'컴퓨팅·AI',medicine:'의학·보건',architecture:'건축·도시',arts:'예술·디자인',theology:'신학·성서학',education:'교육·학습과학',interdisciplinary:'융합학'};
const moduleTitles=['기초개념과 구조','핵심원리와 방법','사례·적용·비판','현대쟁점과 종합'];
const genericBlueprints={
 humanitites:['핵심 개념','역사적 맥락','원전 읽기','대표 이론','해석 방법','비교 관점','대표 사례','대립 해석','비판과 반론','현대 적용','인접학문 연결','종합 세미나'],
 social:['핵심 개념','행위자와 구조','고전 이론','현대 이론','자료와 측정','인과와 설명','대표 사회현상','제도 분석','비판과 대안','정책 적용','AI·디지털 쟁점','종합 사례'],
 law:['법원과 개념','법률관계','요건과 효과','해석 방법','대표 학설','판례 구조','절차와 증명','사례 포섭','대립논증','비교법·정책','AI·기술 쟁점','종합 사례'],
 natural:['기본 단위와 변수','핵심 법칙','측정과 오차','대표 모형','실험 방법','수학적 관계','대표 현상','자료 해석','모형의 한계','응용 문제','현대 연구','종합 실험'],
 engineering:['요구조건','기초 원리','수학적 모델','재료·구성요소','설계 방법','시뮬레이션','대표 시스템','실험·검증','고장·안전','최적화','AI·자동화','설계 프로젝트'],
 computing:['문제와 추상화','자료 표현','핵심 알고리즘','시스템 구조','구현 방법','성능 분석','대표 서비스','테스트·검증','보안·실패','확장성','AI·사회 쟁점','구현 프로젝트'],
 medicine:['정상 구조','정상 기능','병태생리','원인·위험요인','증상과 징후','검사와 진단','감별진단','치료 원리','약물·처치','예후·예방','윤리·의료AI','Case Conference'],
 architecture:['공간과 사용자','대지와 맥락','형태와 구성','구조와 하중','재료와 구축','환경과 설비','대표 사례','도면·BIM','안전·법규','도시 연결','스마트시티·AI','Design Studio'],
 arts:['매체와 형식','기초 요소','역사와 양식','작품분석','기법과 제작','구성 원리','대표 작품','창작 실습','비평과 수정','디지털 미디어','생성형 AI','Creative Capstone'],
 theology:['본문·정경','원어와 용어','역사적 맥락','해석 방법','신학적 주제','교리사','대표 본문','상호본문성','논쟁과 반론','수용사','디지털 본문연구','Exegetical Capstone'],
 education:['학습문제와 목표','학습자 차이','학습이론','교육과정','설명과 연습','수업 상호작용','평가와 측정','피드백','학습데이터','디지털 학습','AI Tutor','Instructional Design'],
 interdisciplinary:['문제정의','이해관계자','시스템 맵','전문분야 렌즈','사회·윤리 렌즈','증거와 불확실성','위험과 실패','가치충돌','법·거버넌스','시나리오','대안설계','통합 Capstone'],
 core:['개념과 문제','핵심 용어','기본 구조','대표 이론','방법과 증거','분석과 추론','대표 사례','반론과 한계','검증 방법','현대 적용','인접학문','종합 과제']
};
function storageGet(key){try{return JSON.parse(localStorage.getItem(key)||'[]')}catch{return[]}}
function storageSet(key,value){try{localStorage.setItem(key,JSON.stringify(value))}catch{}}
function copyText(text){if(navigator.clipboard&&window.isSecureContext)return navigator.clipboard.writeText(text);const t=document.createElement('textarea');t.value=text;t.style.position='fixed';t.style.opacity='0';document.body.append(t);t.select();document.execCommand('copy');t.remove();return Promise.resolve();}
function showToast(message){if(!toast)return;toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1400);}
function courseMeta(c,total,rich){const items=[c.college,c.department,`Level ${c.level}`,`${total} Lessons`,rich?'TEXTBOOK CORE':'COURSE MODEL 1.0'];(c.required||[]).forEach(x=>items.push(`Required ${x}`));(c.recommended||[]).forEach(x=>items.push(`Recommended ${x}`));if(!(c.required||[]).length)items.push('선수과목 없음');return items;}
function progressBlock(c,total,done){return `<section class="progress-card" aria-label="학습 진도"><div class="progress-head"><strong>${esc(c.id)} 학습진도</strong><span id="progressText">${done.size} / ${total} Lessons</span></div><div class="progress-track"><div class="progress-bar" id="progressBar" style="width:${(done.size/total)*100}%"></div></div></section>`;}
function richLesson(c,l,n,done){const key=`L${String(n).padStart(2,'0')}`;const completed=done.has(key);const theories=l[2]||[];const formula=l[3]||'';const caseText=l[4]||'';const readings=l[5]||[];const prompt=`${c.id} ${c.title}의 ${key} ${l[0]}을 공부 중이다. ${theories.join(', ')}의 의미를 내가 직접 설명하게 한 뒤 틀린 전제나 빠진 조건을 한 번에 하나씩 질문해 줘. ${formula?`공식 또는 모형 ${formula}의 각 항과 적용조건도 확인해 줘. `:''}마지막에는 ${caseText} 사례를 변형한 새 문제를 제시하고 내 답을 개념·근거·적용·반론 기준으로 평가해 줘.`;
return `<details class="lesson ${completed?'completed':''}" id="${key.toLowerCase()}" ${n===1?'open':''}><summary><span class="lesson-no">${key}</span><span class="lesson-title"><strong>${esc(l[0])}</strong><span>${esc(l[1])}</span></span><span class="lesson-check">${completed?'완료':'미완료'}</span></summary><div class="lesson-body"><div class="lesson-section"><h3>핵심 질문</h3><p>${esc(`${l[0]}은 ${c.title}에서 무엇을 설명하며, 어떤 전제와 적용한계를 가지는가?`)}</p></div><div class="lesson-section"><h3>본강의</h3><p class="lesson-thesis">${esc(l[1])}</p><p>${esc(`${c.title}에서는 이 내용을 독립된 암기항목으로 보지 않고 앞선 개념·자료·방법과 연결해 이해해야 한다. 아래 이론과 모형이 무엇을 설명하는지, 어떤 조건에서 성립하는지, 실제 사례에서 어떤 변수가 빠질 수 있는지를 함께 점검한다.`)}</p></div><div class="lesson-section"><h3>핵심 이론·학설·개념</h3><div class="theory-list">${theories.map(x=>`<span>${esc(x)}</span>`).join('')}</div></div>${formula?`<div class="lesson-section"><h3>공식·모형</h3><div class="formula-box">${esc(formula)}</div><p>기호를 그대로 외우지 말고 각 항의 의미, 단위 또는 논리적 관계, 성립조건과 실패조건을 설명할 수 있어야 합니다.</p></div>`:''}<div class="lesson-section"><h3>사례</h3><div class="case">${esc(caseText)}</div></div><div class="lesson-section"><h3>대표 원전·문헌</h3><ul class="reading-list">${readings.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div><div class="lesson-section"><h3>확인·연습</h3><div class="exercise"><ol><li>${esc(theories.slice(0,3).join(' · '))}를 서로 구별하여 자신의 말로 설명하라.</li>${formula?`<li>${esc(formula)}의 각 항과 적용조건을 설명하고 간단한 수치 또는 논리 예를 만들어라.</li>`:`<li>${esc(l[1])}이라는 명제의 핵심 전제와 한계를 각각 하나 이상 제시하라.</li>`}<li>${esc(caseText)} 사례를 수업 개념으로 단계적으로 분석하라.</li><li>대표문헌 중 하나의 관점에 가능한 반론 또는 대안설명을 제시하라.</li></ol></div></div><div class="lesson-section"><h3>AI Tutor</h3><div class="tutor-box"><p>정답 제시보다 개념설명 → 전제점검 → 새 사례 적용 → 반론 순으로 학습합니다.</p><button class="tutor-copy" data-prompt="${esc(prompt)}">Tutor 질문 복사</button></div></div><div class="actions"><button class="button complete-btn ${completed?'done':''}" data-complete="${key}">${completed?`${key} 완료됨`:`${key} 학습 완료`}</button></div></div></details>`;}
function renderRich(c,rich){const lessons=rich.lessons||[];const total=lessons.length;const storageKey=`nexus-university:${c.id}:completed`;const done=new Set(storageGet(storageKey));const meta=courseMeta(c,total,true);const modules=[0,1,2,3].map(i=>lessons.slice(i*3,i*3+3));document.title=`${c.id} ${c.title} | NEXUS UNIVERSITY`;app.innerHTML=`<header class="course-hero" id="top"><div class="course-hero-box"><div class="course-kicker"><span class="badge">${esc(c.id)}</span><span class="badge">${esc(domainLabels[c.domain]||c.domain)}</span><span class="badge">TEXTBOOK CORE 1.0</span></div><h1>${esc(c.title)}</h1><p class="course-subtitle">${esc(c.summary)}</p><div class="course-meta">${meta.map(x=>`<span>${esc(x)}</span>`).join('')}</div><div class="textbook-note">이 과목은 공통 자동생성 강의가 아니라 과목별 이론·원전·공식·사례·대표문헌을 별도로 구성한 University Core 교재화 과정입니다.</div></div></header>${progressBlock(c,total,done)}<section class="section"><div class="section-head"><h2>Course Overview</h2><span>TEXTBOOK CORE</span></div><p class="section-intro">${esc(rich.overview)}</p><div class="assessment"><h3>학습성과</h3><ol><li>${esc(c.title)}의 핵심 개념과 대표 이론을 정확히 구분해 설명한다.</li><li>원전·표준교재가 제시하는 대표 논증 또는 모형을 재구성한다.</li><li>공식·방법·자료의 적용조건과 한계를 판단한다.</li><li>사례에 개념을 적용하고 대안설명과 반론을 제시한다.</li><li>인접학문 및 현대 사회·AI 문제와 연결한 종합결론을 작성한다.</li></ol></div><div class="lesson-section"><h3>대표 원전·표준문헌</h3><div class="primary-texts">${(rich.texts||[]).map(x=>`<div class="primary-text">${esc(x)}</div>`).join('')}</div></div></section><nav class="toc">${modules.map((m,i)=>`<a href="#m${i+1}"><strong>Module ${i+1}</strong><span>${moduleTitles[i]} · L${String(i*3+1).padStart(2,'0')}–L${String(Math.min(i*3+3,total)).padStart(2,'0')}</span></a>`).join('')}</nav>${modules.map((m,mi)=>`<section class="module" id="m${mi+1}"><div class="module-head"><p class="eyebrow">MODULE ${String(mi+1).padStart(2,'0')}</p><h2>${moduleTitles[mi]}</h2><p>${esc(c.title)}의 ${mi===0?'기초 개념과 역사적·논리적 구조':mi===1?'핵심 이론·법칙·방법':mi===2?'사례 적용·검증·비판': '현대적 쟁점과 통합적 판단'}을 학습합니다.</p></div>${m.map((l,j)=>richLesson(c,l,mi*3+j+1,done)).join('')}</section>`).join('')}<section class="section"><div class="section-head"><h2>Final Assessment & Capstone</h2><span>TEXTBOOK SYNTHESIS</span></div><div class="textbook-assessment"><div><strong>개념시험</strong><span>대표 개념과 이론 8개를 정의하고 서로의 차이를 설명합니다.</span></div><div><strong>원전 비교</strong><span>대표문헌 2개를 선택해 문제설정·방법·결론·한계를 비교합니다.</span></div><div><strong>사례분석</strong><span>새로운 현실 사례에 이론·공식·증거·반론을 적용합니다.</span></div></div><div class="assessment" style="margin-top:7px"><h3>Capstone</h3><p>${esc(`${c.title}의 핵심 개념과 대표문헌을 사용해 하나의 현대 문제를 선택하고, 문제정의 → 이론 → 자료·모형 → 사례 → 반론 → 한계 → 종합결론의 순서로 학술적 분석노트를 작성합니다.`)}</p></div></section>`;bindProgress(c,total,storageKey,done);}
function genericPlan(c){const key=c.domain==='humanities'?'humanitites':c.domain;const titles=genericBlueprints[key]||genericBlueprints.core;return titles.map((title,i)=>({n:i+1,title,note:`${c.title}에서 ${title}의 의미·방법·적용범위를 학습한다.`}));}
function renderGeneric(c){const lessons=genericPlan(c);const total=12;const storageKey=`nexus-university:${c.id}:completed`;const done=new Set(storageGet(storageKey));const modules=[0,1,2,3].map(i=>lessons.slice(i*3,i*3+3));const meta=courseMeta(c,total,false);document.title=`${c.id} ${c.title} | NEXUS UNIVERSITY`;app.innerHTML=`<header class="course-hero"><div class="course-hero-box"><div class="course-kicker"><span class="badge">${esc(c.id)}</span><span class="badge">${esc(domainLabels[c.domain]||c.domain)}</span><span class="badge">COURSE MODEL 1.0</span></div><h1>${esc(c.title)}</h1><p class="course-subtitle">${esc(c.summary)}</p><div class="course-meta">${meta.map(x=>`<span>${esc(x)}</span>`).join('')}</div></div></header>${progressBlock(c,total,done)}<section class="section"><div class="assessment"><h3>학습성과</h3><ol><li>${esc(c.title)}의 핵심개념을 설명한다.</li><li>대표 방법과 사례를 분석한다.</li><li>실제 문제에 적용하고 반론을 제시한다.</li><li>인접학문과 AI·사회적 연결점을 설명한다.</li></ol></div></section>${modules.map((m,mi)=>`<section class="module"><div class="module-head"><p class="eyebrow">MODULE ${String(mi+1).padStart(2,'0')}</p><h2>${moduleTitles[mi]}</h2></div>${m.map(l=>{const key=`L${String(l.n).padStart(2,'0')}`;const completed=done.has(key);const prompt=`${c.id} ${c.title} ${key} ${l.title}을 공부 중이다. 정답을 먼저 주지 말고 핵심 개념을 내가 설명하게 한 뒤 반례와 실제 사례를 질문해 줘.`;return `<details class="lesson ${completed?'completed':''}"><summary><span class="lesson-no">${key}</span><span class="lesson-title"><strong>${esc(l.title)}</strong><span>${esc(l.note)}</span></span><span class="lesson-check">${completed?'완료':'미완료'}</span></summary><div class="lesson-body"><div class="lesson-section"><h3>본강의</h3><p>${esc(`${l.note} 이 단계에서는 정의·대표 원리·자료 또는 사례를 구분하고, 무엇이 성립조건인지와 무엇이 예외인지 확인한다.`)}</p></div><div class="lesson-section"><h3>확인·연습</h3><div class="exercise"><ol><li>${esc(l.title)}을 자신의 말로 설명하라.</li><li>${esc(c.title)}의 실제 사례 하나에 적용하라.</li><li>적용이 실패할 조건 또는 반론을 제시하라.</li></ol></div></div><div class="lesson-section"><h3>AI Tutor</h3><div class="tutor-box"><p>개념설명과 사례적용을 질문 방식으로 훈련합니다.</p><button class="tutor-copy" data-prompt="${esc(prompt)}">Tutor 질문 복사</button></div></div><div class="actions"><button class="button complete-btn ${completed?'done':''}" data-complete="${key}">${completed?`${key} 완료됨`:`${key} 학습 완료`}</button></div></div></details>`;}).join('')}</section>`).join('')}<section class="section"><div class="assessment"><h3>Final Assessment</h3><p>${esc(`${c.title}의 개념·방법·사례·반론을 연결한 종합 분석과제를 작성합니다. 이 과목은 다음 순차 교재화 단계에서 전용 원전·공식·사례·문헌 데이터로 강화됩니다.`)}</p></div></section>`;bindProgress(c,total,storageKey,done);}
function bindProgress(c,total,storageKey,done){function refresh(){const txt=document.getElementById('progressText');const bar=document.getElementById('progressBar');if(txt)txt.textContent=`${done.size} / ${total} Lessons`;if(bar)bar.style.width=`${(done.size/total)*100}%`;}app.addEventListener('click',async e=>{const t=e.target.closest('.tutor-copy');if(t){await copyText(t.dataset.prompt||'');showToast('AI Tutor 질문을 복사했습니다.');return;}const b=e.target.closest('.complete-btn');if(!b)return;const k=b.dataset.complete;if(done.has(k)){done.delete(k);b.classList.remove('done');b.textContent=`${k} 학습 완료`;b.closest('.lesson')?.classList.remove('completed');const chk=b.closest('.lesson')?.querySelector('.lesson-check');if(chk)chk.textContent='미완료';}else{done.add(k);b.classList.add('done');b.textContent=`${k} 완료됨`;b.closest('.lesson')?.classList.add('completed');const chk=b.closest('.lesson')?.querySelector('.lesson-check');if(chk)chk.textContent='완료';}storageSet(storageKey,[...done]);refresh();});refresh();}
if(!course){app.innerHTML='<section class="section"><div class="assessment"><h3>강좌를 찾을 수 없습니다.</h3><p>University 목록에서 다시 선택해 주세요.</p><a class="button" href="./">University로 돌아가기</a></div></section>';return;}
const rich=textbook[course.id];if(rich)renderRich(course,rich);else renderGeneric(course);
})();
