(()=>{'use strict';
const cur=window.NEXUS_CURRICULUM||{};const textbook=window.NEXUS_CORE_TEXTBOOK||{};const reg=window.NEXUS_QA_REGISTER||{batches:[],verified:{}};
const $=s=>document.querySelector(s);const esc=(v='')=>String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const courses=cur.all||[];const courseMap=new Map(courses.map(c=>[c.id,c]));const issues=[];const lessonRows=[];const bodyMap=new Map();const crossTitleMap=new Map();
const verified=reg.verified||{};const reviewedKey='nexus-university:qa-reviewed';let reviewed=new Set();try{reviewed=new Set(JSON.parse(localStorage.getItem(reviewedKey)||'[]'))}catch{}
const issueMeta={STRUCTURE:['구조','critical'],SOURCE_MISSING:['문헌 누락','high'],SOURCE_DETAIL:['출처 상세화','medium'],DUP_TITLE:['중복 Lesson','high'],DUP_BODY:['본문 중복','high'],PREREQ_INVALID:['선수과목 오류','critical'],PREREQ_CYCLE:['선수과목 순환','critical'],PREREQ_REVIEW:['선수과목 검토','medium'],ASSESSMENT:['평가 난이도','medium'],LINK:['Course 연결','low']};
function norm(v){return String(v||'').toLowerCase().replace(/\s+/g,'').replace(/[\p{P}\p{S}]/gu,'').trim()}
function levelNum(v){const n=Number(v);return Number.isFinite(n)?n:0}
function isAdvanced(c){const n=levelNum(c.level);return n>=300||(n>=3&&n<10)}
function add(type,c,lesson,message,detail=''){const [label,severity]=issueMeta[type]||[type,'medium'];const lessonKey=lesson?`L${String(lesson).padStart(2,'0')}`:'';const key=`${type}:${c?.id||'GLOBAL'}:${lessonKey}:${norm(message).slice(0,80)}`;issues.push({key,type,label,severity,course:c?.id||'',title:c?.title||'',domain:c?.domain||'',lesson:lessonKey,message,detail});}
function genericRef(x){const s=String(x||'').trim();if(!s)return true;if(s.length<7)return true;return /^(표준교재|대표문헌|대표연구|관련문헌|관련법령|관련규정|관련표준|가이드라인|원전|교과서|주요 논문|주요 연구)$/i.test(s)}
function sourceKinds(c,l){const all=[l[0],l[1],...(l[2]||[]),l[3],l[4],...(l[5]||[])].join(' ');const kinds=[];if(l[3])kinds.push('공식·모형');if(/조문|판례|법률|헌법|민법|형법|Regulation|Directive|\bAct\b|Court| v\. /i.test(all))kinds.push('법령·판례');if(/ISO|IEC|IEEE|NIST|ASTM|\bKS\b|RFC|WCAG|ASHRAE|AISC|ACI|ASCE/i.test(all))kinds.push('표준·규격');if(['humanities','theology'].includes(c.domain)||/^PHI-/.test(c.id))kinds.push('원전·사료');if(['social','medicine'].includes(c.domain))kinds.push('경험연구·근거');if(/BIB|BLG|SYS|CHH|JRS/.test(c.id))kinds.push('본문·사본·원어');return [...new Set(kinds)]}
function tier(c){const n=levelNum(c.level);if(n>=500||n>=5&&n<10)return 'T4 · Synthesis/Defense';if(n>=400||n===4)return 'T3 · Evaluation/Design';if(n>=300||n===3)return 'T2 · Analysis/Application';return 'T1 · Foundation/Explanation'}
for(const c of courses){const rich=textbook[c.id];const lessons=rich?.lessons||[];const required=c.required||[],recommended=c.recommended||[];
 if(!rich)add('STRUCTURE',c,0,'교재 데이터가 없습니다.');
 if(lessons.length!==12)add('STRUCTURE',c,0,`Lesson 수 ${lessons.length}/12`);
 const localTitles=new Map();const localBodies=new Map();let genericRefs=0;let readingTotal=0;let uniqueRefs=new Set();
 lessons.forEach((l,i)=>{const n=i+1,title=String(l?.[0]||''),body=String(l?.[1]||''),concepts=Array.isArray(l?.[2])?l[2]:[],formula=String(l?.[3]||''),application=String(l?.[4]||''),readings=Array.isArray(l?.[5])?l[5]:[];const lk=`${c.id}-L${String(n).padStart(2,'0')}`;
  const structural=[];if(!title)structural.push('제목');if(body.length<100)structural.push('본강의');if(concepts.length<2)structural.push('핵심개념');if(application.length<20)structural.push('사례·적용');if(structural.length)add('STRUCTURE',c,n,`${structural.join('·')} 보강 필요`,`본문 ${body.length}자 · 개념 ${concepts.length}개 · 적용 ${application.length}자`);
  if(!readings.length)add('SOURCE_MISSING',c,n,'대표 원전·문헌이 비어 있습니다.');
  readings.forEach(r=>{readingTotal++;uniqueRefs.add(norm(r));if(genericRef(r))genericRefs++});
  if(readings.some(genericRef))add('SOURCE_DETAIL',c,n,'대표문헌 중 서지사항이 지나치게 일반적인 항목이 있습니다.',readings.filter(genericRef).join(' · '));
  const nt=norm(title);if(nt){if(localTitles.has(nt))add('DUP_TITLE',c,n,`동일 Course 안에서 Lesson 제목이 중복됩니다.`,`${localTitles.get(nt)} ↔ L${String(n).padStart(2,'0')} ${title}`);else localTitles.set(nt,`L${String(n).padStart(2,'0')}`)}
  let sig=norm(body.replaceAll(c.title||'','').replaceAll(title,''));if(sig.length>120){sig=sig.slice(0,260);const arr=bodyMap.get(sig)||[];arr.push({course:c.id,lesson:n,title});bodyMap.set(sig,arr);const prev=localBodies.get(sig);if(prev)add('DUP_BODY',c,n,'동일 Course 안에서 본강의 문장구조가 사실상 동일합니다.',`${prev} ↔ L${String(n).padStart(2,'0')}`);else localBodies.set(sig,`L${String(n).padStart(2,'0')}`)}
  lessonRows.push({key:lk,course:c.id,title:c.title,domain:c.domain,department:c.department,lesson:n,lessonTitle:title,readings:readings.length,formula:!!formula,sourceKinds:sourceKinds(c,l),verified:!!verified[lk],tier:tier(c)});
 });
 if(readingTotal>=12&&uniqueRefs.size<=3)add('SOURCE_DETAIL',c,0,'Course 전체의 대표문헌 다양성이 낮습니다.',`총 ${readingTotal}회 표기 · 고유 문헌 ${uniqueRefs.size}개`);
 for(const p of [...required,...recommended]){if(!courseMap.has(p))add('PREREQ_INVALID',c,0,`존재하지 않는 선수·권장과목 코드 ${p}`);if(p===c.id)add('PREREQ_INVALID',c,0,'자기 자신을 선수과목으로 참조합니다.')}
 if(isAdvanced(c)&&required.length===0&&recommended.length===0)add('PREREQ_REVIEW',c,0,'고급과목인데 명시된 Required/Recommended prerequisite가 없습니다.',`Level ${c.level}`);
 add('ASSESSMENT',c,0,`${tier(c)} 기준으로 시험·과제·Capstone 수동 난이도 교정이 필요합니다.`);
 const ct=norm(c.title);if(ct){const arr=crossTitleMap.get(ct)||[];arr.push(c);crossTitleMap.set(ct,arr)}
}
// prerequisite cycle
const color=new Map();const stack=[];function dfs(id){color.set(id,1);stack.push(id);const c=courseMap.get(id);for(const p of (c?.required||[])){if(!courseMap.has(p))continue;if(color.get(p)===1){const idx=stack.indexOf(p);const cycle=stack.slice(idx).concat(p);add('PREREQ_CYCLE',c,0,'Required prerequisite 순환이 발견되었습니다.',cycle.join(' → '));}else if(!color.get(p))dfs(p)}stack.pop();color.set(id,2)}courses.forEach(c=>{if(!color.get(c.id))dfs(c.id)});
// exact/template duplicate clusters across courses
for(const arr of bodyMap.values()){const distinct=new Set(arr.map(x=>x.course));if(distinct.size>1&&arr.length>1){const first=courseMap.get(arr[0].course);add('DUP_BODY',first,arr[0].lesson,`서로 다른 Course에서 본강의 템플릿 중복 후보 ${arr.length}건`,`예: ${arr.slice(0,5).map(x=>`${x.course}-L${String(x.lesson).padStart(2,'0')}`).join(' · ')}`)}}
let linkCandidates=0;for(const arr of crossTitleMap.values()){if(arr.length>1){linkCandidates+=arr.length;for(const c of arr)add('LINK',c,0,'동일·유사 과목명이 다른 학과에 존재합니다. 지식 연결 검토가 필요합니다.',arr.filter(x=>x.id!==c.id).map(x=>`${x.id} ${x.department}`).join(' · '))}}
const severityRank={critical:0,high:1,medium:2,low:3};issues.sort((a,b)=>severityRank[a.severity]-severityRank[b.severity]||a.course.localeCompare(b.course)||a.lesson.localeCompare(b.lesson));
const verifiedCount=lessonRows.filter(x=>x.verified).length;const sourceQueue=lessonRows.filter(x=>x.sourceKinds.length&&!x.verified).length;const structuralCount=issues.filter(x=>x.type==='STRUCTURE').length;const duplicateCount=issues.filter(x=>x.type==='DUP_TITLE'||x.type==='DUP_BODY').length;const prereqCount=issues.filter(x=>x.type.startsWith('PREREQ')).length;
window.NEXUS_QA_RESULT={courses:courses.length,lessons:lessonRows.length,issues,lessonRows,verifiedCount,sourceQueue,structuralCount,duplicateCount,prereqCount,linkCandidates};
function metric(label,value,sub=''){return `<div class="qa-metric"><span>${esc(label)}</span><strong>${esc(value)}</strong>${sub?`<small>${esc(sub)}</small>`:''}</div>`}
function renderMetrics(){const host=$('#qaMetrics');host.innerHTML=[metric('Courses',courses.length,'expected 496'),metric('Lessons',lessonRows.length,'expected 5,952'),metric('Structural Flags',structuralCount),metric('Source Verify Queue',sourceQueue),metric('Duplicate Flags',duplicateCount),metric('Prerequisite Flags',prereqCount),metric('Source Verified',`${verifiedCount} / ${lessonRows.length}`),metric('Cross-course Links',linkCandidates)].join('')}
function renderBatches(){const host=$('#qaBatches');host.innerHTML=(reg.batches||[]).map(b=>`<div class="qa-batch ${String(b.status).toLowerCase()}"><div><strong>${esc(b.id)} · ${esc(b.title)}</strong><span>${b.courses} Courses · ${b.lessons} Lessons</span></div><p>${esc(b.scope)}</p><em>${esc(b.status)}</em></div>`).join('')}
const filterType=$('#qaType'),filterDomain=$('#qaDomain'),search=$('#qaSearch'),list=$('#qaIssues'),count=$('#qaCount');
function renderIssues(){const t=filterType.value,d=filterDomain.value,q=search.value.trim().toLowerCase();const rows=issues.filter(x=>(!t||x.type===t)&&(!d||x.domain===d)&&(!q||`${x.course} ${x.title} ${x.lesson} ${x.message} ${x.detail}`.toLowerCase().includes(q)));count.textContent=`${rows.length} flags`;list.innerHTML=rows.slice(0,800).map(x=>{const done=reviewed.has(x.key);const href=x.course?`./course.html?id=${encodeURIComponent(x.course)}${x.lesson?'#'+x.lesson.toLowerCase():''}`:'#';return `<article class="qa-issue ${x.severity} ${done?'reviewed':''}"><div class="qa-issue-top"><span>${esc(x.label)}</span><strong>${esc(`${x.course}${x.lesson?' · '+x.lesson:''}`)}</strong><em>${esc(x.severity.toUpperCase())}</em></div><h3>${esc(x.title||x.message)}</h3><p>${esc(x.message)}</p>${x.detail?`<small>${esc(x.detail)}</small>`:''}<div class="qa-actions">${x.course?`<a href="${href}">강좌 열기</a>`:''}<button data-review="${esc(x.key)}">${done?'검토표시 해제':'검토함 표시'}</button></div></article>`}).join('')+(rows.length>800?`<p class="qa-limit">화면 성능을 위해 상위 800건만 표시합니다. 검색·필터로 범위를 좁히십시오.</p>`:'')}
function setupFilters(){const types=[...new Set(issues.map(x=>x.type))].sort();filterType.innerHTML='<option value="">전체 검수유형</option>'+types.map(t=>`<option value="${t}">${esc(issueMeta[t]?.[0]||t)}</option>`).join('');const domains=[...new Set(courses.map(c=>c.domain))].sort();filterDomain.innerHTML='<option value="">전체 분야</option>'+domains.map(d=>`<option value="${esc(d)}">${esc(d)}</option>`).join('');[filterType,filterDomain,search].forEach(el=>el.addEventListener(el===search?'input':'change',renderIssues));list.addEventListener('click',e=>{const b=e.target.closest('[data-review]');if(!b)return;const k=b.dataset.review;if(reviewed.has(k))reviewed.delete(k);else reviewed.add(k);localStorage.setItem(reviewedKey,JSON.stringify([...reviewed]));renderIssues()})}
function renderSourcePolicy(){const host=$('#qaPolicy');const p=reg.policy||{};host.innerHTML=`<div><strong>자동 구조점검</strong><p>${esc(p.automatic||'')}</p></div><div><strong>원자료 검증</strong><p>${esc(p.verified||'')}</p></div><div><strong>오류 수정·재검증</strong><p>${esc(p.revision||'')}</p></div>`}
renderMetrics();renderBatches();renderSourcePolicy();setupFilters();renderIssues();
const auto=$('#qaAutoStatus');if(auto)auto.textContent=lessonRows.length===5952&&courses.length===496?'1차 자동 전수스캔 실행됨':'데이터 수 불일치 · 우선 구조점검 필요';
})();