(()=>{'use strict';
const out=window.NEXUS_AI_TEXTBOOKS=window.NEXUS_AI_TEXTBOOKS||{};
const S=window.NEXUS_UNIVERSITY_UTILS.splitList;
function mk(id,focus,chapters,algorithms,maths,systems,papers,failures,readings,lab){
 const ch=S(chapters),al=S(algorithms),ma=S(maths),sy=S(systems),pa=S(papers),fa=S(failures),rd=S(readings),lb=S(lab);
 out[id]={kind:'ai',focus,readings:rd,lessons:Array.from({length:12},(_,i)=>{
  const title=ch[i]||`${focus} 심화 ${i+1}`, a=al[i%Math.max(al.length,1)]||'구조적 문제분해', m=ma[i%Math.max(ma.length,1)]||'복잡도·오차 분석', s=sy[i%Math.max(sy.length,1)]||'표준 시스템 아키텍처', p=pa[i%Math.max(pa.length,1)]||'대표 기술문헌', f=fa[i%Math.max(fa.length,1)]||'성능저하·오류전파', l=lb[i%Math.max(lb.length,1)]||`${focus}의 최소 구현·검증 실습`;
  return {n:i+1,title,question:`${title}의 알고리즘·수학적 가정·시스템 구현·실패모드는 어떻게 연결되는가?`,algorithm:[a],math:[m],system:[s],papers:[p],failures:[f],
   lecture:[`${title}은 ${focus}의 구현을 구성하는 독립된 기술층이다. 먼저 입력과 출력, 상태, 목적함수 또는 불변조건을 명시하고, ${a}가 어떤 가정 아래 문제를 해결하는지 확인한다. 같은 기능을 내는 구현이라도 시간복잡도·공간복잡도·통신비용·수치안정성·확장성에 따라 실제 시스템에서의 선택은 달라진다.`,`수학적 분석에서는 ${m}을 중심으로 모델의 성질을 설명한다. 식 자체를 암기하기보다 각 항이 무엇을 뜻하는지, 어떤 조건에서 근사가 성립하는지, 파라미터 변화가 결과에 어떤 민감도를 만드는지 확인해야 한다. 경험적 성능지표와 이론적 보장은 서로 다른 수준의 주장임을 구분한다.`,`시스템 관점에서는 ${s}를 기준으로 데이터 흐름·메모리·연산·네트워크·저장·장애경계를 추적한다. 논문에서 제시된 알고리즘이 실제 서비스에 들어가면 캐시, 배치, 병렬화, 관측성, 보안, 비용 제약이 추가된다. 따라서 ${f} 같은 실패모드를 재현하고 탐지·완화·복구 절차까지 설계해야 기술을 이해했다고 볼 수 있다.`],
   lab:`기술실습: ${l}. ① 입력·출력과 평가기준을 정한다. ② ${a}의 최소 구현 또는 의사코드를 작성한다. ③ ${m}의 핵심 변수를 변화시키며 결과를 기록한다. ④ ${f}를 의도적으로 재현한다. ⑤ 로그·메트릭으로 원인을 추적하고 완화안을 비교한다.`,
   exercise:[`${a}의 핵심 단계와 계산복잡도를 설명하라.`,`${m}에서 변수 하나를 변화시켰을 때 결과가 어떻게 달라지는지 해석하라.`,`${p}의 핵심 기여와 한계, 그리고 ${f}와 연결되는 지점을 정리하라.`],
   tutor:`${id} ${focus} L${String(i+1).padStart(2,'0')} ${title}을 공부 중이다. 정답을 먼저 주지 말고 알고리즘→수학모형→시스템구조→실험설계→실패모드 순서로 한 단계씩 질문해 줘. 내가 식을 쓰면 차원·가정·경계조건을 검사하고, 논문을 언급할 때는 제목·연도·핵심기여를 분리해 줘.`};
 })};
}
mk('CS-101','프로그래밍 I','계산과 프로그램|변수와 타입|조건문|반복문|함수|스코프|리스트와 배열|문자열|입출력|오류와 디버깅|테스트|작은 프로그램 설계','순차실행|분기|반복|함수호출|선형탐색|누적·집계','상태전이|불변식|O(n)|논리식|정수·부동소수 표현','인터프리터 실행모델|콜스택|메모리와 값|파일 I/O','Abelson & Sussman, SICP|Kernighan & Ritchie, The C Programming Language','off-by-one|무한루프|타입오류|입력검증 실패|부동소수 오차','SICP|Python/C 표준 문서','숫자 통계 프로그램|텍스트 빈도 계산기');
mk('CS-102','프로그래밍 II','추상화와 모듈|객체와 클래스|상속과 합성|인터페이스|예외처리|제네릭|함수형 프로그래밍|이터레이터|동시성 기초|파일·네트워크 API|테스트 설계|리팩터링','동적 디스패치|재귀|map/filter/reduce|producer-consumer|dependency injection','재귀관계|참조동등성|동시성 happens-before|복잡도','객체모델|모듈시스템|스레드·이벤트루프|패키지관리','Gamma et al., Design Patterns|Martin Fowler, Refactoring','공유가변상태|예외누락|자원누수|상속 오용|race condition','Design Patterns|Refactoring','작은 REST 클라이언트|동시 작업큐');
mk('CS-103','자료구조','배열·동적배열|연결리스트|스택·큐|해시테이블|트리|이진검색트리|힙|그래프|트라이|Union-Find|자료구조 선택|성능실험','amortized array growth|hashing|tree traversal|heapify|BFS/DFS|path compression','O(1), O(log n), O(n)|load factor α=n/m|amortized analysis|트리 높이','메모리 레이아웃|포인터·참조|캐시 지역성','Cormen et al., Introduction to Algorithms|Tarjan, Efficiency of a Good But Not Linear Set Union Algorithm','해시충돌 폭증|편향트리|메모리 단편화|잘못된 자료구조 선택','CLRS|Sedgewick Algorithms','LRU 캐시 자료구조|그래프 인접리스트');
mk('CS-104','알고리즘','알고리즘 분석|분할정복|정렬|이진탐색|그리디|동적계획법|그래프 최단경로|최소신장트리|네트워크 플로|문자열 알고리즘|NP-완전성|근사·랜덤화','merge sort|binary search|Dijkstra|Kruskal/Prim|Bellman-Ford|Ford-Fulkerson|KMP|dynamic programming','T(n)=aT(n/b)+f(n)|Big-O/Theta/Omega|최단경로 최적부분구조|NP reduction','RAM model|priority queue 기반 그래프 처리|memoization','Dijkstra 1959|Cook 1971|Karp 1972|CLRS','음수간선에서 Dijkstra 실패|재귀폭발|그리디 반례|정수 overflow','CLRS|Kleinberg & Tardos, Algorithm Design','경로탐색 알고리즘 비교|배낭문제 DP');
mk('CS-105','컴퓨터구조','정보표현|논리게이트|명령어집합|CPU datapath|파이프라인|캐시|가상메모리|분기예측|멀티코어|SIMD·GPU|메모리 일관성|성능·전력 트레이드오프','two’s complement|pipelining|cache replacement|out-of-order execution|SIMD','Amdahl’s law S=1/((1-p)+p/s)|CPI|cache hit rate|memory bandwidth','ISA|CPU pipeline|cache hierarchy|NUMA|GPU SM','Patterson & Hennessy, Computer Organization and Design|Amdahl 1967','cache miss storm|branch misprediction|false sharing|spectre-class side channel','Patterson & Hennessy|Computer Architecture: A Quantitative Approach','캐시 크기와 성능 실험|벡터화 전후 비교');
mk('CS-106','운영체제','프로세스와 스레드|CPU 스케줄링|동기화|교착상태|가상메모리|파일시스템|I/O|보호와 권한|가상화|컨테이너|관측성|OS 성능분석','round-robin|mutex/semaphore|Banker’s algorithm|page replacement|copy-on-write','Little’s law L=λW|working set|queueing|race condition','kernel/user mode|scheduler|virtual memory|VFS|namespaces/cgroups','Dijkstra, Cooperating Sequential Processes|Tanenbaum, Modern Operating Systems','deadlock|priority inversion|thrashing|fd leak|container escape','OSTEP|Tanenbaum','producer-consumer 동기화|페이지 교체 시뮬레이션');
mk('CS-107','데이터베이스','관계모형|SQL|정규화|인덱스|트랜잭션|ACID|동시성 제어|복구|쿼리 최적화|분산 DB|NoSQL|데이터 일관성 설계','B+ tree|hash index|two-phase locking|MVCC|write-ahead logging|join algorithms','functional dependency|selectivity|cost model|serializability','query planner|buffer pool|WAL|replication|sharding','Codd 1970|Gray & Reuter, Transaction Processing|Spanner 2012','lost update|dirty read|hot shard|replica lag|schema drift','Database System Concepts|Designing Data-Intensive Applications','인덱스 전후 쿼리비용|MVCC 동시성 실험');
mk('CS-108','네트워크','계층모델|Ethernet·IP|라우팅|TCP|UDP|DNS|HTTP|TLS|혼잡제어|CDN|데이터센터 네트워크|네트워크 장애분석','Dijkstra routing|TCP congestion control|DNS resolution|TLS handshake','bandwidth-delay product|RTT|throughput≈window/RTT|queueing','OSI/TCP-IP|router|NAT|load balancer|CDN','Cerf & Kahn 1974|Jacobson 1988 congestion avoidance','packet loss|bufferbloat|DNS outage|BGP leak|TLS misconfiguration','Kurose & Ross|Computer Networks by Tanenbaum','TCP 흐름 캡처|DNS·HTTP 지연 분석');
mk('CS-109','소프트웨어공학','요구사항|아키텍처|모듈성|API 설계|버전관리|테스트|CI/CD|코드리뷰|관측성|신뢰성|기술부채|대규모 시스템 진화','unit/integration/property testing|dependency inversion|blue-green deployment|feature flag','cyclomatic complexity|availability A=MTBF/(MTBF+MTTR)|SLO error budget','layered architecture|microservices|CI pipeline|telemetry','Parnas 1972|Brooks 1987 No Silver Bullet|Google SRE','요구사항 누락|coupling 폭증|flaky test|cascading failure|silent data corruption','Software Engineering at Google|Site Reliability Engineering','CI 파이프라인 설계|장애 postmortem 작성');
mk('CS-110','분산시스템','분산시스템 모델|시간과 순서|logical clocks|복제|합의|Raft|Paxos|CAP|분산트랜잭션|stream processing|fault tolerance|분산시스템 설계','Lamport clock|vector clock|Paxos|Raft|consistent hashing|two-phase commit','CAP trade-off|quorum R+W>N|logical time|failure detector','leader-follower replication|quorum|log replication|message queue','Lamport 1978|Lamport 1998 Paxos|Ongaro & Ousterhout 2014 Raft|Gilbert & Lynch 2002 CAP','split brain|network partition|clock skew|duplicate delivery|retry storm','Designing Data-Intensive Applications|Distributed Systems by van Steen & Tanenbaum','Raft 로그 시뮬레이션|중복메시지 idempotency 처리');
mk('CS-111','프로그래밍언어론','문법과 의미론|타입시스템|스코프와 바인딩|함수와 클로저|객체모델|메모리관리|정적·동적 타입|다형성|함수형 언어|논리형 언어|컴파일과 해석|언어설계','lambda calculus|type inference|garbage collection|pattern matching|unification','β-reduction|Hindley-Milner type inference|operational semantics','lexer/parser|AST|bytecode VM|JIT','Church lambda calculus|Milner 1978 polymorphism|Pierce, Types and Programming Languages','type unsoundness|memory unsafety|undefined behavior|GC pause','Types and Programming Languages|Crafting Interpreters','작은 인터프리터|타입검사기');
mk('DS-101','확률과 통계','확률공리|조건부확률|확률변수|분포|기댓값·분산|표본분포|추정|신뢰구간|가설검정|회귀|Bayesian 추론|통계적 의사결정','Bayes rule|maximum likelihood|bootstrap|linear regression','P(A|B)=P(B|A)P(A)/P(B)|E[X]|Var(X)|SE=s/√n|OLS β=(XᵀX)⁻¹Xᵀy','통계 계산 파이프라인|simulation','Fisher 1922|Neyman & Pearson 1933|Gelman et al., Bayesian Data Analysis','p-hacking|multiple testing|selection bias|confounding','OpenIntro Statistics|Bayesian Data Analysis','부트스트랩 신뢰구간|회귀 잔차분석');
mk('DS-102','데이터처리','데이터 형식|ETL|정제|결측치|중복|타입·스키마|조인|집계|시계열 처리|스트리밍|데이터 품질|재현 가능한 파이프라인','map/filter/reduce|hash join|sort-merge join|window aggregation','throughput|latency|completeness rate|duplicate rate','ETL/ELT|data lake|warehouse|stream processor','Dean & Ghemawat 2004 MapReduce|Kleppmann DDIA','schema drift|silent truncation|timezone 오류|중복이벤트|late data','DDIA|Pandas/Spark docs','원시 CSV→검증된 분석테이블|스트림 집계');
mk('DS-103','데이터베이스','관계형 모델|SQL 분석|정규화|인덱스|OLTP|OLAP|컬럼 저장|데이터웨어하우스|분산저장|쿼리계획|메타데이터|분석 데이터 모델','B+ tree|bitmap index|star schema|columnar scan','cost estimation|compression ratio|selectivity','RDBMS|warehouse|lakehouse|catalog','Codd 1970|Dremel 2010|Delta Lake papers','full table scan|skewed join|stale statistics|broken lineage','Database Systems|DDIA','별 스키마 설계|실행계획 비교');
mk('DS-104','데이터분석','EDA|요약통계|시각적 탐색|상관|그룹 비교|회귀|분류|군집|차원축소|시계열|실험분석|분석 보고서','linear/logistic regression|k-means|PCA|ARIMA','correlation r|logit p=1/(1+e^-z)|PCA eigenvectors','notebook→pipeline→report','Tukey, Exploratory Data Analysis|Pearson 1901 PCA','spurious correlation|data leakage|Simpson’s paradox|overfitting','Tukey EDA|ISLR','실제 공개데이터 EDA|재현 가능한 분석보고서');
mk('DS-105','통계적 추론','추정량|충분통계량|MLE|MAP|신뢰구간|검정력|likelihood ratio|다중검정|비모수검정|Bayesian posterior|causal inference 입문|불확실성 전달','MLE|MAP|bootstrap|permutation test|Benjamini-Hochberg','L(θ|x)|posterior∝likelihood×prior|power=1-β|FDR','simulation-based inference','Neyman 1937|Benjamini & Hochberg 1995|Rubin causal model','underpowered study|optional stopping|prior sensitivity|model misspecification','Casella & Berger|Gelman BDA','검정력 시뮬레이션|Bayesian posterior 비교');
mk('DS-106','데이터시각화','그래픽 인코딩|척도|분포 시각화|비교|관계|불확실성|고차원|지도|대시보드|상호작용|접근성|시각화 윤리','binning|kernel density|coordinate transform|small multiples','perceptual error|confidence interval encoding','visualization grammar|dashboard architecture','Cleveland & McGill 1984|Wilkinson Grammar of Graphics','잘린 축|면적왜곡|rainbow colormap|과도한 집계|확신구간 누락','The Visual Display of Quantitative Information|Fundamentals of Data Visualization','같은 데이터의 정직/오해 그래프 비교');
mk('DS-107','빅데이터','분산처리 개념|MapReduce|Spark DAG|파티셔닝|셔플|컬럼저장|스트리밍|메시지큐|lakehouse|대규모 ML|비용 최적화|신뢰성','MapReduce|consistent hashing|Spark transformations|stream window','speedup|shuffle cost|data skew|throughput','HDFS/S3|Spark|Kafka|lakehouse','Dean & Ghemawat 2004|Zaharia et al. Spark 2010|Kafka paper','data skew|executor OOM|small file problem|backpressure|duplicate event','DDIA|Spark docs','대용량 group-by 파티셔닝|stream backpressure 재현');
mk('DS-108','데이터거버넌스','데이터 자산|소유자·책임자|메타데이터|데이터 카탈로그|품질규칙|lineage|접근통제|보존·삭제|개인정보|모델 데이터셋|감사|거버넌스 운영','data classification|lineage graph|quality checks|RBAC/ABAC','completeness|accuracy|freshness|uniqueness','catalog|data contracts|policy engine','DAMA-DMBOK|NIST Privacy Framework','orphan dataset|권한과다|lineage 단절|학습데이터 provenance 부재','DAMA-DMBOK|NIST Privacy Framework','AI 학습데이터셋 등록·승인 워크플로');
mk('AI-101','AI 개론','지능형 에이전트|상태공간|탐색|지식표현|확률추론|머신러닝|신경망|NLP·비전|강화학습|생성모델|AI 안전|AI 시스템 종합','BFS/DFS/A*|Bayes inference|gradient descent|Q-learning','f(n)=g(n)+h(n)|Bayes rule|loss minimization|Bellman equation','agent-perception-action loop|model pipeline','Russell & Norvig, AIMA|Turing 1950','state explosion|distribution shift|reward hacking|hallucination','AIMA|Deep Learning','미니 grid-world agent|간단 분류기');
mk('AI-102','탐색과 문제해결','문제정의|BFS|DFS|uniform-cost|휴리스틱|A*|local search|constraint satisfaction|game tree|minimax|Monte Carlo tree search|탐색 설계','BFS|DFS|Dijkstra/UCS|A*|hill climbing|minimax|MCTS','f(n)=g(n)+h(n)|branching factor b|O(b^d)|admissible heuristic','frontier/explored set|priority queue|game engine','Hart, Nilsson & Raphael 1968 A*|Kocsis & Szepesvári 2006 UCT','휴리스틱 과대평가|loop|combinatorial explosion|horizon effect','AIMA','8-puzzle A*|틱택토 minimax');
mk('AI-103','지식표현과 추론','명제논리|1차논리|추론규칙|Horn clause|규칙기반 시스템|온톨로지|description logic|지식그래프|비단조추론|상식추론|신경-기호 결합|KR 종합','resolution|forward/backward chaining|unification|graph traversal','P→Q, P ⊢ Q|first-order quantification|subsumption','rule engine|knowledge graph|ontology reasoner','McCarthy 1959 Programs with Common Sense|Newell & Simon symbolic AI','knowledge incompleteness|rule conflict|ontology mismatch|combinatorial inference','AIMA|Knowledge Representation by Brachman & Levesque','작은 규칙기반 진단기|RDF 지식그래프');
mk('AI-104','머신러닝','학습문제와 데이터|선형회귀|로지스틱회귀|k-NN|decision tree|ensemble|SVM|regularization|validation|class imbalance|calibration|ML pipeline','gradient descent|decision tree splitting|random forest|SVM|cross-validation','MSE|cross-entropy|L1/L2|margin|precision/recall/F1|ROC-AUC','feature pipeline|training/evaluation serving','Vapnik SVM|Breiman 2001 Random Forests','overfitting|data leakage|imbalance|concept drift|miscalibration','Bishop PRML|Hastie Tibshirani Friedman ESL','분류모델 비교|교차검증·calibration');
mk('AI-105','딥러닝','퍼셉트론|MLP|backpropagation|optimization|CNN|RNN/LSTM|attention|normalization|regularization|representation learning|scaling|deep learning system','backprop|SGD/Adam|convolution|LSTM|attention','∂L/∂w chain rule|Adam moments|softmax|cross-entropy','GPU training loop|autodiff graph|checkpointing','Rumelhart et al. 1986|LeCun et al. 1998|Kingma & Ba 2014 Adam|Vaswani et al. 2017','vanishing gradient|exploding gradient|overfit|OOM|unstable training','Goodfellow et al., Deep Learning','CNN 이미지분류|학습률 실험');
mk('AI-106','확률적 AI','확률모델|Bayesian network|Markov model|HMM|Kalman filter|particle filter|MDP|POMDP|variational inference|MCMC|uncertainty|probabilistic decision','variable elimination|Viterbi|Kalman filter|particle filtering|MCMC','Bayes rule|Markov property|Kalman update|ELBO|expected utility','probabilistic graphical model|state estimator','Pearl 1988|Kalman 1960|Jordan et al. graphical models','model misspecification|particle degeneracy|posterior collapse|uncalibrated uncertainty','Kevin Murphy, Probabilistic Machine Learning|Pearl, Probabilistic Reasoning','HMM 시퀀스 추론|Kalman tracking');
mk('AI-107','자연어처리','토큰화|언어모델|n-gram|word embeddings|RNN/LSTM|attention|Transformer|pretraining|sequence-to-sequence|information retrieval|evaluation|LLM NLP','BPE|word2vec|beam search|Transformer attention|BM25','P(w1…wn)=∏P(wi|context)|cosine similarity|attention(Q,K,V)=softmax(QKᵀ/√d)V|perplexity','tokenizer→encoder/decoder→serving','Mikolov et al. 2013 word2vec|Vaswani et al. 2017|Devlin et al. 2018 BERT','tokenization bias|hallucination|context truncation|benchmark contamination','Jurafsky & Martin, Speech and Language Processing','BPE 구현|문서검색+생성 비교');
mk('AI-108','컴퓨터비전','영상표현|필터·에지|feature|CNN|classification|object detection|segmentation|metric learning|vision transformer|self-supervised vision|multimodal vision|vision robustness','Sobel/Canny|convolution|NMS|IoU matching|ViT patch attention','2D convolution|IoU=|A∩B|/|A∪B||cross-entropy|mAP','image pipeline|detector|segmenter|multimodal encoder','Krizhevsky et al. 2012 AlexNet|He et al. 2015 ResNet|Dosovitskiy et al. 2020 ViT','adversarial example|domain shift|small-object miss|dataset bias','Szeliski, Computer Vision','작은 CNN|검출 threshold와 mAP');
mk('AI-109','AI Planning','계획문제|STRIPS|forward/backward planning|heuristic planning|partial-order planning|planning graph|temporal planning|resource constraints|stochastic planning|HTN|LLM planning|계획 검증','STRIPS|Graphplan|A* planning|HTN','state transition|heuristic relaxed plan|expected cost','planner|world model|tool executor','Fikes & Nilsson 1971 STRIPS|Blum & Furst 1997 Graphplan','invalid action|state mismatch|long-horizon compounding|tool side effect','AIMA|Automated Planning by Ghallab et al.','블록월드 planner|도구호출 계획 검증');
mk('AI-110','AI Agents','에이전트 구조|관찰·행동|reactive agent|deliberative agent|memory|tool use|ReAct|reflection|planning-execution loop|permissions|evaluation|agent system design','ReAct|tool routing|memory retrieval|plan-and-execute','expected utility|success rate|cost per task|trajectory length','LLM→planner→tools→memory→guardrails','Yao et al. 2022 ReAct|Schick et al. 2023 Toolformer','tool misuse|looping|prompt injection|memory poisoning|unbounded action','AIMA|ReAct paper|Toolformer','파일·검색 도구 agent sandbox|trajectory 평가');
mk('AI-111','생성형 AI','생성모형 개요|autoregressive model|VAE|GAN|diffusion|Transformer LM|conditioning|sampling|prompting|RAG|evaluation|생성시스템 안전','next-token prediction|VAE reparameterization|GAN minimax|diffusion denoising|top-k/top-p sampling','ELBO|GAN minmax|p(x)=∏p(xt|x<t)|diffusion noise schedule','generator|retriever|sampler|safety filter','Kingma & Welling 2013 VAE|Goodfellow et al. 2014 GAN|Ho et al. 2020 DDPM|Lewis et al. 2020 RAG','mode collapse|hallucination|prompt injection|memorization|unsafe generation','Deep Generative Modeling|RAG paper','작은 RAG|sampling temperature 비교');
mk('AI-112','Foundation Models','스케일과 사전학습|데이터 믹스|Transformer scaling|self-supervision|instruction tuning|RLHF|in-context learning|emergent behavior 논쟁|multimodal foundation|fine-tuning·PEFT|evaluation|foundation model governance','pretraining|instruction tuning|RLHF|LoRA|mixture-of-experts','scaling laws L(N,D,C)|cross-entropy|KL penalty|low-rank ΔW=BA','distributed pretraining|model serving|adapter stack','Kaplan et al. 2020 Scaling Laws|Bommasani et al. 2021 Foundation Models|Ouyang et al. 2022 InstructGPT|Hu et al. 2021 LoRA','data contamination|capability overhang|alignment tax|catastrophic forgetting|serving cost','Stanford Foundation Models report|InstructGPT|LoRA','LoRA 미세조정 설계|벤치마크 contamination 점검');
mk('AI-113','Agentic AI','agentic workflow|goal decomposition|planner-executor|tool discovery|memory|long-horizon tasks|self-correction|computer use|multi-tool transactions|sandboxing|agent evaluation|책임가능한 agent architecture','ReAct|plan-and-execute|reflection|function calling|workflow DAG','task success|expected cost|risk-weighted utility|trajectory entropy','planner→policy→tool gateway→memory→monitor→rollback','Yao et al. ReAct|Shinn et al. 2023 Reflexion|Park et al. 2023 Generative Agents','goal drift|privilege escalation|prompt injection|irreversible action|retry amplification|hidden state corruption','Agentic systems research|NIST AI RMF','메일·캘린더·결제 agent를 최소권한 sandbox로 구성');
mk('AI-114','Multi-Agent Systems','다중에이전트 개념|협력·경쟁|game theory|distributed coordination|communication protocols|task allocation|consensus|auctions|emergence|multi-agent RL|security·collusion|MAS governance','contract net|consensus|auction mechanisms|MARL|message passing','Nash equilibrium|social welfare ΣUi|consensus update xi(t+1)=Σwijxj(t)|credit assignment','agent registry|message bus|shared environment|coordinator','Wooldridge, MultiAgent Systems|Smith 1980 Contract Net|Lowe et al. 2017 MADDPG','emergent collusion|deadlock|miscommunication|credit assignment failure|cascading delegation','Wooldridge|MARL literature','협상 agent 3개 시뮬레이션|창발적 실패 로그 분석');
mk('ROB-101','로봇공학','좌표계|강체변환|운동학|역운동학|동역학|센서|상태추정|제어|경로계획|매니퓰레이션|안전|로봇시스템 통합','forward kinematics|inverse kinematics|Jacobian|PID|A*','homogeneous transform|q̇=J⁻¹ẋ|τ=M(q)q̈+C+g','sense→estimate→plan→control→act','Craig, Introduction to Robotics|Siciliano et al. Robotics','singularity|sensor noise|collision|control instability|actuator saturation','Craig|Probabilistic Robotics','2-link arm IK|PID joint control');
mk('ROB-102','센서','센서 물리|카메라|LiDAR|radar|IMU|encoder|GPS|캘리브레이션|센서융합|시간동기화|오류모델|센서 안전','camera projection|range measurement|IMU integration|sensor fusion','pinhole x=fX/Z|bias+noise model|covariance','camera/LiDAR/IMU stack|timestamp pipeline','Hartley & Zisserman|sensor fusion literature','bias drift|miscalibration|occlusion|multipath|timestamp skew','Probabilistic Robotics|Multiple View Geometry','IMU drift 측정|카메라 캘리브레이션');
mk('ROB-103','제어','피드백|안정성|PID|상태공간|controllability|LQR|observer|MPC|비선형제어|adaptive control|robust control|로봇 안전제어','PID|LQR|Kalman observer|MPC','ẋ=Ax+Bu|u=-Kx|PID u=Kpe+Ki∫e+Kdė','controller loop|plant|observer','Kalman 1960|LQR/control textbooks','oscillation|integral windup|model mismatch|delay instability','Åström & Murray, Feedback Systems','PID tuning|MPC constraint 실험');
mk('ROB-104','컴퓨터비전','카메라기하|feature|stereo|optical flow|CNN|detection|segmentation|pose estimation|depth|tracking|robot vision|robustness','SIFT/ORB|stereo matching|optical flow|PnP|CNN detector','epipolar constraint xᵀFx’=0|reprojection error|IoU','camera→perception→tracking','Hartley & Zisserman|Szeliski','motion blur|lighting shift|occlusion|depth ambiguity','Multiple View Geometry|Computer Vision','feature matching|pose estimation');
mk('ROB-105','자율주행','자율주행 stack|센서융합|localization|HD map|perception|prediction|behavior planning|trajectory planning|vehicle control|simulation|safety case|edge cases','Kalman/particle filter|object tracking|Frenet planning|MPC','time-to-collision|kinematic bicycle model|risk metric','sensor→perception→prediction→planning→control','Paden et al. 2016 autonomous vehicle survey|Kalman/SLAM literature','phantom braking|occlusion|rare object|map error|handover failure','autonomous driving surveys|ISO 26262/SOTIF overview','cut-in 차량 시나리오 계획|센서 failure injection');
mk('ROB-106','SLAM','SLAM 문제|odometry|landmarks|EKF-SLAM|particle SLAM|graph SLAM|loop closure|visual SLAM|LiDAR SLAM|factor graph|map consistency|SLAM 실패분석','EKF-SLAM|FastSLAM|pose graph optimization|bundle adjustment','Bayes filtering|least squares minΣ||eij||²Σ⁻¹|covariance','front-end data association|back-end optimizer','Durrant-Whyte & Bailey 2006 SLAM|Thrun et al. Probabilistic Robotics','perceptual aliasing|loop closure false positive|drift|dynamic scene','Probabilistic Robotics|SLAM surveys','2D pose graph|loop closure 오류 재현');
mk('ROB-107','경로계획','configuration space|grid search|Dijkstra|A*|D*|sampling planning|RRT|RRT*|trajectory optimization|dynamic obstacles|multi-agent planning|planning safety','A*|D* Lite|RRT|RRT*|potential field','path cost|heuristic admissibility|sampling completeness','global planner|local planner|collision checker','LaValle, Planning Algorithms|Karaman & Frazzoli 2011 RRT*','local minima|narrow passage|dynamic obstacle|planning timeout','Planning Algorithms','RRT 장애물 회피|A*와 D* 비교');
mk('ROB-108','드론','비행역학|좌표계|IMU|자세추정|PID attitude|position control|GPS navigation|path planning|vision navigation|communications|battery·payload|drone safety','quaternion attitude|PID cascade|Kalman filter|waypoint planning','thrust/torque dynamics|quaternion|energy budget','flight controller|GNSS/IMU|telemetry','quadrotor control literature|PX4 architecture docs','GPS spoofing|wind|battery sag|motor failure|link loss','quadrotor dynamics texts|PX4 docs','시뮬레이터 waypoint flight|link-loss failsafe');
mk('ROB-109','휴머노이드','인체형 기구학|balance|center of mass|ZMP|walking|whole-body control|manipulation|vision-language action|force control|fall recovery|human interaction|humanoid safety','ZMP control|inverse dynamics|whole-body QP|motion retargeting','ZMP|centroidal dynamics|Jacobian|contact constraints','perception→whole-body planner→actuators','Vukobratović ZMP|whole-body control literature','fall|contact slip|self-collision|unexpected human contact|thermal limit','humanoid robotics literature','단순 biped balance simulation|contact constraint 분석');
mk('ROB-110','Physical AI','embodied intelligence|world models|sim-to-real|imitation learning|reinforcement learning|vision-language-action|affordance|dexterous manipulation|robot foundation model|data collection|safety|physical AI system','behavior cloning|domain randomization|RL|VLA policy','MDP return|policy gradient|domain gap metrics','simulation→training→robot deployment|teleoperation data','Sutton & Barto|RT-1/RT-2 papers|robot foundation model literature','sim2real gap|unsafe exploration|distribution shift|actuator damage|human proximity risk','Reinforcement Learning|robot foundation model papers','sim-to-real pick-and-place|safety envelope');
mk('SEC-101','정보보안','CIA triad|위협모델|인증|인가|접근통제|취약점|보안개발|악성코드|로그·탐지|사고대응|보안아키텍처|risk assessment','threat modeling|least privilege|secure hashing|defense in depth','risk≈likelihood×impact|entropy|false positive/negative','identity→policy→resource|SIEM/SOC','Saltzer & Schroeder 1975|NIST CSF','credential theft|privilege escalation|supply-chain attack|log blind spot','NIST CSF|Security Engineering by Ross Anderson','STRIDE threat model|incident tabletop');
mk('SEC-102','네트워크보안','네트워크 위협|방화벽|IDS/IPS|VPN|TLS|PKI|DNS security|DDoS|zero trust|segmentation|cloud network|network forensics','stateful filtering|signature/anomaly detection|TLS handshake|rate limiting','packet rate|entropy|false positive rate|key exchange','firewall→WAF→service mesh|zero-trust gateway','Diffie & Hellman 1976|TLS RFCs|NIST Zero Trust','MITM|DDoS|DNS poisoning|certificate misissue|lateral movement','NIST Zero Trust|Network Security texts','TLS packet capture|segment 침해 시나리오');
mk('SEC-103','암호학','보안목표|고전암호|대칭키|블록암호|해시|MAC|공개키|Diffie-Hellman|RSA|전자서명|키관리|현대 암호와 PQC','AES|SHA-2/3|HMAC|Diffie-Hellman|RSA|ECDSA','c=m^e mod n|HMAC|discrete log hardness|birthday bound','KMS|PKI|HSM','Shannon 1949|Diffie & Hellman 1976|Rivest Shamir Adleman 1978','nonce reuse|weak RNG|padding oracle|key leakage|algorithm deprecation','Boneh & Shoup, A Graduate Course in Applied Cryptography','RSA toy implementation|nonce reuse 분석');
mk('SEC-104','개인정보보호','privacy threat model|data minimization|consent|pseudonymization|anonymization|differential privacy|federated learning|secure aggregation|privacy attack|PII detection|privacy engineering|AI privacy','k-anonymity|differential privacy|secure aggregation|federated averaging','ε-differential privacy|re-identification risk|privacy budget','data inventory|privacy gateway|federated architecture','Dwork 2006 differential privacy|McMahan et al. 2017 FedAvg','membership inference|model inversion|re-identification|over-collection','NIST Privacy Framework|Differential Privacy literature','DP noise 실험|membership inference 개념실험');
mk('SEC-105','인간컴퓨터상호작용','사용자·과업|mental model|affordance|feedback|Fitts law|Hick-Hyman law|정보구조|프로토타이핑|usability testing|인지부하|AI interaction|HCI ethics','task analysis|think-aloud|A/B test|heuristic evaluation','Fitts MT=a+b log2(1+D/W)|Hick RT=a+b log2(n+1)','user→interface→system feedback loop','Card Moran Newell GOMS|Nielsen usability heuristics','automation surprise|dark pattern|mode error|overtrust','Designing with the Mind in Mind|HCI textbooks','사용성 테스트|AI 추천설명 UI 비교');
mk('SEC-106','접근성','장애와 접근성|WCAG 원칙|키보드 접근|스크린리더|색·대비|자막|인지 접근성|모바일 접근성|문서 접근성|테스트|AI 보조기술|포용적 설계','semantic HTML|focus management|contrast checking|captioning','contrast ratio|target size|error rate','assistive technology stack|accessibility tree','WCAG 2.2|WAI-ARIA','focus trap|unlabeled control|low contrast|auto-caption 오류','WCAG|Inclusive Design','키보드만으로 앱 점검|스크린리더 레이블 검사');
mk('SEC-107','사용자경험','UX research|journey map|persona|information architecture|interaction flow|prototype|usability metrics|experimentation|service blueprint|product analytics|AI UX|UX strategy','interview coding|task flow|A/B test|funnel analysis','SUS score|conversion|retention|time-on-task','research→design→test→measure loop','ISO 9241-210|Nielsen Norman research','metric gaming|selection bias|dark pattern|AI overtrust','Don Norman, Design of Everyday Things|Lean UX','AI 기능의 사용자여정·실패복구 설계');
mk('SEC-108','AI 안전','AI 위험분류|robustness|distribution shift|adversarial ML|alignment|reward hacking|red teaming|evals|guardrails|monitoring|incident response|safety case','adversarial training|RLHF/RLAIF|red teaming|conformal prediction|sandboxing','robust risk|max loss|calibration error|risk-weighted utility','model→policy→guardrail→monitor→response','Amodei et al. 2016 Concrete Problems in AI Safety|NIST AI RMF|adversarial ML literature','jailbreak|prompt injection|reward hacking|goal misgeneralization|model collapse|agent tool misuse','NIST AI RMF|AI safety papers','agent prompt-injection red team|safety eval suite');
mk('SEC-109','신뢰가능 AI','trustworthiness 속성|validity|reliability|fairness|transparency|explainability|privacy|security|accountability|human oversight|assurance|trustworthy AI case','calibration|SHAP/LIME|fairness metrics|model cards|audit logging','demographic parity|equalized odds|ECE calibration|confidence interval','governance→data→model→deployment→audit','NIST AI RMF|Mitchell et al. 2019 Model Cards|Gebru et al. 2021 Datasheets','fairness gerrymandering|explanation instability|metric mismatch|audit gap','NIST AI RMF|Model Cards|Datasheets for Datasets','모델카드 작성|공정성 지표 충돌 비교');
})();