(()=>{'use strict';
const out=window.NEXUS_ARTS_TEXTBOOKS=window.NEXUS_ARTS_TEXTBOOKS||{};
const S=s=>String(s||'').split('|').map(x=>x.trim()).filter(Boolean);
function mk(id,focus,topics,form,work,technique,movement,practice,critique,revision,readings){
 const tp=S(topics),fm=S(form),wk=S(work),tc=S(technique),mv=S(movement),pr=S(practice),cq=S(critique),rv=S(revision),rd=S(readings);
 out[id]={kind:'arts',focus,readings:rd,lessons:Array.from({length:12},(_,i)=>{const title=tp[i]||`${focus} 실습 ${i+1}`;return{n:i+1,title,form:[fm[i%fm.length]],work:[wk[i%wk.length]],technique:[tc[i%tc.length]],movement:[mv[i%mv.length]],practice:[pr[i%pr.length]],critique:[cq[i%cq.length]],revision:[rv[i%rv.length]],lecture:[`${title}은 ${focus}에서 형식과 제작을 분리하지 않는다. 먼저 ${fm[i%fm.length]}의 구조를 실제 작품에서 찾아보고, ${wk[i%wk.length]}를 분석하여 구성요소가 지각·정서·의미에 어떤 효과를 만드는지 설명한다.`,`제작 단계에서는 ${tc[i%tc.length]}을 직접 적용한다. 기법을 장식적 효과로 사용하는 것이 아니라 선택한 매체의 물리적·기술적 제약과 ${mv[i%mv.length]}의 역사적 맥락을 이해한 뒤 목적에 맞게 변형한다.`,`완성 후에는 ${cq[i%cq.length]} 기준으로 자기 작업을 비평하고 ${rv[i%rv.length]}을 수행한다. 첫 결과물을 최종작으로 간주하지 않고 의도와 실제 결과의 차이를 기록하면서 반복수정하는 것이 핵심이다.`],application:`창작·비평 과제: ${pr[i%pr.length]}. 결과물과 함께 형식 선택, 참고작품, 제작과정, 실패한 시도, 비평 피드백, 수정 전후의 차이를 기록하라.`};});}

mk('MUS-101','음악이론','음높이와 오선|리듬과 박자|음정|장·단음계|조표와 조성|삼화음|7화음|기능화성 입문|선율구조|악구와 종지|전조 입문|형식분석','notation|meter|interval|scale|key|triad|seventh chord|cadence|phrase|form','Bach chorales|Mozart sonatas|Beethoven themes|folk melodies','sight reading|interval identification|Roman numeral analysis|rhythmic dictation','tonal common practice|modal traditions|20th-century extensions','8마디 선율을 분석하고 재작성|4성부 화음진행 작성|리듬 변주 만들기','음정 정확성|박자 안정성|화성 기능|형식 명료성','voice-leading 수정|불필요한 반복 제거|종지 강화','Steven Laitz, The Complete Musician|Kostka, Payne & Almén, Tonal Harmony');
mk('MUS-102','화성학','3화음 연결|전위|비화성음|도미넌트7|감7화음|2차도미넌트|전조|차용화음|증6화음|나폴리6|크로매틱 화성|현대 화성확장','functional harmony|voice leading|chromatic harmony|tonicization','Bach chorales|Mozart K.545|Beethoven Op.13|Schubert songs|Debussy preludes','four-part writing|figured bass|Roman numerals|harmonic reduction','Baroque|Classical|Romantic|Impressionism|Jazz extensions','주어진 베이스에 4성부 화성화|피아노곡 화성환원|같은 선율을 세 화성으로 편곡','평행5·8도|성부진행|기능논리|색채와 긴장','내성 재배치|대리화음 실험|전조 경로 단순화','Walter Piston, Harmony|Aldwell & Schachter, Harmony and Voice Leading');
mk('MUS-103','음악사','고대·중세음악|르네상스 다성음악|바로크|고전주의|낭만주의|민족주의|인상주의|현대주의|재즈|대중음악|전자음악|글로벌 음악사','chant|counterpoint|sonata|symphony|leitmotif|jazz harmony|studio production','Gregorian chant|Palestrina|Bach|Mozart|Beethoven|Wagner|Debussy|Stravinsky|Ellington|Beatles','score listening|historical recording comparison|source criticism','Medieval|Renaissance|Baroque|Classical|Romantic|Modernism|Popular music','같은 장르의 시대별 녹음 비교|작곡가 한 작품의 역사맥락 분석','시대양식 과잉일반화|정전 중심성|연주관행','비서구 사례 추가|사료와 청취증거 분리','Richard Taruskin, Oxford History of Western Music|Burkholder, A History of Western Music');
mk('MUS-104','작곡','동기|선율|리듬|화성|대위|텍스처|형식|변주|전개|클라이맥스|가사와 음악|완성곡 설계','motif|phrase|texture|form|development|contrast','Beethoven Symphony No.5 motif|Bach inventions|Schubert songs|Bartók miniatures','motivic development|sequence|inversion|augmentation|orchestral sketch','tonal composition|modernism|minimalism|songwriting','4음 동기로 16마디 작곡|A-B-A 소품|가사 한 연에 선율 작곡','통일성과 대비|호흡|중복|클라이맥스 위치','동기 압축|구조 재배열|불필요한 성부 삭제','Arnold Schoenberg, Fundamentals of Musical Composition|William Russo, Composing Music');
mk('MUS-105','편곡','원곡 구조분석|키와 음역|리듬 재설계|화성 재구성|베이스라인|보이싱|악기배치|인트로·간주·아웃트로|장르변환|보컬 중심 편곡|다이내믹 설계|최종 편곡','arrangement map|register|voicing|groove|density','jazz standards|pop ballads|gospel arrangements|orchestral reductions','reharmonization|drop voicing|rhythmic displacement|layering','jazz|gospel|pop|orchestral|electronic','같은 곡을 두 장르로 편곡|보컬 음역에 맞춰 재조정|8트랙 제한 편곡','원곡 정체성|주파수 충돌|밀도|보컬 가독성','트랙 감축|보이싱 재배치|다이내믹 대비 강화','Don Sebesky, The Contemporary Arranger|Dick Grove, Arranging Concepts');
mk('MUS-106','오케스트레이션','현악기|목관|금관|타악기|음역과 음색|유니즌·옥타브|블렌딩|솔로와 투티|오케스트라 균형|아티큘레이션|관현악 축약|전체 악장 배치','instrument range|timbre|doubling|balance|articulation','Ravel, Boléro|Berlioz, Symphonie fantastique|Stravinsky, Rite of Spring|Mahler symphonies','score reading|transposition|doubling|register planning','Romantic orchestra|20th-century color|film scoring','피아노 8마디를 현악으로 편곡|같은 화음을 세 음색조합으로 작성','연주가능성|밸런스|두께|음역 충돌','중복음 제거|옥타브 재배치|다이내믹 수정','Samuel Adler, The Study of Orchestration|Berlioz/Strauss, Treatise on Instrumentation');
mk('MUS-107','음악미학','음악은 무엇을 표현하는가|형식주의|감정표현론|절대음악|프로그램음악|연주와 작품|즉흥성|진정성|대중음악 가치|기술과 음악|AI 창작|음악적 가치 종합','form|expression|work concept|performance|authenticity','Hanslick|Beethoven|Wagner|jazz improvisation|electronic music|AI-generated music','comparative listening|argument reconstruction|performance comparison','formalism|expressionism|new musicology|popular music studies','같은 곡 두 연주의 미학적 차이 논증|AI 음악의 작품성 논증','형식과 표현의 근거|문화편향|작품개념','반론 추가|다른 장르 사례로 검증','Eduard Hanslick, On the Musically Beautiful|Peter Kivy, Introduction to Philosophy of Music|Lydia Goehr, Imaginary Museum');
mk('MUS-108','음악기술','디지털 오디오|샘플링|비트뎁스|DAW|MIDI|마이크|EQ|컴프레서|리버브·딜레이|믹싱|마스터링|배포 포맷','sample rate|bit depth|signal flow|dynamic range|stereo field','multitrack session|dry/wet mixes|reference tracks','gain staging|editing|EQ|compression|automation|loudness metering','analog recording|digital studio|streaming era','보컬 한 트랙 편집|8트랙 믹스|레퍼런스와 LUFS 비교','clipping|masking|phase|overcompression|translation','gain 재설정|EQ 절제|모노 호환성 점검','Bob Katz, Mastering Audio|David Miles Huber, Modern Recording Techniques');
mk('MUS-109','전자음악','오실레이터|파형|필터|엔벌로프|LFO|FM 합성|샘플링|시퀀싱|드럼머신|공간계 이펙트|라이브 전자음악|전자음악 작품설계','oscillator|filter|ADSR|modulation|sequencing','Stockhausen|Wendy Carlos|Kraftwerk|Brian Eno|Aphex Twin','subtractive synthesis|FM synthesis|sampling|automation','musique concrète|electronic studio|minimal techno|ambient','한 음색을 세 방식으로 합성|샘플만으로 1분 작품 제작','aliasing|muddy spectrum|static automation|overlayering','필터·엔벌로프 단순화|공간 재설계|리듬 대비','Curtis Roads, Computer Music Tutorial|Miller Puckette, Theory and Technique of Electronic Music');
mk('MUS-110','AI 음악','MIDI 생성|audio generation|conditioning|text-to-music|style representation|voice synthesis|stem generation|AI 편곡|평가와 데이터셋|저작권·출처|인간-AI 공동창작|최종 AI 음악 프로젝트','symbolic representation|latent space|conditioning|audio tokens','Magenta examples|MusicLM|AudioCraft|Suno/Udio-type workflows','prompt design|seed comparison|stem editing|human revision|A/B evaluation','algorithmic composition|deep generative music|creator tools','같은 가사를 세 생성조건으로 비교|AI 출력물을 직접 편곡·수정|구조 반복|가사 발음오류|스타일 모방|artifact|통제력 부족','프롬프트보다 후편집 강화|구조 재작성|보컬·악기 직접 교체','David Cope, Experiments in Musical Intelligence|Huang et al., Music Transformer|Agostinelli et al., MusicLM');

mk('FAR-101','미술사','선사·고대미술|그리스·로마|중세|르네상스|바로크|신고전·낭만|인상주의|후기인상|모더니즘|추상|전후미술|동시대미술','composition|iconography|perspective|materiality','Parthenon|Giotto Arena Chapel|Michelangelo Sistine Chapel|Velázquez Las Meninas|Monet|Picasso|Rothko|Duchamp','formal analysis|iconographic analysis|provenance research','Renaissance|Baroque|Impressionism|Cubism|Dada|Abstract Expressionism','한 작품의 형식·후원·관객 분석|동일 주제 시대별 비교','정전 중심성|식민지 수집|작가중심 서술','여성·비서구 작가 추가|소장 이력 검토','E.H. Gombrich, The Story of Art|Hal Foster et al., Art Since 1900');
mk('FAR-102','조형원리','점·선·면|형태|비례|균형|리듬|대비|강조|통일|공간|질감|게슈탈트|복합구성','balance|contrast|rhythm|hierarchy|unity|negative space','Bauhaus exercises|Mondrian|Klee|graphic compositions','thumbnail sketch|value study|grid|cropping','Bauhaus|Constructivism|modern design basics','흑백 도형만으로 균형 3안|같은 요소의 리듬변주','시선흐름|중심성|시각적 무게|불필요 요소','크롭 수정|계층 단순화|대비 재조정','Wucius Wong, Principles of Form and Design|Johannes Itten, Design and Form');
mk('FAR-103','회화','드로잉과 관찰|명암|색 혼합|구도|원근|인물|정물|풍경|추상|레이어링|매체혼합|연작','value|color|composition|surface|gesture','Rembrandt portraits|Cézanne still life|Monet landscape|Rothko color fields','charcoal drawing|underpainting|glazing|impasto|wet-on-wet','Realism|Impressionism|Expressionism|Abstraction','정물 3구도|제한 팔레트 회화|동일대상 사실·추상 2안','비례|명암구조|색온도|표면 통일성','밑그림 수정|채도 제한|초점영역 강화','James Gurney, Color and Light|Josef Albers, Interaction of Color');
mk('FAR-104','조각','질량과 부피|양감과 빈공간|점토 모델링|석고|목재|석재|금속|조립|주조|설치|공공조각|디지털 제작','mass|volume|void|balance|site','Michelangelo David|Rodin|Brancusi|Henry Moore|Richard Serra','modeling|carving|casting|welding|assemblage|3D printing','Classical sculpture|Modernism|Minimalism|Installation','점토 소형 인체|negative space 중심 조형|site-specific 모형','구조안정|재료적합성|스케일|관객동선','무게중심 수정|접합부 강화|설치위치 재설계','Herbert Read, Modern Sculpture|Rudolf Wittkower, Sculpture');
mk('FAR-105','색채학','색의 물리|색상·명도·채도|가산·감산혼합|색대비|동시대비|색온도|색채조화|색과 공간|색과 감정|색채시스템|디지털 색관리|색채프로젝트','hue|value|chroma|RGB|CMYK|contrast','Albers color studies|Munsell charts|Itten exercises','color mixing|palette restriction|calibration|soft proofing','Bauhaus color theory|modern color science','동일색이 배경에 따라 달라지는 실험|3색 팔레트 디자인','색 대비|접근성|출력차이|문화적 의미','명도차 강화|색 수 축소|ICC 프로파일 점검','Josef Albers, Interaction of Color|Johannes Itten, The Art of Color');
mk('FAR-106','시각문화','보는 행위와 권력|재현|사진|광고|영화이미지|뉴스이미지|젠더|인종|감시|밈|플랫폼 이미지|생성형 이미지','gaze|representation|framing|spectacle|visuality','Berger examples|advertisements|photojournalism|social media feeds','semiotic analysis|framing analysis|visual ethnography','visual culture studies|feminist film theory|postcolonial critique','광고 한 장의 기호분석|같은 사건의 매체별 프레이밍 비교','맥락삭제|stereotype|selection bias|algorithmic amplification','반대 프레임 추가|출처 추적|시각근거와 해석 분리','John Berger, Ways of Seeing|Nicholas Mirzoeff, An Introduction to Visual Culture');
mk('FAR-107','현대미술','아방가르드|다다|초현실주의|추상표현주의|팝아트|미니멀리즘|개념미술|퍼포먼스|대지미술|제도비평|관계미학|디지털·AI 미술','appropriation|concept|site|performance|institution','Duchamp Fountain|Warhol|Donald Judd|Joseph Kosuth|Marina Abramović|Ai Weiwei','readymade|installation|performance documentation|digital fabrication','Dada|Pop|Minimalism|Conceptual Art|Post-internet','일상물로 개념작품 설계|작품보다 지시문이 중심인 작업','개념의 명료성|제도 의존|관객참여|윤리','작가문 수정|설치맥락 변경|관객 피드백 반영','Hal Foster et al., Art Since 1900|Arthur Danto, After the End of Art');

mk('DES-101','디자인원리','문제정의|사용자|기능과 형태|시각계층|그리드|타이포그래피|색|일관성|제약조건|프로토타입|평가|통합디자인','hierarchy|grid|affordance|consistency|constraint','Bauhaus posters|Braun products|Swiss Style|Apple design examples','sketching|wireframe|prototype|design critique','Bauhaus|Ulm|Swiss Style|human-centered design','하나의 안내물을 3안으로 설계|기능 우선 제품 스케치','목적성|가독성|사용성|일관성','요소 삭제|계층 재정렬|사용자 피드백 반영','Don Norman, The Design of Everyday Things|Ellen Lupton, Graphic Design: The New Basics');
mk('DES-102','시각디자인','점·선·면|레이아웃|그리드|타이포그래피|이미지|색|브랜딩|포스터|편집디자인|아이콘|디지털 캠페인|포트폴리오','grid|type hierarchy|contrast|alignment|identity','Bauhaus posters|Josef Müller-Brockmann|Paul Rand|Pentagram identities','layout|typesetting|vector drawing|brand system','Swiss International Style|modern branding|digital design','행사 포스터 3안|브랜드 기본시스템|4페이지 편집물','가독성|시선흐름|브랜드 일관성|정보 우선순위','타입 크기 재설정|그리드 정리|장식요소 삭제','Josef Müller-Brockmann, Grid Systems|Ellen Lupton, Thinking with Type');
mk('DES-103','정보디자인','정보구조|데이터와 메시지|표|그래프|지도|타임라인|다이어그램|네트워크|불확실성|대시보드|접근성|정보윤리','data-ink|hierarchy|encoding|annotation|uncertainty','Minard map|London Tube map|NYT graphics|scientific figures','chart selection|annotation|small multiples|dashboard prototyping','modern cartography|statistical graphics|data journalism','같은 데이터를 3차트로 표현|복잡한 절차를 다이어그램화','오도성 축|과잉장식|색각 접근성|불확실성 누락','축 수정|범례 단순화|신뢰구간 추가','Edward Tufte, The Visual Display of Quantitative Information|Alberto Cairo, The Functional Art');
mk('DES-104','제품디자인','사용상황|인간공학|기능분해|형태|재료|제조|메커니즘|CMF|프로토타입|사용성시험|지속가능성|제품개발 종합','ergonomics|form|material|manufacturability|lifecycle','Braun products|Eames furniture|OXO Good Grips|consumer electronics','foam mockup|CAD|3D printing|DFM','industrial design|universal design|sustainable design','손잡이 제품 3안|1:1 폼모델|사용성 5인 테스트','그립|안전|제조가능성|수리성|환경영향','치수 수정|부품감축|재료교체','Henry Dreyfuss, Designing for People|Ulrich & Eppinger, Product Design and Development');
mk('DES-105','인터랙션디자인','행동과 피드백|affordance|상태|내비게이션|입력|오류|마이크로인터랙션|모바일 제스처|대화형 UI|멀티모달|프로토타입|사용성평가','feedback|mapping|state|flow|error prevention','ATM|smartphone apps|voice assistants|interactive installations','user flow|state diagram|clickable prototype|usability test','HCI|ubiquitous computing|conversational interaction','로그인 흐름 프로토타입|오류복구 시나리오 설계','발견가능성|응답시간|오류율|인지부하','단계 축소|피드백 강화|오류메시지 수정','Alan Cooper, About Face|Dan Saffer, Microinteractions');
mk('DES-106','UX/UI','사용자 조사|persona 비판|journey map|information architecture|wireframe|UI pattern|design system|responsive design|accessibility|usability test|analytics|iteration','task success|cognitive load|consistency|WCAG|conversion','GOV.UK|Material Design|Apple HIG|accessible websites','interview|card sorting|wireframe|Figma prototype|A/B test','user-centered design|lean UX|design systems','실제 서비스 한 흐름 재설계|모바일·폴드·데스크톱 반응형 안','task completion|SUS|접근성|오류율|retention','레이블 수정|탭 수 감소|대비·터치영역 수정','Steve Krug, Don’t Make Me Think|Nielsen Norman Group research|WCAG');
mk('DES-107','서비스디자인','서비스 생태계|이해관계자|고객여정|frontstage/backstage|service blueprint|접점|대기와 실패|직원 경험|정책과 규칙|프로토타입|측정|서비스 개선','journey|touchpoint|blueprint|queue|recovery','hospital service|airport|banking|public service','contextual inquiry|blueprinting|role-play|service prototyping','service design|design thinking|public sector design','민원 서비스 blueprint|실패 접점 재설계','대기시간|handoff|failure recovery|형평성','병목 제거|역할 재배치|예외경로 추가','Marc Stickdorn et al., This Is Service Design Doing|Andy Polaine et al., Service Design');
mk('DES-108','생성형 AI 디자인','생성모델 이해|프롬프트와 제약|이미지 생성|텍스트·레이아웃|브랜드 변형|참조이미지|일관성|편향|저작권·출처|human-in-the-loop|품질평가|AI 디자인 시스템','prompt|conditioning|variation|consistency|provenance','generative image workflows|AI layout tools|brand variation sets','prompt iteration|reference control|inpainting|manual compositing','computational design|generative art|AI-assisted design','동일 brief로 20안 생성 후 3안 선별·수정|AI 결과를 직접 재편집','artifact|텍스트오류|스타일 편향|브랜드 불일치|출처 불명','수작업 typography|형태 재구성|생성기록 보존','Lev Manovich, AI Aesthetics|Adobe/industry content provenance materials|C2PA specifications');

mk('AES-101','미학','미의 개념|모방|숭고|취미판단|형식|표현|예술정의|해석|예술가 의도|제도론|일상미학|AI 미학','beauty|mimesis|sublime|taste|form|expression','Plato|Aristotle|Kant|Hegel|Tolstoy|Danto','argument analysis|comparative artwork analysis','ancient aesthetics|German idealism|analytic aesthetics','같은 작품을 칸트·단토 관점으로 각각 분석','개념정확성|작품증거|이론의 설명범위','반례 추가|이론 적용범위 제한','Plato, Republic X|Kant, Critique of Judgment|Arthur Danto, The Transfiguration of the Commonplace');
mk('AES-102','예술철학','예술 정의|재현|표현|형식|작품과 물체|작가의도|해석|위작|예술가치|예술과 도덕|대중예술|AI와 저자성','representation|expression|ontology|intention|interpretation|authorship','Duchamp|forgery cases|performance art|conceptual art|AI works','conceptual analysis|counterexample|thought experiment','institutional theory|historical definition|analytic aesthetics','AI 생성물을 예술로 보는 조건 논증|위작의 미학적 가치 토론','필요·충분조건|반례|작품관행','정의 수정|예외조건 명시','Noël Carroll, Philosophy of Art|Jerrold Levinson, Music, Art, and Metaphysics');
mk('AES-103','문화이론','문화 개념|헤게모니|문화산업|기호와 신화|구별짓기|정체성|재현|담론|팬덤|서브컬처|플랫폼문화|알고리즘 문화','hegemony|culture industry|myth|habitus|representation','Adorno|Gramsci|Barthes|Bourdieu|Stuart Hall','discourse analysis|semiotics|cultural ethnography','Frankfurt School|Birmingham CCCS|poststructuralism','플랫폼 인기콘텐츠 한 사례를 이론 2개로 분석','엘리트주의|경제환원|텍스트 과잉해석|자료부족','실제 이용자료 추가|경쟁이론 비교','Stuart Hall, Representation|Pierre Bourdieu, Distinction|Adorno & Horkheimer');
mk('AES-104','대중문화','대중문화 정의|대량생산|스타시스템|텔레비전|대중음악|영화|광고|팬덤|게임|밈|인플루언서|스트리밍 플랫폼','genre|celebrity|fandom|participation|platform','Hollywood|K-pop|YouTube|TikTok|gaming communities','content analysis|audience study|platform observation','mass culture theory|participatory culture|platform studies','한 콘텐츠의 제작-유통-수용 경로 분석|팬덤 참여관찰 설계','인기=가치 등치|플랫폼 지표 편향|팬덤 일반화','정성자료 추가|플랫폼 비교','John Storey, Cultural Theory and Popular Culture|Henry Jenkins, Convergence Culture');
mk('AES-105','미디어예술','사진과 기술|영화실험|비디오아트|사운드아트|인터랙티브아트|넷아트|VR/AR|데이터아트|바이오아트|로봇아트|생성예술|AI 미디어아트','time|interface|interaction|data|immersion','Nam June Paik|Bill Viola|Rafael Lozano-Hemmer|teamLab|Refik Anadol','video editing|sensors|projection mapping|creative coding|real-time graphics','video art|new media art|interactive art|generative art','센서 입력에 반응하는 소형 작품 설계|데이터를 시청각으로 변환','기술과잉|interaction latency|관객동선|데이터윤리','기술요소 감축|반응규칙 수정|설명문 정리','Christiane Paul, Digital Art|Lev Manovich, The Language of New Media');
mk('AES-106','저작권과 창작','저작물과 창작성|아이디어·표현|저작자|공동저작|2차적저작물|인용|공정이용|음악저작권|이미지·사진|소프트웨어|생성형 AI|라이선스와 출처관리','originality|authorship|derivative work|fair use|license','sampling disputes|appropriation art|photography cases|AI training disputes','rights clearance|citation|license tracking|provenance record','copyright law|Creative Commons|digital rights management','한 창작물의 권리관계표 작성|샘플 사용 전 clearance checklist','법률관할 차이|라이선스 누락|출처불명 AI 출력','출처기록 추가|사용범위 축소|대체소재 사용','WIPO copyright materials|Creative Commons licenses|국가별 저작권법 원문');
})();