(()=>{'use strict';
const out=window.NEXUS_LAW_TEXTBOOKS=window.NEXUS_LAW_TEXTBOOKS||{};
const S=window.NEXUS_UNIVERSITY_UTILS.splitList;
function mk(id,focus,chapters,norms,doctrines,cases,compare,readings,scenario){
 const ch=S(chapters),ns=S(norms),ds=S(doctrines),cs=S(cases),cmp=S(compare),rd=S(readings),sc=S(scenario);
 out[id]={kind:'law',focus,readings:rd,lessons:Array.from({length:12},(_,i)=>{
  const title=ch[i]||`${focus}의 쟁점 ${i+1}`, n1=ns[i%Math.max(ns.length,1)]||'관련 법령·규범', n2=ns[(i+1)%Math.max(ns.length,1)]||n1;
  const d1=ds[i%Math.max(ds.length,1)]||'법적 요건과 효과', d2=ds[(i+1)%Math.max(ds.length,1)]||'해석과 적용';
  const ca=cs[i%Math.max(cs.length,1)]||'대표 판례의 사실관계와 판시구조', co=cmp[i%Math.max(cmp.length,1)]||'비교법상 접근', sr=sc[i%Math.max(sc.length,1)]||`${focus}에 관한 가상사례`;
  return {n:i+1,title,question:`${title}에서 적용규범·요건·법효과·증명책임은 어떻게 연결되는가?`,
   theory:[d1,d2],norms:[n1,n2],caseLaw:[ca],comparison:[co],
   lecture:[`${title}은 ${focus}의 체계 안에서 독립된 규범문제로 다루어야 한다. 먼저 적용 가능한 법원과 규범의 위계를 확인하고, 구성요건 또는 법률요건을 요소별로 분해한 뒤 각 요건에 대응하는 사실과 증거를 배치한다. 결론부터 정하는 것이 아니라 규범→요건→사실→법효과의 순서를 유지하는 것이 기본이다.`,`핵심 법리는 ${d1}과 ${d2}이다. 이 법리들은 문언만으로 결정되지 않고 입법목적, 체계적 위치, 기본권과의 관계, 판례가 형성한 세부기준에 의해 구체화된다. 따라서 ${n1} 및 ${n2}의 문언을 출발점으로 삼되 판례가 어떤 사실을 결정적으로 보았는지, 학설이 어디에서 갈리는지를 함께 비교해야 한다.`,`사례 해결에서는 반대논증을 반드시 병치한다. 동일 사실도 당사자의 지위, 행위시점, 주관적 요소, 인과관계, 손해 또는 위험의 발생, 절차적 하자 여부에 따라 법적 평가가 달라질 수 있다. 최종 결론은 확정적 단정이 아니라 인정사실과 불확실한 사실을 구분한 뒤 각 쟁점별 잠정결론을 합성해 제시한다.`],
   application:`사례 포섭: ${sr}. ① 사실을 시간순으로 정리한다. ② ${n1}을 중심으로 적용규범을 특정한다. ③ ${d1}의 요건을 세분한다. ④ 각 요건에 유리·불리한 사실과 증거를 배치한다. ⑤ ${ca}의 판시기준과 비교한다. ⑥ 반론과 재반론을 거쳐 법효과와 구제수단을 제시한다.`,
   exercise:[`${title}의 법률요건을 3~6개 요소로 분해하라.`,`${ca}에서 법원이 중요하게 평가했을 사실을 추출하고 본 사례와 구별하라.`,`${co}와 국내법 접근이 달라지는 지점을 한 가지 제시하라.`],
   tutor:`${id} ${focus} L${String(i+1).padStart(2,'0')} ${title} 사례풀이를 하자. 정답을 먼저 말하지 말고 사실관계→쟁점→적용조문→요건→판례기준→포섭→반론→결론 순서로 한 단계씩 질문해 줘. 판례나 조문을 제시할 때는 불확실하면 불확실하다고 표시하고 원문 확인이 필요한 지점을 분리해 줘.`};
 })};
}
mk('LAW-101','법학입문','법과 규범의 구조|법원과 법규범의 위계|권리·의무·권한·책임|공법과 사법|실체법과 절차법|법률요건과 법률효과|법적 사실과 증명|법해석의 기본|판례와 선례|법적 논증과 포섭|구제수단과 집행|종합 사례해결','대한민국헌법|민법|형법|행정기본법|민사소송법|형사소송법','Hohfeld의 법적 관계|법률요건-법률효과 구조|법원론|법적 삼단논법|법적 권리와 구제|절차적 정당성','헌법재판소의 기본권 심사구조|대법원의 민사·형사 판례 형성방식','대륙법계 성문법 중심 구조|영미법계 precedent와 stare decisis','H.L.A. Hart, The Concept of Law|Neil MacCormick, Legal Reasoning and Legal Theory|Karl Larenz, Methodenlehre der Rechtswissenschaft','온라인 플랫폼의 이용정지 분쟁|자율시스템 사고와 책임주체 분쟁');
mk('LAW-102','법철학','자연법과 법실증주의|Kelsen의 순수법학|Hart의 승인규칙|Fuller의 법의 내재적 도덕성|Dworkin의 원리와 권리|Raz의 권위이론|Radbruch 공식|정의와 법적 안정성|권리론과 공익|법인격과 법적 지위|AI 행위자성과 책임|법개념 종합논증','대한민국헌법 제10조|대한민국헌법 제37조 제2항|법치국가원리','자연법론|법실증주의|포괄적 법실증주의|배제적 법실증주의|해석주의|법의 권위|Radbruch 공식','독일 전후 Radbruch 논쟁|헌법재판소의 법치주의·과잉금지원칙 판례군','Hart–Dworkin debate|Alexy의 원리이론|미국 legal realism','H.L.A. Hart, The Concept of Law|Ronald Dworkin, Law’s Empire|Hans Kelsen, Pure Theory of Law|Lon L. Fuller, The Morality of Law|Robert Alexy, A Theory of Constitutional Rights','극단적으로 부정의한 법률의 효력|AI에게 제한적 법적 지위를 부여하는 입법안');
mk('LAW-103','법사회학','법과 사회질서|Weber의 합리화|Durkheim의 연대와 법|Ehrlich의 살아있는 법|Pound의 사회공학|법의식과 준법|법조직과 전문직|소송과 분쟁피라미드|법과 불평등|규제와 조직행동|플랫폼·알고리즘과 규범|경험적 법연구 설계','헌법상 법치국가원리|행정규제 관련 법제|사법통계·행정통계','법사회학|legal consciousness|law in action|responsive regulation|repeat player theory|legal mobilization','Galanter의 Why the Haves Come Out Ahead|규제기관과 피규제조직 판례·사례군','미국 Law & Society 전통|유럽 socio-legal studies','Max Weber, Economy and Society|Eugen Ehrlich, Fundamental Principles of the Sociology of Law|Roscoe Pound, Social Control Through Law|Marc Galanter, Why the Haves Come Out Ahead','플랫폼 약관은 법원 판단 전에도 이용자 행동을 규율하는가|AI 감사의무가 조직 내부 의사결정을 실제로 바꾸는가');
mk('LAW-104','법해석론','문언해석|체계해석|역사해석|목적론적 해석|유추와 반대해석|헌법합치적 해석|법률의 흠결|원칙과 규칙의 충돌|판례해석|입법자료의 사용|동태적 해석과 신기술|해석 종합실습','헌법 제37조 제2항|민법 제1조·제103조|형법 제1조|행정기본법','Savigny의 해석요소|문언주의|목적론|유추해석의 한계|헌법합치적 해석|원칙충돌과 비례성','형벌법규 엄격해석 판례군|신기술에 기존 법개념을 적용한 판례군','미국 textualism/purposivism|EU effet utile','Friedrich Carl von Savigny, System des heutigen Römischen Rechts|Karl Larenz, Methodenlehre|Antonin Scalia & Bryan Garner, Reading Law','법률에 AI가 명시되지 않은 경우 기존 자동화 규정의 적용|디지털 자산을 물건 개념에 포함할 수 있는지');
mk('LAW-105','헌법','헌법과 국가권력|기본권 주체와 효력|인간의 존엄과 행복추구|평등원칙|신체의 자유와 적법절차|표현의 자유|사생활·개인정보 자기결정|재산권|재판청구권|과잉금지원칙|권력분립과 사법심사|AI 시대 기본권 충돌','헌법 제10조|헌법 제11조|헌법 제12조|헌법 제17조|헌법 제21조|헌법 제23조|헌법 제27조|헌법 제37조 제2항','기본권 보호영역|과잉금지원칙|평등심사|적법절차|국가의 기본권 보호의무|기본권의 대사인효','헌법재판소의 과잉금지원칙 판례군|개인정보자기결정권 판례군|표현의 자유 판례군','독일 비례성심사|미국 strict/intermediate scrutiny|EU Charter 기본권심사','대한민국헌법|Robert Alexy, A Theory of Constitutional Rights|헌법재판소 결정례','공공기관 얼굴인식 시스템 도입|AI 자동심사로 복지급여가 중단된 경우');
mk('LAW-106','행정법','행정법의 법원|행정행위와 처분|재량과 기속|부관|행정절차와 이유제시|행정상 계약·지도|행정입법|행정강제와 제재|취소·무효|행정심판·행정소송|국가배상|알고리즘 행정과 자동처분','행정기본법|행정절차법|행정심판법|행정소송법|국가배상법','처분성|재량통제|신뢰보호|비례원칙|평등원칙|절차적 하자|원고적격','재량권 일탈·남용 판례군|처분성 확대 판례군|국가배상 위법성 판례군','독일 Verwaltungsakt|EU good administration|미국 APA judicial review','행정기본법|행정절차법|행정소송법|Paul Craig, Administrative Law','AI가 산정한 위험점수로 영업허가가 거부된 경우|자동 과태료 시스템 오류');
mk('LAW-107','민법총칙','민법의 기본원리|권리주체와 권리능력|법인|법률행위|반사회질서 법률행위|의사표시|착오|사기·강박|대리|무효와 취소|조건·기한|소멸시효','민법 제1조|민법 제103조|민법 제104조|민법 제107조|민법 제108조|민법 제109조|민법 제110조|민법 대리 규정','사적자치|신의성실|권리남용|의사주의와 표시주의|대리권|표현대리|무효·취소','비진의표시·통정허위표시 판례군|착오 취소 판례군|표현대리 판례군','독일 BGB Allgemeiner Teil|일본 민법 총칙','민법|곽윤직·김재형 민법총칙|Larenz/Wolf, Allgemeiner Teil des BGB','생성형 AI가 작성한 계약서에 중대한 착오가 있는 경우|AI 에이전트가 권한을 초과해 주문한 경우');
mk('LAW-108','물권법','물권법정주의|물권변동과 공시|등기|점유|소유권|상린관계|공동소유|취득시효|선의취득|용익물권|담보물권|디지털 자산과 물권개념','민법 제185조|민법 제186조|민법 제187조|민법 제192조 이하|민법 제213조|민법 제214조|민법 제245조|민법 제249조','물권법정주의|공시의 원칙|공신의 원칙|점유권|배타성|우선순위','등기 없는 물권변동 판례군|취득시효 판례군|명의신탁 관련 판례군','독일 Trennungsprinzip/Abstraktionsprinzip|영미 property bundle of rights','민법 물권편|Thomas Merrill & Henry Smith, Property','토큰화 자산의 소유권 주장|무권리자가 처분한 동산을 플랫폼에서 취득한 경우');
mk('LAW-109','채권법','채권관계의 구조|급부의무와 보호의무|이행과 변제|채무불이행|이행지체|이행불능|손해배상 범위|과실상계|채권자대위|채권자취소|다수당사자 채권|위험부담과 사정변경','민법 제390조|민법 제391조|민법 제393조|민법 제396조|민법 제404조|민법 제406조|민법 변제·공탁 규정','채무불이행|귀책사유|상당인과관계|통상손해·특별손해|과실상계|책임재산 보전','채무불이행 손해배상 판례군|특별손해 예견가능성 판례군|채권자취소 판례군','CISG remedies|독일 Leistungsstörungsrecht','민법 채권총론|CISG|김형배 채권총론','클라우드 장애로 연쇄 손해가 발생한 경우|AI 서비스 공급자가 SLA를 위반한 경우');
mk('LAW-110','계약법','계약자유와 한계|청약과 승낙|약관과 표준계약|계약해석|계약체결상 과실|동시이행|위험부담|채무불이행과 구제|해제·해지|손해배상 예정|전자계약|AI 에이전트의 계약체결','민법 제105조|민법 제109조|민법 제110조|민법 제390조|민법 제398조|민법 계약총칙|전자문서 및 전자거래 기본법','계약자유|합의|신뢰책임|약관규제|사정변경|효율적 계약위반 논의','계약해석 판례군|약관 명시·설명의무 판례군|전자거래 판례·분쟁례','CISG|UN Convention on Electronic Communications Art.12|미국 UETA/ESIGN','민법|CISG|UNCITRAL Electronic Communications Convention|E. Allan Farnsworth, Contracts','구매 AI가 가격오류 상품을 대량 주문한 경우|대화형 AI의 약속이 계약조건이 되는지');
mk('LAW-111','불법행위법','일반불법행위 요건|위법성|고의·과실|주의의무|인과관계|손해|사용자책임|공작물책임|공동불법행위|과실상계|제조물·위험책임|AI 손해와 책임귀속','민법 제750조|민법 제751조|민법 제756조|민법 제758조|민법 제760조|제조물책임법','과실책임|주의의무|상당인과관계|보호법규론|공동불법행위|위험책임','상당인과관계 판례군|사용자책임 판례군|공동불법행위 판례군','미국 negligence/product liability|EU Product Liability Directive (EU) 2024/2853','민법|제조물책임법|Prosser and Keeton on Torts|European Tort Law','추천 알고리즘이 위험행동을 유발했다는 손해주장|다중 AI 에이전트 상호작용으로 손해가 발생한 경우');
mk('LAW-112','상법','상인과 상행위|상업사용인과 대리|상호·상업등기|상사채권|상사매매|운송·창고|보험|어음·수표의 기본|전자상거래|플랫폼 거래|기업 간 위험배분|AI 상거래','상법|전자상거래 등에서의 소비자보호에 관한 법률|전자문서 및 전자거래 기본법','기업거래 신속성|외관주의|상사대리|상사보증|상사시효|거래안전','상사대리·명의대여 판례군|보험약관 판례군|전자상거래 분쟁례','UCC Article 2|CISG|EU Digital Services framework','상법|CISG|UCC','자동발주시스템의 권한 범위|플랫폼 사업자의 거래상 책임');
mk('LAW-113','회사법','회사와 법인격|주식회사 설립|주식과 자본|주주총회|이사와 이사회|이사의 충실·선관주의의무|이사 책임|대표소송|회사기회·이해충돌|기업집단|ESG·컴플라이언스|AI 이사회와 알고리즘 경영','상법 회사편|상법 제382조의3|상법 제399조|상법 제401조','법인격|유한책임|fiduciary duty|business judgment rule|법인격부인|주주대표소송','이사 책임 판례군|법인격부인 판례군|주주대표소송 판례군','Delaware fiduciary law|UK Companies Act s.172','상법|Clark, Corporate Law|Gower Principles of Modern Company Law','이사회가 AI 의사결정시스템을 검증 없이 채택한 경우|자회사 AI 사고에 모회사가 관여한 경우');
mk('LAW-114','형법총론','죄형법정주의|범죄체계론|구성요건 해당성|고의|과실|인과관계·객관적 귀속|부작위범|위법성 조각|책임론|미수|공범|AI와 형사책임','형법 제1조|형법 제13조|형법 제14조|형법 제17조|형법 제18조|형법 제20조~제24조|형법 제25조|형법 제30조~제32조','죄형법정주의|구성요건적 고의|허용된 위험|객관적 귀속|작위의무|정당방위|책임능력','인과관계 판례군|부작위범 작위의무 판례군|공동정범 판례군','독일 3단계 범죄체계|영미 mens rea/actus reus','형법|Roxin, Strafrecht Allgemeiner Teil|Jescheck/Weigend','자율로봇 사고에서 운영자의 과실|AI가 범죄계획을 생성했으나 인간이 일부만 실행한 경우');
mk('LAW-115','형법각론','생명·신체 범죄|자유에 관한 죄|명예·신용 범죄|재산범죄 구조|절도|사기|횡령·배임|업무방해|컴퓨터등사용사기|문서·전자기록 범죄|사이버 범죄|생성형 AI 악용 범죄','형법 제250조|형법 제257조|형법 제307조|형법 제314조|형법 제329조|형법 제347조|형법 제347조의2|형법 제355조','보호법익|불법영득의사|기망행위|처분행위|재산상 손해|배임임무','사기죄 기망·처분행위 판례군|배임죄 임무위배 판례군|업무방해 판례군','미국 computer fraud statutes|EU cybercrime instruments','형법|사이버범죄 관련 특별법령','딥페이크를 이용한 사기|AI 자동거래를 악용한 재산상 이익 취득');
mk('LAW-116','민사소송법','민사재판과 소송요건|당사자와 당사자능력|관할|소의 이익|변론주의|처분권주의|증명책임|자유심증|문서·전자증거|공동소송|판결의 효력|AI 시대 증거와 소송능력','민사소송법|민사소송법 제202조|전자문서 관련 증거규정','변론주의|처분권주의|증명책임분배|자유심증주의|기판력|소송물','증명책임 판례군|전자문서 증거능력 판례군|기판력 판례군','미국 discovery|EU civil procedure cooperation','민사소송법|Rosenberg/Schwab/Gottwald Zivilprozessrecht','AI 로그가 핵심증거인데 사업자가 보유하고 있는 경우|기능적 AI 단위에 당사자능력을 부여할 수 있는지');
mk('LAW-117','형사소송법','적법절차와 수사|강제처분 법정주의|체포·구속|압수·수색|디지털 증거|공소제기|공판중심주의|증거능력|전문법칙|자백법칙|위법수집증거배제|AI 수사·예측치안','헌법 제12조|형사소송법 제307조|형사소송법 제308조|형사소송법 제309조|형사소송법 제310조|형사소송법 제312조','영장주의|적법절차|증거능력|전문법칙|위법수집증거배제|무죄추정','디지털 압수수색 판례군|위법수집증거 판례군|자백보강법칙 판례군','미국 Fourth Amendment|ECtHR fair trial jurisprudence','형사소송법|Wayne LaFave, Criminal Procedure','AI 얼굴인식으로 용의자를 특정한 뒤 수색한 경우|생성형 AI 분석보고서의 증거가치');
mk('LAW-118','국제법','국제법의 법원|조약법|국가와 승인|국가관할권|국가책임|외교면제|국제기구|무력사용 금지|자위권|국제인권법|국제분쟁해결|사이버·AI와 국제법','ICJ Statute Art.38|UN Charter Art.2(4)|UN Charter Art.51|Vienna Convention on the Law of Treaties Arts.31-32|Articles on State Responsibility','조약해석|관습국제법|국가귀속|국가책임|jus cogens|비례성','Nicaragua v United States|Lotus|Barcelona Traction','UN·ICJ 체계|EU·지역인권체계','ICJ Statute|UN Charter|VCLT|James Crawford, Brownlie’s Principles of Public International Law','국가가 민간 AI 사이버작전을 사실상 통제한 경우|자율무기 공격의 국가귀속');
mk('LAW-119','국제사법','국제재판관할|준거법 선택|계약 준거법|불법행위 준거법|물권·지식재산|가족·상속|법인|외국판결 승인·집행|국제중재|소비자·근로자 보호|플랫폼 국경간 거래|AI 서비스와 충돌법','국제사법|뉴욕협약|헤이그국제사법회의 협약','최밀접관련원칙|당사자자치|공서예외|강행규정|외국판결 승인','국제재판관할 판례군|외국판결 승인 판례군','Rome I|Rome II|Brussels I bis','국제사법|Dicey, Morris & Collins on the Conflict of Laws','한국 이용자와 미국 AI사업자 간 손해분쟁|다국가 에이전트가 자동계약을 체결한 경우');
mk('LAW-120','경제법','시장과 경쟁정책|시장획정|시장지배적 지위|카르텔|수직제한|기업결합|불공정거래|플랫폼 경쟁|소비자보호|데이터와 경쟁|알고리즘 담합|AI 시장의 규제','독점규제 및 공정거래에 관한 법률|Sherman Act §1|Sherman Act §2|TFEU Arts.101-102','시장획정|시장지배력|경쟁제한성|효율성 항변|essential facilities 논의|two-sided markets','플랫폼 시장획정 사건군|기업결합 심사사례|가격담합 사건군','미국 antitrust|EU competition law','공정거래법|Herbert Hovenkamp, Federal Antitrust Policy|EU Competition Law materials','가격결정 AI들이 명시적 합의 없이 평행적으로 가격을 올린 경우|대형 AI 플랫폼의 데이터 결합');
mk('LAW-121','노동법','노동기본권|근로자성|근로계약|임금|근로시간|해고|취업규칙|산업안전|노동조합|단체교섭|플랫폼 노동|AI 인사관리와 알고리즘 통제','헌법 제32조|헌법 제33조|근로기준법|노동조합 및 노동관계조정법|산업안전보건법','종속성|근로자성|해고의 정당한 이유|불이익변경|단결권|사용자성','근로자성 판례군|해고 정당성 판례군|플랫폼 종사자 판례·결정례','ILO standards|EU Platform Work Directive','근로기준법|노동조합법|ILO Conventions','AI 성과평가를 근거로 자동해고한 경우|플랫폼 배달노동자의 근로자성');
mk('LAW-122','지식재산법','지식재산 체계|저작물성과 창작성|저작자|저작재산권·인격권|공정이용·제한|특허요건|발명자|상표와 혼동|영업비밀|데이터베이스|AI 학습데이터|AI 생성물과 발명','저작권법|특허법|상표법|부정경쟁방지법|Berne Convention|TRIPS','창작성|아이디어-표현 이분법|신규성|진보성|발명자성|공정이용','Thaler v. Vidal|Thaler v. Perlmutter|AI 학습데이터 저작권 소송군','미국 fair use|EU DSM Directive text/data mining','저작권법|특허법|WIPO 자료|Pamela Samuelson 등 AI-IP 연구','생성형 AI 이미지의 저작권 주장|AI가 도출한 발명에서 인간 기여가 제한적인 경우');
mk('LAW-123','개인정보·데이터법','개인정보 개념|처리의 법적 근거|동의와 목적제한|민감정보|개인정보처리자 의무|정보주체 권리|프로파일링·자동결정|가명·익명화|국외이전|안전조치·침해사고|데이터 거버넌스|AI 학습과 개인정보','개인정보 보호법|GDPR Art.5|GDPR Art.6|GDPR Art.9|GDPR Arts.12-22|GDPR Arts.32-35','목적제한|데이터 최소화|적법성|투명성|privacy by design|DPIA','CJEU SCHUFA C-634/21|개인정보자기결정권 판례군|국외이전 관련 EU 판례군','GDPR|미국 sectoral privacy|한국 개인정보보호법','개인정보 보호법|GDPR|EDPB Guidelines|Solove, Understanding Privacy','고객대화 로그를 모델학습에 재사용한 경우|신용평가 AI가 프로파일링으로 대출을 거절한 경우');
mk('LAW-124','정보통신법','통신규제 구조|전기통신사업자|플랫폼 책임|콘텐츠 규율|전자문서|전자서명|전자상거래|통신비밀|망·접근과 중립성|사이버보안 의무|온라인 중개서비스|생성형 AI 서비스 규율','전기통신사업법|전자문서 및 전자거래 기본법|전자서명법|통신비밀보호법|전자상거래 등에서의 소비자보호에 관한 법률','중개자책임|통신비밀|전자문서 효력|플랫폼 주의의무|네트워크 거버넌스','플랫폼 게시물 책임 판례군|전자문서·전자계약 판례군','EU Digital Services Act|US CDA §230|EU eIDAS','전기통신사업법|DSA|Jack Goldsmith & Tim Wu, Who Controls the Internet?','생성형 AI 서비스가 불법 콘텐츠를 반복 출력한 경우|AI 챗봇을 통한 전자계약과 고지의무');
mk('LAW-125','인공지능법','AI 규율의 대상과 정의|위험기반 규제|금지·고위험 AI|투명성|데이터 거버넌스|인간감독|안전·성능·로그|책임귀속|제조물책임|차별·기본권|Agentic AI·다중에이전트|AI 법체계 종합','인공지능 발전과 신뢰 기반 조성 등에 관한 기본법|EU AI Act Regulation (EU) 2024/1689|GDPR|EU Product Liability Directive (EU) 2024/2853|NIST AI RMF','위험기반 규제|설명의무|인간감독|책임주체 식별|기능적 법적 지위|계층적 책임귀속','State v. Loomis|CJEU SCHUFA C-634/21|Mata v. Avianca|Thaler litigation','EU AI Act|한국 AI 기본법|미국 연방·주 규율|OECD AI Principles','EU AI Act|한국 AI 기본법|NIST AI RMF|OECD AI Principles|AI 책임법 학술문헌','의료 Agentic AI가 여러 도구를 호출해 오진한 경우|다중에이전트 시스템의 창발적 거래로 손해가 난 경우');
mk('PPA-101','행정학','행정국가와 관료제|Wilson과 정치·행정|Weber 관료제|Simon의 제한합리성|신공공관리|거버넌스|조직과 동기|성과관리|책임성과 통제|디지털정부|AI 행정|행정혁신 종합','정부조직법|행정기본법|국가공무원법|공공기관 운영 관련 법제','관료제|제한합리성|principal-agent|NPM|network governance|public value','행정조직 개편 사례|전자정부 정책사례','미국 PA|영국 NPM|북유럽 governance','Herbert Simon, Administrative Behavior|Max Weber, Economy and Society|Mark Moore, Creating Public Value','AI 민원분류 시스템 도입으로 담당공무원의 재량이 변화한 경우');
mk('PPA-102','정책학','정책문제 정의|의제설정|정책목표|대안형성|정책결정 모형|정책집행|정책평가|정책변동|이해관계자|증거기반정책|실험과 파일럿|AI 정책 종합','행정기본법|정부업무평가 관련 법제|규제영향분석 제도','multiple streams|punctuated equilibrium|advocacy coalition|incrementalism|evidence-based policy','주요 정책 실패·성공 사례군','미국 OMB 평가|영국 What Works|EU impact assessment','Kingdon, Agendas, Alternatives, and Public Policies|Sabatier, Theories of the Policy Process','공공부문 생성형 AI 도입정책의 목표와 평가지표 설계');
mk('PPA-103','정책분석','문제구조화|기준과 지표|비용편익분석|비용효과분석|할인율|위험·불확실성|민감도분석|분배효과|다기준의사결정|규제영향분석|시나리오 분석|AI 정책분석 실습','국가재정·규제영향 관련 지침|행정규제기본법','cost-benefit analysis|discounting|sensitivity analysis|MCDA|distributional analysis','대형 공공사업 타당성분석 사례|규제영향평가 사례','US OMB Circular A-4|EU Better Regulation','Boardman et al., Cost-Benefit Analysis|Dunn, Public Policy Analysis','AI 안전규제의 비용·편익과 분배효과를 비교하는 경우');
mk('PPA-104','규제이론','규제의 정당화|시장실패|정보비대칭|외부효과|명령통제|성과기반규제|자율규제·공동규제|responsive regulation|risk regulation|regulatory capture|sandbox|AI 위험규제','행정규제기본법|규제샌드박스 관련 법제|EU AI Act','market failure|responsive regulation|risk-based regulation|regulatory capture|principles-based regulation','환경·금융·플랫폼 규제사례','영국 principles-based regulation|EU risk regulation|미국 cost-benefit review','Ayres & Braithwaite, Responsive Regulation|Baldwin, Cave & Lodge, Understanding Regulation','고위험 AI 인증제와 자율규제를 조합하는 경우');
mk('PPA-105','조직론','고전 조직이론|관료제|인간관계론|의사결정이론|상황적합이론|자원의존|제도주의|조직문화|권력과 갈등|네트워크 조직|고신뢰조직|AI 조직설계','정부조직법|상법상 회사기관 관련 규범|공공기관 운영규범','bounded rationality|contingency theory|resource dependence|institutional isomorphism|high reliability organization','NASA Challenger 조직실패|대형 플랫폼 조직사고 사례','공공조직·기업조직 비교','James March & Herbert Simon, Organizations|Charles Perrow, Complex Organizations|Weick & Sutcliffe, Managing the Unexpected','AI 운영조직에서 개발·배치·감사팀 권한이 충돌하는 경우');
mk('PPA-106','행정조직','중앙행정기관|독립규제기관|지방행정|공공기관|위원회제|조직권한 배분|위임·전결|감사와 감독|전문성·독립성|협업정부|디지털 행정조직|AI 감독기관 설계','정부조직법|지방자치법|공공기관의 운영에 관한 법률|감사원법','조직법정주의|권한배분|독립성|책임성|전문규제기관','독립위원회 권한분쟁 사례군','미국 independent agencies|EU agencies','정부조직법|행정조직론 표준교재','AI 감독을 기존 개인정보·공정거래·산업부처 중 어디에 배분할지 설계');
mk('PPA-107','정부와 시장','정부개입의 근거|공공재|외부효과|정보비대칭|독점|정부실패|민영화|민관협력|공공조달|플랫폼 시장|산업정책|AI 인프라와 국가역할','국가계약법|공정거래법|공공조달 관련 법제','market failure|government failure|public choice|PPP|industrial policy','민영화·민관협력 사례|디지털 플랫폼 규제사례','미국 산업정책|EU strategic autonomy','Joseph Stiglitz, Economics of the Public Sector|public choice literature','국가가 AI 컴퓨팅 인프라에 직접 투자할지 보조금만 제공할지 결정하는 경우');
mk('PPA-108','위험규제','위험 개념|위해성과 노출|확률과 심각도|예방원칙|사전주의원칙|허용가능위험|위험평가|위험관리|위험소통|시스템 사고|복합·창발 위험|AI 안전규제','산업안전·환경·제품안전 관련 법제|EU AI Act|NIST AI RMF','precautionary principle|ALARP|risk matrix|system safety|normal accidents|resilience','Bhopal·Fukushima 등 위험사례|AI 사고·모델 실패사례','EU precautionary principle|미국 risk assessment','Cass Sunstein, Laws of Fear|Charles Perrow, Normal Accidents|NIST AI RMF','에이전트가 금융·메일·결제도구를 연쇄 호출하는 서비스의 위험등급 산정');
mk('PPA-109','과학기술정책','혁신시스템|R&D 정책|기초연구와 응용|특허·지식확산|산학협력|표준화|기술예측|전략기술|반도체·컴퓨팅|오픈소스|기술주권|AI 국가전략','과학기술기본법|국가연구개발혁신법|지식재산 관련 법제','national innovation system|mission-oriented innovation|technology foresight|standards policy','국가 R&D 프로젝트 사례|반도체 산업정책 사례','미국 CHIPS policy|EU Horizon/AI strategy','Christopher Freeman|Mariana Mazzucato, Mission Economy|OECD STI materials','국가 AI 모델 개발에 공공자금을 투입할 때 공개성과 안전조건 설계');
mk('PPA-110','AI 거버넌스','AI 거버넌스 개념|역할과 책임|AI 인벤토리|위험분류|데이터 거버넌스|모델 검증|인간감독|로그·감사|사고대응|공급망·제3자|국제표준|조직 거버넌스 Capstone','한국 AI 기본법|EU AI Act|NIST AI RMF|ISO/IEC 42001|ISO/IEC 23894','three lines model|risk ownership|model governance|assurance|auditability|incident response','금융 모델리스크 관리 사례|AI 서비스 사고대응 사례','NIST AI RMF|ISO 42001|EU AI Act conformity framework','NIST AI RMF|ISO/IEC 42001|ISO/IEC 23894|OECD AI Principles','기관이 외부 LLM과 내부 RAG·에이전트를 결합해 업무자동화를 운영하는 경우');
})();